// SPDX-FileCopyrightText: Copyright 2025 Stacklok, Inc.
// SPDX-License-Identifier: Apache-2.0

package signer

import (
	"context"
	"crypto"
	"crypto/rand"
	"crypto/x509"
	"encoding/pem"
	"fmt"
	"os"
	"path/filepath"

	"github.com/secure-systems-lab/go-securesystemslib/encrypted"
	protocommon "github.com/sigstore/protobuf-specs/gen/pb-go/common/v1"
	"github.com/sigstore/sigstore-go/pkg/sign"
	"github.com/sigstore/sigstore/pkg/cryptoutils"
)

// cosignEncryptedPEMTypes are the PEM labels the cosign CLI writes for
// password-protected private keys ("ENCRYPTED SIGSTORE PRIVATE KEY" today,
// the COSIGN spelling for keys generated by older releases).
//
// The label alone does not determine the payload. cosign seals the PKCS#8
// key with scrypt + nacl/secretbox via go-securesystemslib, whereas
// cryptoutils writes PKCS#8 standard encryption under the same label. Only
// the former is what `cosign generate-key-pair` produces, and cryptoutils
// cannot read it — it tries to parse the sealed blob as PKCS#8 and fails
// with an opaque ASN.1 error. Both are accepted here.
var cosignEncryptedPEMTypes = map[string]bool{
	"ENCRYPTED SIGSTORE PRIVATE KEY": true,
	"ENCRYPTED COSIGN PRIVATE KEY":   true,
}

// resolveKeyPath canonicalizes and vets a user-supplied signing key path:
// absolute, cleaned, symlinks resolved, and a regular file. The value comes
// straight from a --key flag, so this is the recognized sanitization
// barrier before the path is opened — no string-inspection shortcuts.
func resolveKeyPath(path string) (string, error) {
	if path == "" {
		return "", ErrKeyRequired
	}
	abs, err := filepath.Abs(path)
	if err != nil {
		return "", fmt.Errorf("resolving signing key path: %w", err)
	}
	resolved, err := filepath.EvalSymlinks(filepath.Clean(abs))
	if err != nil {
		return "", fmt.Errorf("resolving signing key path: %w", err)
	}
	info, err := os.Stat(resolved)
	if err != nil {
		return "", fmt.Errorf("reading signing key: %w", err)
	}
	if !info.Mode().IsRegular() {
		return "", fmt.Errorf("signing key %q is not a regular file", resolved)
	}
	return resolved, nil
}

// loadKeypair reads a cosign PEM private key from path. Encrypted keys are
// decrypted with the COSIGN_PASSWORD environment variable, matching the
// cosign CLI's behavior.
func loadKeypair(path string) (sign.Keypair, error) {
	resolved, err := resolveKeyPath(path)
	if err != nil {
		return nil, err
	}
	pemBytes, err := os.ReadFile(resolved) //nolint:gosec // resolved by resolveKeyPath from an explicit --key flag
	if err != nil {
		return nil, fmt.Errorf("reading signing key: %w", err)
	}
	priv, err := decodePrivateKeyPEM(pemBytes)
	if err != nil {
		return nil, err
	}
	signerKey, ok := priv.(crypto.Signer)
	if !ok {
		return nil, fmt.Errorf("signing key type %T cannot sign", priv)
	}
	return &fileKeypair{priv: signerKey}, nil
}

// decodePrivateKeyPEM decodes a signing key, accepting both the format the
// cosign CLI writes and the PKCS#8 forms cryptoutils handles.
func decodePrivateKeyPEM(pemBytes []byte) (crypto.PrivateKey, error) {
	block, _ := pem.Decode(pemBytes)
	if block == nil || !cosignEncryptedPEMTypes[block.Type] {
		priv, err := cryptoutils.UnmarshalPEMToPrivateKey(pemBytes, cosignPassFunc())
		if err != nil {
			return nil, fmt.Errorf("decoding signing key: %w", err)
		}
		return priv, nil
	}

	pass, err := cosignPassFunc()(false)
	if err != nil {
		return nil, fmt.Errorf("reading signing key password: %w", err)
	}
	der, decryptErr := encrypted.Decrypt(block.Bytes, pass)
	if decryptErr == nil {
		priv, parseErr := x509.ParsePKCS8PrivateKey(der)
		if parseErr != nil {
			return nil, fmt.Errorf("parsing decrypted signing key: %w", parseErr)
		}
		return priv, nil
	}

	// Same label, PKCS#8 standard encryption. Try that before giving up, but
	// report the cosign failure — for a key from `cosign generate-key-pair`
	// that is the real cause, and it is almost always a wrong password.
	priv, fallbackErr := cryptoutils.UnmarshalPEMToPrivateKey(pemBytes, cosignPassFunc())
	if fallbackErr != nil {
		return nil, fmt.Errorf("decrypting signing key (check COSIGN_PASSWORD): %w", decryptErr)
	}
	return priv, nil
}

func cosignPassFunc() cryptoutils.PassFunc {
	if pw := os.Getenv("COSIGN_PASSWORD"); pw != "" {
		return cryptoutils.StaticPasswordFunc([]byte(pw))
	}
	return func(_ bool) ([]byte, error) { return nil, nil }
}

// fileKeypair adapts a file-loaded private key to sigstore-go's signing
// Keypair interface (ECDSA P-256 / SHA-256, the cosign default).
type fileKeypair struct {
	priv crypto.Signer
}

func (*fileKeypair) GetHashAlgorithm() protocommon.HashAlgorithm {
	return protocommon.HashAlgorithm_SHA2_256
}

func (*fileKeypair) GetSigningAlgorithm() protocommon.PublicKeyDetails {
	return protocommon.PublicKeyDetails_PKIX_ECDSA_P256_SHA_256
}

func (k *fileKeypair) GetHint() []byte {
	pubKeyBytes, err := cryptoutils.MarshalPublicKeyToPEM(k.priv.Public())
	if err != nil {
		return nil
	}
	return pubKeyBytes
}

func (*fileKeypair) GetKeyAlgorithm() string {
	return "ecdsa"
}

func (k *fileKeypair) GetPublicKey() crypto.PublicKey {
	return k.priv.Public()
}

func (k *fileKeypair) GetPublicKeyPem() (string, error) {
	pemBytes, err := cryptoutils.MarshalPublicKeyToPEM(k.priv.Public())
	if err != nil {
		return "", err
	}
	return string(pemBytes), nil
}

// SignData hashes data with SHA-256 and signs the digest, returning
// (signature, digest) — the order sigstore-go's Keypair contract requires
// (see sign.EphemeralKeypair for the reference implementation).
func (k *fileKeypair) SignData(_ context.Context, data []byte) ([]byte, []byte, error) {
	hash := crypto.SHA256.New()
	if _, err := hash.Write(data); err != nil {
		return nil, nil, err
	}
	digest := hash.Sum(nil)
	sig, err := k.priv.Sign(rand.Reader, digest, crypto.SHA256)
	if err != nil {
		return nil, nil, err
	}
	return sig, digest, nil
}
