import type {
  OAuthMetadata,
  OAuthClientInformation,
  OAuthClientInformationFull,
  OAuthTokens,
  OAuthProtectedResourceMetadata,
} from "@modelcontextprotocol/client";

// OAuth flow steps. Extended for the 2026-07-28 authorization hardening:
// `cimd_fetch` (SEP-991 client-id metadata document registration), `issuer_comparison`
// (SEP-2352 authorization-server binding check), and `scope_step_up` (SEP-2350
// accumulated-scope re-authorization).
export type OAuthStep =
  | "metadata_discovery"
  | "client_registration"
  /** SEP-991 — registering via a Client ID Metadata Document instead of DCR. */
  | "cimd_fetch"
  /** SEP-2352 — comparing the resolved AS `issuer` against stored/discovered state. */
  | "issuer_comparison"
  | "authorization_redirect"
  | "authorization_code"
  /** SEP-2350 — re-authorizing with the accumulated (prior ∪ challenged) scope union. */
  | "scope_step_up"
  | "token_request"
  | "complete";

// Message types for inline feedback
export type MessageType = "success" | "error" | "info";

export interface StatusMessage {
  type: MessageType;
  message: string;
}

/** Which authorization protocol applies. */
export type AuthProtocol = "standard" | "ema";

/** How the active OAuth client id was established for this MCP server. */
export type OAuthClientRegistrationKind = "static" | "dcr" | "cimd";

/** Persisted OAuth authorization snapshot for an HTTP MCP server (storage + config). */
export interface OAuthConnectionState {
  authorized: boolean;
  protocol: AuthProtocol;
  serverUrl: string;
  configuredScope?: string;
  grantedScope?: string;
  tokens?: OAuthTokens;
  client?: {
    clientId: string;
    /** Absent for legacy storage entries predating registration kind tracking. */
    registrationKind?: OAuthClientRegistrationKind;
    hasClientSecret: boolean;
  };
  authorizationServerMetadata?: OAuthMetadata;
  enterpriseManaged?: boolean;
  ema?: {
    idpIssuer: string;
    idpClientId: string;
    idpSession: "none" | "logged_in" | "expired";
    idpMetadata?: OAuthMetadata;
  };
}

export function authProtocolFromEnterpriseManaged(
  enterpriseManaged?: boolean,
): AuthProtocol {
  return enterpriseManaged ? "ema" : "standard";
}

/** In-memory snapshot while an OAuth flow is active or just completed. */
export interface OAuthFlowState {
  /** When auth reached step "complete" (ms since epoch), if applicable. */
  completedAt: number | null;
  isInitiatingAuth: boolean;
  oauthTokens: OAuthTokens | null;
  oauthStep: OAuthStep;
  resourceMetadata: OAuthProtectedResourceMetadata | null;
  resourceMetadataError: Error | null;
  resource: URL | null;
  authServerUrl: URL | null;
  oauthMetadata: OAuthMetadata | null;
  oauthClientInfo: OAuthClientInformationFull | OAuthClientInformation | null;
  authorizationUrl: URL | null;
  authorizationCode: string;
  latestError: Error | null;
  statusMessage: StatusMessage | null;
  validationError: string | null;
}

export const EMPTY_OAUTH_FLOW_STATE: OAuthFlowState = {
  completedAt: null,
  isInitiatingAuth: false,
  oauthTokens: null,
  oauthStep: "authorization_code",
  oauthMetadata: null,
  resourceMetadata: null,
  resourceMetadataError: null,
  resource: null,
  authServerUrl: null,
  oauthClientInfo: null,
  authorizationUrl: null,
  authorizationCode: "",
  latestError: null,
  statusMessage: null,
  validationError: null,
};

// The parsed query parameters returned by the Authorization Server
// representing either a valid authorization_code or an error
// ref: https://datatracker.ietf.org/doc/html/draft-ietf-oauth-v2-1-12#section-4.1.2
export type CallbackParams =
  | {
      successful: true;
      // The authorization code is generated by the authorization server.
      code: string;
      // RFC 9207 `iss`. Present only when the authorization server includes it.
      // Forwarded to the SDK, which validates it against the issuer in the
      // validated metadata (RFC 9207 §2.4) to detect mix-up attacks. Servers
      // advertising `authorization_response_iss_parameter_supported: true` MUST
      // send it, and the SDK rejects the callback when it is missing.
      iss?: string;
    }
  | {
      successful: false;
      // The OAuth 2.1 Error Code.
      // Usually one of:
      //    ```
      //    invalid_request, unauthorized_client, access_denied, unsupported_response_type,
      //    invalid_scope, server_error, temporarily_unavailable
      //    ```
      error: string;
      // Human-readable ASCII text providing additional information, used to assist the
      // developer in understanding the error that occurred.
      error_description: string | null;
      // A URI identifying a human-readable web page with information about the error,
      // used to provide the client developer with additional information about the error.
      error_uri: string | null;
    };
