import { z } from "zod";
import type { ToolArgs, OperationType, ToolExecutionContext, ToolResult } from "../../tool.js";
import { AtlasToolBase } from "../atlasTool.js";
import type { CloudDatabaseUser, DatabaseUserRole } from "../../../common/atlas/openapi.js";
import { generateSecurePassword } from "../../../helpers/generatePassword.js";
import { escapeMarkdown } from "../../../helpers/escapeMarkdown.js";
import { ensureCurrentIpInAccessList, getAccessListNote } from "../../../common/atlas/accessListUtils.js";
import { ALPHANUMERIC_DASH_UNDERSCORE_REGEX, AtlasArgs, CommonArgs } from "../../args.js";
import { BUILT_IN_DB_USER_ROLES } from "../../../common/atlas/roles.js";

export const CreateDBUserArgs = {
    projectId: AtlasArgs.projectId().describe("Atlas project ID"),
    username: AtlasArgs.username().describe("Username for the new user"),
    // Models will generate overly simplistic passwords like SecurePassword123 or
    // AtlasPassword123, which are easily guessable and exploitable. We're instructing
    // the model not to try and generate anything and instead leave the field unset.
    password: AtlasArgs.password()
        .optional()
        .describe(
            "Password for the new user. IMPORTANT: If the user hasn't supplied an explicit password, leave it unset and under no circumstances try to generate a random one. A secure password will be generated by the MCP server if necessary."
        ),
    roles: z
        .array(
            z.object({
                roleName: z
                    .union([
                        z.enum(BUILT_IN_DB_USER_ROLES),
                        z
                            .string()
                            .regex(
                                ALPHANUMERIC_DASH_UNDERSCORE_REGEX,
                                "Custom role names can only contain letters, numbers, hyphens, and underscores"
                            ),
                    ])
                    .describe("Role name"),
                databaseName: CommonArgs.string().describe("Database name").default("admin"),
                collectionName: CommonArgs.string().describe("Collection name").optional(),
            })
        )
        .describe("Roles for the new user"),
    clusters: z
        .array(AtlasArgs.clusterName())
        .describe("Clusters to assign the user to, leave empty for access to all clusters")
        .optional(),
};

const CreateDBUserOutputSchema = {
    username: z.string(),
    password: z.string().optional(),
};

export class CreateDBUserTool extends AtlasToolBase {
    static toolName = "atlas-create-db-user";
    public description = "Create an MongoDB Atlas database user";
    static operationType: OperationType = "create";
    public argsShape = {
        ...CreateDBUserArgs,
    };
    public override outputSchema = CreateDBUserOutputSchema;

    protected async execute(
        { projectId, username, password, roles, clusters }: ToolArgs<typeof this.argsShape>,
        context: ToolExecutionContext
    ): Promise<ToolResult<typeof this.outputSchema>> {
        const ipAccessListResult = await ensureCurrentIpInAccessList(this.apiClient, projectId, context);
        const shouldGeneratePassword = !password;
        if (shouldGeneratePassword) {
            password = await generateSecurePassword();
        }

        const input = {
            groupId: projectId,
            awsIAMType: "NONE",
            databaseName: "admin",
            ldapAuthType: "NONE",
            oidcAuthType: "NONE",
            x509Type: "NONE",
            username,
            password,
            roles: roles as unknown as DatabaseUserRole[],
            scopes: clusters?.length
                ? clusters.map((cluster) => ({
                      type: "CLUSTER",
                      name: cluster,
                  }))
                : undefined,
        } as CloudDatabaseUser;

        await this.apiClient.createDatabaseUser(
            {
                params: {
                    path: {
                        groupId: projectId,
                    },
                },
                body: input,
            },
            context
        );

        this.session.keychain.register(username, "user");
        if (password) {
            this.session.keychain.register(password, "password");
        }

        const ipAccessListNote = getAccessListNote(ipAccessListResult);

        return {
            content: [
                {
                    type: "text",
                    text: `User "${username}" created successfully${shouldGeneratePassword ? ` with password: \`${password}\`` : ""}.`,
                },
                ...(ipAccessListNote ? [{ type: "text" as const, text: ipAccessListNote }] : []),
            ],
            structuredContent: {
                username,
                ...(shouldGeneratePassword && { password }),
            },
        };
    }

    protected getConfirmationMessage({
        projectId,
        username,
        password,
        roles,
        clusters,
    }: ToolArgs<typeof this.argsShape>): string {
        return (
            `You are about to create a database user in Atlas project \`${projectId}\`:\n\n` +
            `**Username**: \`${username}\`\n\n` +
            `**Password**: ${password ? "(User-provided password)" : "(Auto-generated secure password)"}\n\n` +
            `**Roles**: ${roles
                .map((role) => {
                    const target = role.collectionName
                        ? `${escapeMarkdown(role.databaseName)}.${escapeMarkdown(role.collectionName)}`
                        : escapeMarkdown(role.databaseName);
                    return `${escapeMarkdown(role.roleName)} on ${target}`;
                })
                .join(", ")}\n\n` +
            `**Cluster Access**: ${clusters?.length ? clusters.join(", ") : "All clusters in the project"}\n\n` +
            "This will create a new database user with the specified permissions. " +
            "**Do you confirm the execution of the action?**"
        );
    }
}
