"""Add calendar tables

Revision ID: 2ac6c433442a
Revises: c8f3a2b1d9e4
Create Date: 2026-01-19 15:50:46.254187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2ac6c433442a'
down_revision: Union[str, None] = 'c8f3a2b1d9e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_channels',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=False),
    sa.Column('resource_uri', sa.String(length=1000), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=1000), nullable=False),
    sa.Column('expiration', sa.Integer(), nullable=True),
    sa.Column('token', sa.String(length=500), nullable=True),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('payload', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calendar_users',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('self', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('calendar_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('setting_id', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('etag', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['calendar_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'setting_id', name='uq_user_setting')
    )
    op.create_table('calendar_sync_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('snapshot_time', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['calendar_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index('ix_sync_token_resource', 'calendar_sync_tokens', ['resource_type', 'resource_id'], unique=False)
    op.create_table('calendars',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('time_zone', sa.String(length=100), nullable=True),
    sa.Column('etag', sa.String(length=100), nullable=False),
    sa.Column('conference_properties', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('auto_accept_invitations', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('owner_id', sa.String(length=255), nullable=False),
    sa.Column('data_owner', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['calendar_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calendar_acl_rules',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('calendar_id', sa.String(length=255), nullable=False),
    sa.Column('etag', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('none', 'freeBusyReader', 'reader', 'writer', 'owner', name='acl_role_enum', schema='public'), nullable=False),
    sa.Column('scope_type', sa.Enum('default', 'user', 'group', 'domain', name='acl_scope_type_enum', schema='public'), nullable=False),
    sa.Column('scope_value', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['calendar_id'], ['calendars.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('calendar_id', 'scope_type', 'scope_value', name='uq_acl_rule')
    )
    op.create_index('ix_acl_calendar', 'calendar_acl_rules', ['calendar_id'], unique=False)
    op.create_table('calendar_events',
    sa.Column('id', sa.String(length=1024), nullable=False),
    sa.Column('calendar_id', sa.String(length=255), nullable=False),
    sa.Column('etag', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('confirmed', 'tentative', 'cancelled', name='event_status_enum', schema='public'), nullable=False),
    sa.Column('html_link', sa.String(length=500), nullable=True),
    sa.Column('summary', sa.String(length=1000), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=1000), nullable=True),
    sa.Column('color_id', sa.String(length=10), nullable=True),
    sa.Column('creator_id', sa.String(length=255), nullable=True),
    sa.Column('organizer_id', sa.String(length=255), nullable=True),
    sa.Column('creator_email', sa.String(length=255), nullable=True),
    sa.Column('organizer_email', sa.String(length=255), nullable=True),
    sa.Column('creator_display_name', sa.String(length=255), nullable=True),
    sa.Column('organizer_display_name', sa.String(length=255), nullable=True),
    sa.Column('creator_profile_id', sa.String(length=255), nullable=True),
    sa.Column('organizer_profile_id', sa.String(length=255), nullable=True),
    sa.Column('creator_self', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('organizer_self', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('start', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('end', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('start_datetime', sa.DateTime(), nullable=True),
    sa.Column('end_datetime', sa.DateTime(), nullable=True),
    sa.Column('start_date', sa.String(length=10), nullable=True),
    sa.Column('end_date', sa.String(length=10), nullable=True),
    sa.Column('end_time_unspecified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('recurrence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recurring_event_id', sa.String(length=1024), nullable=True),
    sa.Column('original_start_time', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('transparency', sa.Enum('opaque', 'transparent', name='event_transparency_enum', schema='public'), nullable=False),
    sa.Column('visibility', sa.Enum('default', 'public', 'private', 'confidential', name='event_visibility_enum', schema='public'), nullable=False),
    sa.Column('ical_uid', sa.String(length=1024), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('guests_can_invite_others', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('guests_can_modify', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('guests_can_see_other_guests', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('anyone_can_add_self', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('private_copy', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('locked', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('attendees_omitted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('hangout_link', sa.String(length=500), nullable=True),
    sa.Column('conference_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extended_properties', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('gadget', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reminders', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('event_type', sa.Enum('default', 'outOfOffice', 'focusTime', 'workingLocation', 'fromGmail', 'birthday', name='event_type_enum', schema='public'), nullable=False),
    sa.Column('working_location_properties', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('out_of_office_properties', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('focus_time_properties', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('birthday_properties', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['calendar_id'], ['calendars.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['calendar_users.id'], ),
    sa.ForeignKeyConstraint(['organizer_id'], ['calendar_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_event_calendar', 'calendar_events', ['calendar_id'], unique=False)
    op.create_index('ix_event_end', 'calendar_events', ['end_datetime'], unique=False)
    op.create_index('ix_event_ical_uid', 'calendar_events', ['ical_uid'], unique=False)
    op.create_index('ix_event_recurring', 'calendar_events', ['recurring_event_id'], unique=False)
    op.create_index('ix_event_start', 'calendar_events', ['start_datetime'], unique=False)
    op.create_index('ix_event_updated', 'calendar_events', ['updated_at'], unique=False)
    op.create_table('calendar_list_entries',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('calendar_id', sa.String(length=255), nullable=False),
    sa.Column('etag', sa.String(length=100), nullable=False),
    sa.Column('access_role', sa.Enum('none', 'freeBusyReader', 'reader', 'writer', 'owner', name='access_role_enum', schema='public'), nullable=False),
    sa.Column('summary_override', sa.String(length=255), nullable=True),
    sa.Column('description_override', sa.Text(), nullable=True),
    sa.Column('color_id', sa.String(length=10), nullable=True),
    sa.Column('background_color', sa.String(length=10), nullable=True),
    sa.Column('foreground_color', sa.String(length=10), nullable=True),
    sa.Column('hidden', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('selected', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('primary', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('default_reminders', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notification_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['calendar_id'], ['calendars.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['calendar_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'calendar_id', name='uq_user_calendar')
    )
    op.create_index('ix_calendar_list_user', 'calendar_list_entries', ['user_id'], unique=False)
    op.create_table('calendar_event_attendees',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=1024), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('organizer', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('self', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('resource', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('optional', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('response_status', sa.Enum('needsAction', 'declined', 'tentative', 'accepted', name='attendee_response_enum', schema='public'), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('additional_guests', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('profile_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['calendar_events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'email', name='uq_event_attendee')
    )
    op.create_index('ix_attendee_email', 'calendar_event_attendees', ['email'], unique=False)
    op.create_index('ix_attendee_event', 'calendar_event_attendees', ['event_id'], unique=False)
    op.create_table('calendar_event_reminders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=1024), nullable=False),
    sa.Column('method', sa.Enum('email', 'popup', name='reminder_method_enum', schema='public'), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['calendar_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reminder_event', 'calendar_event_reminders', ['event_id'], unique=False)
    op.drop_constraint(op.f('change_journal_environment_id_fkey'), 'change_journal', type_='foreignkey')
    op.create_foreign_key('change_journal_environment_id_fkey_new', 'change_journal', 'run_time_environments', ['environment_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('diffs_environment_id_fkey'), 'diffs', type_='foreignkey')
    op.create_foreign_key('diffs_environment_id_fkey_new', 'diffs', 'run_time_environments', ['environment_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_index(op.f('ix_environment_pool_template_status'), table_name='environment_pool_entries')
    op.drop_constraint(op.f('environment_pool_entries_template_id_fkey'), 'environment_pool_entries', type_='foreignkey')
    op.create_foreign_key('environment_pool_entries_template_id_fkey_new', 'environment_pool_entries', 'environments', ['template_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('snapshot_metadata_environment_id_fkey'), 'snapshot_metadata', type_='foreignkey')
    op.create_foreign_key('snapshot_metadata_environment_id_fkey_new', 'snapshot_metadata', 'run_time_environments', ['environment_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('test_memberships_test_id_fkey'), 'test_memberships', type_='foreignkey')
    op.drop_constraint(op.f('test_memberships_test_suite_id_fkey'), 'test_memberships', type_='foreignkey')
    op.create_foreign_key('test_memberships_test_id_fkey_new', 'test_memberships', 'tests', ['test_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key('test_memberships_test_suite_id_fkey_new', 'test_memberships', 'test_suites', ['test_suite_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('test_runs_environment_id_fkey'), 'test_runs', type_='foreignkey')
    op.drop_constraint(op.f('test_runs_test_id_fkey'), 'test_runs', type_='foreignkey')
    op.drop_constraint(op.f('test_runs_test_suite_id_fkey'), 'test_runs', type_='foreignkey')
    op.create_foreign_key('test_runs_test_suite_id_fkey_new', 'test_runs', 'test_suites', ['test_suite_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key('test_runs_test_id_fkey_new', 'test_runs', 'tests', ['test_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key('test_runs_environment_id_fkey_new', 'test_runs', 'run_time_environments', ['environment_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop FKs with explicit names created in upgrade, restore original FKs
    op.drop_constraint('test_runs_test_suite_id_fkey_new', 'test_runs', schema='public', type_='foreignkey')
    op.drop_constraint('test_runs_test_id_fkey_new', 'test_runs', schema='public', type_='foreignkey')
    op.drop_constraint('test_runs_environment_id_fkey_new', 'test_runs', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('test_runs_test_suite_id_fkey'), 'test_runs', 'test_suites', ['test_suite_id'], ['id'])
    op.create_foreign_key(op.f('test_runs_test_id_fkey'), 'test_runs', 'tests', ['test_id'], ['id'])
    op.create_foreign_key(op.f('test_runs_environment_id_fkey'), 'test_runs', 'run_time_environments', ['environment_id'], ['id'])
    op.drop_constraint('test_memberships_test_suite_id_fkey_new', 'test_memberships', schema='public', type_='foreignkey')
    op.drop_constraint('test_memberships_test_id_fkey_new', 'test_memberships', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('test_memberships_test_suite_id_fkey'), 'test_memberships', 'test_suites', ['test_suite_id'], ['id'])
    op.create_foreign_key(op.f('test_memberships_test_id_fkey'), 'test_memberships', 'tests', ['test_id'], ['id'])
    op.drop_constraint('snapshot_metadata_environment_id_fkey_new', 'snapshot_metadata', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('snapshot_metadata_environment_id_fkey'), 'snapshot_metadata', 'run_time_environments', ['environment_id'], ['id'])
    op.drop_constraint('environment_pool_entries_template_id_fkey_new', 'environment_pool_entries', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('environment_pool_entries_template_id_fkey'), 'environment_pool_entries', 'environments', ['template_id'], ['id'])
    op.create_index(op.f('ix_environment_pool_template_status'), 'environment_pool_entries', ['template_schema', 'status'], unique=False)
    op.drop_constraint('diffs_environment_id_fkey_new', 'diffs', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('diffs_environment_id_fkey'), 'diffs', 'run_time_environments', ['environment_id'], ['id'])
    op.drop_constraint('change_journal_environment_id_fkey_new', 'change_journal', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('change_journal_environment_id_fkey'), 'change_journal', 'run_time_environments', ['environment_id'], ['id'])
    op.drop_index('ix_reminder_event', table_name='calendar_event_reminders')
    op.drop_table('calendar_event_reminders')
    op.drop_index('ix_attendee_event', table_name='calendar_event_attendees')
    op.drop_index('ix_attendee_email', table_name='calendar_event_attendees')
    op.drop_table('calendar_event_attendees')
    op.drop_index('ix_calendar_list_user', table_name='calendar_list_entries')
    op.drop_table('calendar_list_entries')
    op.drop_index('ix_event_updated', table_name='calendar_events')
    op.drop_index('ix_event_start', table_name='calendar_events')
    op.drop_index('ix_event_recurring', table_name='calendar_events')
    op.drop_index('ix_event_ical_uid', table_name='calendar_events')
    op.drop_index('ix_event_end', table_name='calendar_events')
    op.drop_index('ix_event_calendar', table_name='calendar_events')
    op.drop_table('calendar_events')
    op.drop_index('ix_acl_calendar', table_name='calendar_acl_rules')
    op.drop_table('calendar_acl_rules')
    op.drop_table('calendars')
    op.drop_index('ix_sync_token_resource', table_name='calendar_sync_tokens')
    op.drop_table('calendar_sync_tokens')
    op.drop_table('calendar_settings')
    op.drop_table('calendar_users')
    op.drop_table('calendar_channels')
    
    # Drop PostgreSQL enum types created by this migration
    op.execute("DROP TYPE IF EXISTS acl_role_enum")
    op.execute("DROP TYPE IF EXISTS acl_scope_type_enum")
    op.execute("DROP TYPE IF EXISTS access_role_enum")
    op.execute("DROP TYPE IF EXISTS event_status_enum")
    op.execute("DROP TYPE IF EXISTS event_transparency_enum")
    op.execute("DROP TYPE IF EXISTS event_visibility_enum")
    op.execute("DROP TYPE IF EXISTS event_type_enum")
    op.execute("DROP TYPE IF EXISTS attendee_response_enum")
    op.execute("DROP TYPE IF EXISTS reminder_method_enum")
    # ### end Alembic commands ###
