#!/usr/bin/env bun
/**
 * ============================================================================
 * UpdateModels — drift check + safe registry bump for model IDs
 * ============================================================================
 *
 * The companion to models.ts. Two modes, propose-not-auto by design:
 *
 *   bun UpdateModels.ts --check
 *     Scans the live tree for pinned Claude IDs and reports any that don't
 *     match the registry (models.ts CURRENT). Excludes historical Algorithm
 *     snapshots, node_modules, and release staging. Exit 0 = no drift, 1 = drift.
 *
 *   bun UpdateModels.ts --apply <tier> <new-id>
 *     Rewrites ONLY models.ts CURRENT[tier] to <new-id>. Touches nothing else —
 *     consumers either use aliases (auto-track) or import the registry. After
 *     applying, re-run --check to confirm the tree is clean.
 *
 * ON A NEW RELEASE the _NEWS Anthropic monitor surfaces a proposal; a human
 * approves, runs --apply, runs --check. No silent system-wide edits.
 * ============================================================================
 */

import { readFileSync, writeFileSync, appendFileSync, readdirSync } from "fs";
import { join } from "path";
import { CURRENT, EFFORT_MODEL, CLAUDE_ID_PATTERN, type ClaudeTier } from "./models";

const CLAUDE_DIR = join(import.meta.dir, "..", "..");
const REGISTRY_PATH = join(import.meta.dir, "models.ts");

/**
 * Paths excluded from drift scanning. The scan targets LIVE single-pin drift —
 * a dated ID where an alias or the registry should be. It deliberately ignores:
 *   - vendored / third-party code (we don't own its model refs)
 *   - frozen records (historical doctrine, eval run artifacts, ISA evidence)
 *   - test fixtures (intentionally use old/new IDs)
 *   - recognition/price maps (cost-aggregator, Evals graders) — these list many
 *     historical IDs on purpose; a missing entry falls through, it isn't drift
 *   - the registry + its own docs (they cite old IDs to explain themselves)
 */
export const SCAN_EXCLUDES = [
  "node_modules",
  "LIFEOS_RELEASES",
  "profile-data",
  "plugins/",            // third-party marketplace plugins
  "LIFEOS/ALGORITHM/v",     // historical doctrine snapshots keep their period IDs
  "ALGORITHM/changelog.md", // the changelog records what WAS current at each version
  "/State/",                // skill runtime state (cached scan results), not source
  "MEMORY/WORK",         // ISA bodies may quote IDs as evidence
  "history.jsonl",
  "cache/",
  "/test/",              // test fixtures intentionally use old/new IDs
  ".test.ts",            // ditto for co-located tests (e.g. Inference.verification.test.ts,
                         // whose mock modelUsage envelopes pin arbitrary IDs by design)
  "Evals/",              // evals PIN a model on purpose — reproducible apples-to-apples comparison; aliasing would break the eval
  "cost-aggregator",     // historical price table keyed by past model IDs
  "Schema/Fixtures",     // generated Data Plane snapshots — regenerated by Pulse RebuildAll from the (aliased) manifests
  "LIFEOS/TOOLS/models.ts", // the registry cites superseded IDs in comments
  "DOCUMENTATION/",      // docs reference old IDs as examples
];

export type DriftHit = { id: string; tier: ClaudeTier; status: "current" | "stale" };

/** Tier of a Claude ID, or null if unparseable. */
export function tierOf(id: string): ClaudeTier | null {
  const m = id.match(/claude-(opus|sonnet|haiku|fable)-/);
  return m ? (m[1] as ClaudeTier) : null;
}

/** Classify a found Claude ID against the registry. Pure — drives the tests. */
export function classify(id: string): DriftHit | null {
  const tier = tierOf(id);
  if (!tier) return null;
  return { id, tier, status: id === CURRENT[tier] ? "current" : "stale" };
}

/**
 * Rewrite the CURRENT[tier] line in models.ts source. Pure string transform so
 * tests can exercise it without disk I/O. Returns the new source, or throws if
 * the tier line isn't found (fail loud — never silently no-op a bump).
 */
export function applyToRegistrySource(src: string, tier: ClaudeTier, newId: string): string {
  const re = new RegExp(`(\\b${tier}:\\s*")[^"]+(")`);
  if (!re.test(src)) throw new Error(`CURRENT.${tier} line not found in registry source`);
  return src.replace(re, `$1${newId}$2`);
}

/**
 * Find Claude model IDs in arbitrary text (e.g. a changelog digest) that the
 * registry does NOT recognize — candidates for a just-released model. Pure and
 * deduped so the _NEWS monitor and tests can both call it. A human triages the
 * result (propose-not-auto); old IDs quoted in news may also surface, which is
 * fine for a flag.
 */
export function detectNewModelIds(text: string): string[] {
  const seen = new Set<string>();
  for (const m of text.matchAll(CLAUDE_ID_PATTERN)) {
    const id = m[0];
    const hit = classify(id);
    if (hit && hit.status === "stale") seen.add(id);
  }
  return [...seen];
}

export const MODEL_RELEASES_PATH = join(CLAUDE_DIR, "LIFEOS", "MEMORY", "OBSERVABILITY", "model-releases.jsonl");

/**
 * Build the propose-not-auto action commands for detected IDs. Each is a full,
 * runnable two-step (apply the bump, then re-check). Pure — drives the test.
 * NOTE: deliberately NOT the memory pending-proposals queue — that queue
 * applies *text edits to markdown sections* (applyProposalEdit appends under a
 * header), which cannot rewrite the registry's TS const. A model bump is a
 * command, not a text-append, so it gets its own surface + a /notify.
 */
export function buildActionCommands(ids: string[]): string[] {
  return ids.map((id) => {
    const t = tierOf(id);
    return t
      ? `bun ~/.claude/LIFEOS/TOOLS/UpdateModels.ts --apply ${t} ${id} && bun ~/.claude/LIFEOS/TOOLS/UpdateModels.ts --check`
      : `review ${id} (unparseable tier)`;
  });
}

/**
 * Record a detected model release to a dedicated log and best-effort notify the
 * principal. Propose-not-auto: never bumps the registry. `logPath` is injectable
 * for tests. Returns the row written (for assertions).
 */
export function emitModelProposal(
  ids: string[],
  source: string,
  nowIso: string,
  logPath: string = MODEL_RELEASES_PATH,
  notify: boolean = true,
): Record<string, unknown> | null {
  if (ids.length === 0) return null;
  const row = {
    ts: nowIso,
    kind: "model-release",
    source,
    detected_ids: ids,
    registry: CURRENT,
    action: buildActionCommands(ids),
    note: "Propose-only. New Claude model ID detected; review, then run the action command to bump the registry.",
  };
  try {
    appendFileSync(logPath, JSON.stringify(row) + "\n");
  } catch {
    writeFileSync(logPath, JSON.stringify(row) + "\n");
  }
  // Best-effort reach the principal — never let a notify failure break the caller.
  if (notify) try {
    Bun.spawnSync(
      ["curl", "-sk", "-m", "5", "-X", "POST", "http://localhost:31337/notify",
       "-H", "Content-Type: application/json",
       "-d", JSON.stringify({ message: `New Claude model detected: ${ids.join(", ")}. Review and run UpdateModels --apply.`, voice_enabled: true })],
      { stdout: "ignore", stderr: "ignore" },
    );
  } catch { /* notify is best-effort */ }
  return row;
}

function isExcluded(path: string): boolean {
  return SCAN_EXCLUDES.some((ex) => path.includes(ex));
}

export type ScanResult = { path: string; hit: DriftHit };

/**
 * Categorize `rg -o -N` output (path:id per line) into two action classes.
 * Pure — tests drive it without spawning rg. Cato's blind-spot lesson: a dated
 * pin that EQUALS current today is still a landmine (it silently rots on the
 * next bump), so "current-but-pinned" in live code is reported, not just stale.
 *   - stale:    dated pin ≠ registry → wrong now
 *   - landmine: dated pin = registry → right now, will rot; alias or import it
 * Excluded paths (recognition maps, tests, historical, registry) are dropped.
 */
export function categorizeScanLines(rgOutput: string): { stale: ScanResult[]; landmine: ScanResult[] } {
  const stale: ScanResult[] = [];
  const landmine: ScanResult[] = [];
  for (const line of rgOutput.split("\n")) {
    if (!line.trim()) continue;
    const idx = line.lastIndexOf(":");
    const path = line.slice(0, idx);
    const id = line.slice(idx + 1).trim();
    if (isExcluded(path)) continue;
    const hit = classify(id);
    if (!hit) continue;
    if (hit.status === "stale") stale.push({ path, hit });
    else landmine.push({ path, hit }); // status === "current" but still pinned
  }
  return { stale, landmine };
}

function scanTree(): { stale: ScanResult[]; landmine: ScanResult[] } {
  const proc = Bun.spawnSync(
    ["rg", "--no-heading", "-o", "-N", CLAUDE_ID_PATTERN.source, CLAUDE_DIR, "--glob", "!**/node_modules/**"],
    { stdout: "pipe", stderr: "pipe" }
  );
  return categorizeScanLines(new TextDecoder().decode(proc.stdout));
}

/**
 * Validate agent frontmatter against the registry (v6.15.0 four-level layer).
 * Static agent `model:` frontmatter can't import models.ts, so it's the one
 * routing surface that can rot silently on a lineup change. Two assertions:
 *   1. every agents/*.md `model:` value is a known tier alias
 *   2. any agent self-declared as a "MAX persona" pins the alias
 *      that EFFORT_MODEL.max currently resolves to — so remapping max in
 *      models.ts makes --check name the exact frontmatter lines to update,
 *      keeping the one-line-swap story honest end to end.
 * Pure-ish (injectable dir) so tests can drive it.
 */
export function checkAgentFrontmatter(agentsDir: string = join(CLAUDE_DIR, "agents")): string[] {
  const problems: string[] = [];
  const validAliases = new Set(Object.keys(CURRENT));
  const maxAlias = EFFORT_MODEL.max;
  let files: string[];
  try {
    files = readdirSync(agentsDir).filter((f) => f.endsWith(".md"));
  } catch {
    return problems; // no agents dir — nothing to validate
  }
  for (const f of files) {
    const src = readFileSync(join(agentsDir, f), "utf8");
    const fm = src.match(/^---\n([\s\S]*?)\n---/);
    if (!fm) continue;
    const modelLine = fm[1].match(/^model:\s*(\S+)/m);
    if (!modelLine) continue;
    const model = modelLine[1];
    if (!validAliases.has(model)) {
      problems.push(`agents/${f}: model '${model}' is not a known tier alias (${[...validAliases].join(" | ")})`);
    }
    if (/MAX persona/i.test(fm[1]) && model !== maxAlias) {
      problems.push(`agents/${f}: MAX persona pinned to '${model}' but EFFORT_MODEL.max resolves to '${maxAlias}' — update frontmatter`);
    }
  }
  return problems;
}

function check(): number {
  const { stale, landmine } = scanTree();
  const frontmatterProblems = checkAgentFrontmatter();
  if (frontmatterProblems.length > 0) {
    console.log(`\n⚠️  ${frontmatterProblems.length} agent-frontmatter problem(s) vs EFFORT_MODEL:`);
    for (const p of frontmatterProblems) console.log(`  ${p}`);
  }
  if (stale.length === 0 && landmine.length === 0 && frontmatterProblems.length > 0) return 1;
  if (stale.length === 0 && landmine.length === 0) {
    console.log("✅ No model drift. All pinned Claude IDs match the registry, or consumers use aliases.");
    return 0;
  }
  console.log("Registry says:");
  for (const t of Object.keys(CURRENT) as ClaudeTier[]) console.log(`    ${t}: ${CURRENT[t]}`);
  if (stale.length > 0) {
    console.log(`\n⚠️  ${stale.length} STALE pinned ID(s) — wrong now, bump or alias:`);
    for (const { path, hit } of stale) console.log(`  ${path}: '${hit.id}' (${hit.tier}) → expected '${CURRENT[hit.tier]}'`);
  }
  if (landmine.length > 0) {
    console.log(`\n🧨 ${landmine.length} pinned-but-current ID(s) — correct today, will rot on next ${landmine[0].hit.tier} bump. Prefer alias ("${landmine[0].hit.tier}") or import the registry:`);
    for (const { path, hit } of landmine) console.log(`  ${path}: '${hit.id}' (${hit.tier})`);
  }
  return 1;
}



function apply(tier: string, newId: string): number {
  if (!["opus", "sonnet", "haiku", "fable"].includes(tier)) {
    console.error(`Invalid tier '${tier}'. Use opus | sonnet | haiku | fable.`);
    return 1;
  }
  const src = readFileSync(REGISTRY_PATH, "utf8");
  const next = applyToRegistrySource(src, tier as ClaudeTier, newId);
  writeFileSync(REGISTRY_PATH, next);
  console.log(`✅ Registry CURRENT.${tier} → '${newId}'.`);
  console.log("   Propose-mode: only models.ts was touched. Next: re-run --check, review any flagged consumers, commit.");
  return 0;
}

if (import.meta.main) {
  const args = process.argv.slice(2);
  if (args[0] === "--check") process.exit(check());
  else if (args[0] === "--apply" && args[1] && args[2]) process.exit(apply(args[1], args[2]));
  else {
    console.error("Usage: UpdateModels.ts --check | --apply <opus|sonnet|haiku|fable> <new-id>");
    process.exit(2);
  }
}
