// Code generated by MockGen. DO NOT EDIT.
// Source: types.go
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_collector.go -package=mocks -source=types.go StatusManager
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	v1beta1 "github.com/stacklok/toolhive/cmd/thv-operator/api/v1beta1"
	gomock "go.uber.org/mock/gomock"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// MockStatusManager is a mock of StatusManager interface.
type MockStatusManager struct {
	ctrl     *gomock.Controller
	recorder *MockStatusManagerMockRecorder
	isgomock struct{}
}

// MockStatusManagerMockRecorder is the mock recorder for MockStatusManager.
type MockStatusManagerMockRecorder struct {
	mock *MockStatusManager
}

// NewMockStatusManager creates a new mock instance.
func NewMockStatusManager(ctrl *gomock.Controller) *MockStatusManager {
	mock := &MockStatusManager{ctrl: ctrl}
	mock.recorder = &MockStatusManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatusManager) EXPECT() *MockStatusManagerMockRecorder {
	return m.recorder
}

// RemoveConditionsWithPrefix mocks base method.
func (m *MockStatusManager) RemoveConditionsWithPrefix(prefix string, exclude []string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RemoveConditionsWithPrefix", prefix, exclude)
}

// RemoveConditionsWithPrefix indicates an expected call of RemoveConditionsWithPrefix.
func (mr *MockStatusManagerMockRecorder) RemoveConditionsWithPrefix(prefix, exclude any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveConditionsWithPrefix", reflect.TypeOf((*MockStatusManager)(nil).RemoveConditionsWithPrefix), prefix, exclude)
}

// SetAuthConfigCondition mocks base method.
func (m *MockStatusManager) SetAuthConfigCondition(conditionType, reason, message string, status v1.ConditionStatus) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetAuthConfigCondition", conditionType, reason, message, status)
}

// SetAuthConfigCondition indicates an expected call of SetAuthConfigCondition.
func (mr *MockStatusManagerMockRecorder) SetAuthConfigCondition(conditionType, reason, message, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAuthConfigCondition", reflect.TypeOf((*MockStatusManager)(nil).SetAuthConfigCondition), conditionType, reason, message, status)
}

// SetAuthConfiguredCondition mocks base method.
func (m *MockStatusManager) SetAuthConfiguredCondition(reason, message string, status v1.ConditionStatus) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetAuthConfiguredCondition", reason, message, status)
}

// SetAuthConfiguredCondition indicates an expected call of SetAuthConfiguredCondition.
func (mr *MockStatusManagerMockRecorder) SetAuthConfiguredCondition(reason, message, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAuthConfiguredCondition", reflect.TypeOf((*MockStatusManager)(nil).SetAuthConfiguredCondition), reason, message, status)
}

// SetAuthServerConfigValidatedCondition mocks base method.
func (m *MockStatusManager) SetAuthServerConfigValidatedCondition(reason, message string, status v1.ConditionStatus) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetAuthServerConfigValidatedCondition", reason, message, status)
}

// SetAuthServerConfigValidatedCondition indicates an expected call of SetAuthServerConfigValidatedCondition.
func (mr *MockStatusManagerMockRecorder) SetAuthServerConfigValidatedCondition(reason, message, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAuthServerConfigValidatedCondition", reflect.TypeOf((*MockStatusManager)(nil).SetAuthServerConfigValidatedCondition), reason, message, status)
}

// SetAuthzConfigHash mocks base method.
func (m *MockStatusManager) SetAuthzConfigHash(hash string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetAuthzConfigHash", hash)
}

// SetAuthzConfigHash indicates an expected call of SetAuthzConfigHash.
func (mr *MockStatusManagerMockRecorder) SetAuthzConfigHash(hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAuthzConfigHash", reflect.TypeOf((*MockStatusManager)(nil).SetAuthzConfigHash), hash)
}

// SetCompositeToolRefsValidatedCondition mocks base method.
func (m *MockStatusManager) SetCompositeToolRefsValidatedCondition(reason, message string, status v1.ConditionStatus) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetCompositeToolRefsValidatedCondition", reason, message, status)
}

// SetCompositeToolRefsValidatedCondition indicates an expected call of SetCompositeToolRefsValidatedCondition.
func (mr *MockStatusManagerMockRecorder) SetCompositeToolRefsValidatedCondition(reason, message, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCompositeToolRefsValidatedCondition", reflect.TypeOf((*MockStatusManager)(nil).SetCompositeToolRefsValidatedCondition), reason, message, status)
}

// SetCondition mocks base method.
func (m *MockStatusManager) SetCondition(conditionType, reason, message string, status v1.ConditionStatus) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetCondition", conditionType, reason, message, status)
}

// SetCondition indicates an expected call of SetCondition.
func (mr *MockStatusManagerMockRecorder) SetCondition(conditionType, reason, message, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCondition", reflect.TypeOf((*MockStatusManager)(nil).SetCondition), conditionType, reason, message, status)
}

// SetDiscoveredBackends mocks base method.
func (m *MockStatusManager) SetDiscoveredBackends(backends []v1beta1.DiscoveredBackend) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetDiscoveredBackends", backends)
}

// SetDiscoveredBackends indicates an expected call of SetDiscoveredBackends.
func (mr *MockStatusManagerMockRecorder) SetDiscoveredBackends(backends any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDiscoveredBackends", reflect.TypeOf((*MockStatusManager)(nil).SetDiscoveredBackends), backends)
}

// SetEmbeddingServerReadyCondition mocks base method.
func (m *MockStatusManager) SetEmbeddingServerReadyCondition(reason, message string, status v1.ConditionStatus) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetEmbeddingServerReadyCondition", reason, message, status)
}

// SetEmbeddingServerReadyCondition indicates an expected call of SetEmbeddingServerReadyCondition.
func (mr *MockStatusManagerMockRecorder) SetEmbeddingServerReadyCondition(reason, message, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetEmbeddingServerReadyCondition", reflect.TypeOf((*MockStatusManager)(nil).SetEmbeddingServerReadyCondition), reason, message, status)
}

// SetGroupRefValidatedCondition mocks base method.
func (m *MockStatusManager) SetGroupRefValidatedCondition(reason, message string, status v1.ConditionStatus) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetGroupRefValidatedCondition", reason, message, status)
}

// SetGroupRefValidatedCondition indicates an expected call of SetGroupRefValidatedCondition.
func (mr *MockStatusManagerMockRecorder) SetGroupRefValidatedCondition(reason, message, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetGroupRefValidatedCondition", reflect.TypeOf((*MockStatusManager)(nil).SetGroupRefValidatedCondition), reason, message, status)
}

// SetMessage mocks base method.
func (m *MockStatusManager) SetMessage(message string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetMessage", message)
}

// SetMessage indicates an expected call of SetMessage.
func (mr *MockStatusManagerMockRecorder) SetMessage(message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMessage", reflect.TypeOf((*MockStatusManager)(nil).SetMessage), message)
}

// SetOIDCConfigHash mocks base method.
func (m *MockStatusManager) SetOIDCConfigHash(hash string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetOIDCConfigHash", hash)
}

// SetOIDCConfigHash indicates an expected call of SetOIDCConfigHash.
func (mr *MockStatusManagerMockRecorder) SetOIDCConfigHash(hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetOIDCConfigHash", reflect.TypeOf((*MockStatusManager)(nil).SetOIDCConfigHash), hash)
}

// SetObservedGeneration mocks base method.
func (m *MockStatusManager) SetObservedGeneration(generation int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetObservedGeneration", generation)
}

// SetObservedGeneration indicates an expected call of SetObservedGeneration.
func (mr *MockStatusManagerMockRecorder) SetObservedGeneration(generation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetObservedGeneration", reflect.TypeOf((*MockStatusManager)(nil).SetObservedGeneration), generation)
}

// SetPhase mocks base method.
func (m *MockStatusManager) SetPhase(phase v1beta1.VirtualMCPServerPhase) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetPhase", phase)
}

// SetPhase indicates an expected call of SetPhase.
func (mr *MockStatusManagerMockRecorder) SetPhase(phase any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPhase", reflect.TypeOf((*MockStatusManager)(nil).SetPhase), phase)
}

// SetReadyCondition mocks base method.
func (m *MockStatusManager) SetReadyCondition(reason, message string, status v1.ConditionStatus) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetReadyCondition", reason, message, status)
}

// SetReadyCondition indicates an expected call of SetReadyCondition.
func (mr *MockStatusManagerMockRecorder) SetReadyCondition(reason, message, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetReadyCondition", reflect.TypeOf((*MockStatusManager)(nil).SetReadyCondition), reason, message, status)
}

// SetTelemetryConfigHash mocks base method.
func (m *MockStatusManager) SetTelemetryConfigHash(hash string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetTelemetryConfigHash", hash)
}

// SetTelemetryConfigHash indicates an expected call of SetTelemetryConfigHash.
func (mr *MockStatusManagerMockRecorder) SetTelemetryConfigHash(hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTelemetryConfigHash", reflect.TypeOf((*MockStatusManager)(nil).SetTelemetryConfigHash), hash)
}

// SetTelemetryConfigRefValidatedCondition mocks base method.
func (m *MockStatusManager) SetTelemetryConfigRefValidatedCondition(reason, message string, status v1.ConditionStatus) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetTelemetryConfigRefValidatedCondition", reason, message, status)
}

// SetTelemetryConfigRefValidatedCondition indicates an expected call of SetTelemetryConfigRefValidatedCondition.
func (mr *MockStatusManagerMockRecorder) SetTelemetryConfigRefValidatedCondition(reason, message, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTelemetryConfigRefValidatedCondition", reflect.TypeOf((*MockStatusManager)(nil).SetTelemetryConfigRefValidatedCondition), reason, message, status)
}

// SetURL mocks base method.
func (m *MockStatusManager) SetURL(url string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetURL", url)
}

// SetURL indicates an expected call of SetURL.
func (mr *MockStatusManagerMockRecorder) SetURL(url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetURL", reflect.TypeOf((*MockStatusManager)(nil).SetURL), url)
}

// UpdateStatus mocks base method.
func (m *MockStatusManager) UpdateStatus(ctx context.Context, vmcpStatus *v1beta1.VirtualMCPServerStatus) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, vmcpStatus)
	ret0, _ := ret[0].(bool)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockStatusManagerMockRecorder) UpdateStatus(ctx, vmcpStatus any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockStatusManager)(nil).UpdateStatus), ctx, vmcpStatus)
}
