import { z } from 'zod';

/**
 * Operations supported by the space tool
 * Standard mode: find, view_parameters, invoke
 * Dynamic mode (DYNAMIC_SPACE_DATA): discover, view_parameters, invoke
 */

export const VIEW_PARAMETERS = 'view_parameters';
export const OPERATION_NAMES = ['find', VIEW_PARAMETERS, 'invoke'] as const;
export const DYNAMIC_OPERATION_NAMES = ['discover', VIEW_PARAMETERS, 'invoke'] as const;
export type OperationName = (typeof OPERATION_NAMES)[number];
export type DynamicOperationName = (typeof DYNAMIC_OPERATION_NAMES)[number];

/**
 * File input help message constant
 */
export const FILE_INPUT_HELP_MESSAGE =
	'Provide a publicly accessible URL (http:// or https://) for the file input. ' +
	"Previously generated URL's are usable. ";

/**
 * File handling instructions for user-facing documentation
 */
export const FILE_HANDLING_TEXT = `For parameters that accept files (FileData, Images, file URL types):
- Provide a publicly accessible URL (http:// or https://)
- Example: \`{"image": "https://example.com/photo.jpg"}\`
- URL's generated by one Space can be used as inputs to another Space.`;

/**
 * Check if dynamic space mode is enabled
 */
export function isDynamicSpaceMode(): boolean {
	return !!process.env.DYNAMIC_SPACE_DATA;
}

/**
 * Get the appropriate operation names based on mode
 */
export function getOperationNames(): readonly string[] {
	return isDynamicSpaceMode() ? DYNAMIC_OPERATION_NAMES : OPERATION_NAMES;
}

/**
 * Zod schema for operation arguments (standard mode)
 */
export const spaceArgsSchema = z.object({
	operation: z.enum(OPERATION_NAMES).optional().describe('Operation to execute.'),
	space_name: z
		.string()
		.optional()
		.describe(`Space ID (format: "username/space-name"). Required for operation = ${VIEW_PARAMETERS} or invoke.`),
	parameters: z.string().optional().describe('Required for invoke operation: JSON object string of parameters'),
	search_query: z
		.string()
		.optional()
		.describe(
			'For find operation: Search query or task category (e.g. "Image Generation", "OCR", "FLUX image generation") to find MCP-enabled Spaces. Call with blank query to see task hints.'
		),
	limit: z.number().optional().describe('For find operation: Maximum number of results to return (default: 10)'),
});

/**
 * Zod schema for operation arguments (dynamic mode with DYNAMIC_SPACE_DATA)
 */
export const dynamicSpaceArgsSchema = z.object({
	operation: z.enum(DYNAMIC_OPERATION_NAMES).optional().describe('Operation to perform.'),
	space_name: z
		.string()
		.optional()
		.describe(`Space ID (format: "username/space-name"). Required for "${VIEW_PARAMETERS}" and "invoke" operations.`),
	parameters: z.string().optional().describe('JSON object string of parameters. Only used for "invoke" operation.'),
});

/**
 * Get the appropriate schema based on mode
 */
export function getSpaceArgsSchema(): z.ZodObject<z.ZodRawShape> {
	return isDynamicSpaceMode() ? dynamicSpaceArgsSchema : spaceArgsSchema;
}

export type SpaceArgs = z.infer<typeof spaceArgsSchema>;

/**
 * Parameter information extracted from schema
 */
export interface ParameterInfo {
	name: string;
	type: string;
	description?: string;
	required: boolean;
	default?: unknown;
	enum?: unknown[];
	isFileData?: boolean;
	complexType?: string; // Reason why the type is complex
}

/**
 * Result of schema complexity analysis
 */
export interface SchemaComplexityResult {
	isSimple: boolean;
	reason?: string; // Reason if not simple
	parameters: ParameterInfo[];
	toolName: string;
	toolDescription?: string;
}

/**
 * Result of parameter processing
 */
export interface ProcessParametersResult {
	valid: boolean;
	parameters?: Record<string, unknown>;
	error?: string;
	warnings?: string[];
}

/**
 * JSON Schema property definition
 */
export interface JsonSchemaProperty {
	type?: string;
	title?: string;
	description?: string;
	default?: unknown;
	enum?: unknown[];
	format?: string;
	properties?: Record<string, JsonSchemaProperty>;
	items?: JsonSchemaProperty;
	required?: string[];
	[key: string]: unknown;
}

/**
 * JSON Schema definition
 */
export interface JsonSchema {
	type?: string;
	properties?: Record<string, JsonSchemaProperty>;
	required?: string[];
	description?: string;
	[key: string]: unknown;
}

/**
 * Check if a property is a FileData type
 */
export function isFileDataProperty(prop: JsonSchemaProperty): boolean {
	return (
		prop.title === 'ImageData' ||
		prop.title === 'FileData' ||
		(prop.format?.includes('http') && prop.format?.includes('file')) ||
		false
	);
}

/**
 * Check if a schema contains file data
 */
export function hasFileData(schema: JsonSchema): boolean {
	if (!schema.properties) return false;

	return Object.values(schema.properties).some((prop) => isFileDataProperty(prop));
}

/**
 * Extended result type for invoke operation that includes raw MCP result
 * This allows the space tool to return structured content blocks instead of formatted text
 */
export interface InvokeResult {
	result: {
		content: unknown[];
		isError?: boolean;
		[key: string]: unknown;
	};
	warnings: string[];
	totalResults: number;
	resultsShared: number;
	isError?: boolean;
}
