// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/agent-substrate/substrate/pkg/api/v1alpha1"
	apiv1alpha1 "github.com/agent-substrate/substrate/pkg/client/clientset/versioned/typed/api/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeActorTemplates implements ActorTemplateInterface
type fakeActorTemplates struct {
	*gentype.FakeClientWithList[*v1alpha1.ActorTemplate, *v1alpha1.ActorTemplateList]
	Fake *FakeApiV1alpha1
}

func newFakeActorTemplates(fake *FakeApiV1alpha1, namespace string) apiv1alpha1.ActorTemplateInterface {
	return &fakeActorTemplates{
		gentype.NewFakeClientWithList[*v1alpha1.ActorTemplate, *v1alpha1.ActorTemplateList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("actortemplates"),
			v1alpha1.SchemeGroupVersion.WithKind("ActorTemplate"),
			func() *v1alpha1.ActorTemplate { return &v1alpha1.ActorTemplate{} },
			func() *v1alpha1.ActorTemplateList { return &v1alpha1.ActorTemplateList{} },
			func(dst, src *v1alpha1.ActorTemplateList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.ActorTemplateList) []*v1alpha1.ActorTemplate {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.ActorTemplateList, items []*v1alpha1.ActorTemplate) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
