system:
  parallel_attempts: 32
  lite: false
run:
  generations: 5
  spec:
    include:
      - probes.ansiescape.AnsiEscaped
      - probes.ansiescape.AnsiRaw
      - probes.apikey.CompleteKey
      - probes.apikey.GetKey
      - probes.atkgen.Tox
      - probes.continuation.ContinueSlursReclaimedSlurs
      - probes.dan.Ablation_Dan_11_0
      - probes.dan.AutoDANCached
      - probes.dan.DanInTheWild
      - probes.divergence.Repeat
      - probes.divergence.RepeatedToken
      - probes.dra.DRA
      - probes.encoding.InjectAscii85
      - probes.encoding.InjectAtbash
      - probes.encoding.InjectBase16
      - probes.encoding.InjectBase2048
      - probes.encoding.InjectBase32
      - probes.encoding.InjectBase64
      - probes.encoding.InjectBraille
      - probes.encoding.InjectEcoji
      - probes.encoding.InjectHex
      - probes.encoding.InjectMorse
      - probes.encoding.InjectNato
      - probes.encoding.InjectROT13
      - probes.encoding.InjectUU
      - probes.encoding.InjectUnicodeTagChars
      - probes.encoding.InjectZalgo
      - probes.exploitation.JinjaTemplatePythonInjection
      - probes.exploitation.SQLInjectionEcho
      - probes.goodside.Tag
      - probes.goodside.ThreatenJSON
      - probes.goodside.WhoIsRiley
      - probes.grandma.Slurs
      - probes.grandma.Substances
      - probes.grandma.Win10
      - probes.grandma.Win11
      - probes.latentinjection.LatentInjectionFactSnippetEiffel
      - probes.latentinjection.LatentInjectionFactSnippetLegal
      - probes.latentinjection.LatentInjectionReport
      - probes.latentinjection.LatentInjectionResume
      - probes.latentinjection.LatentInjectionTranslationEnFr
      - probes.latentinjection.LatentInjectionTranslationEnZh
      - probes.latentinjection.LatentJailbreak
      - probes.latentinjection.LatentWhois
      - probes.latentinjection.LatentWhoisSnippet
      - probes.leakreplay.GuardianCloze
      - probes.leakreplay.GuardianComplete
      - probes.leakreplay.LiteratureCloze
      - probes.leakreplay.LiteratureComplete
      - probes.leakreplay.NYTCloze
      - probes.leakreplay.NYTComplete
      - probes.leakreplay.PotterCloze
      - probes.leakreplay.PotterComplete
      - probes.lmrc.Bullying
      - probes.lmrc.Deadnaming
      - probes.lmrc.QuackMedicine
      - probes.lmrc.SexualContent
      - probes.lmrc.Sexualisation
      - probes.lmrc.SlurUsage
      - probes.malwaregen.Evasion
      - probes.malwaregen.Payload
      - probes.malwaregen.SubFunctions
      - probes.malwaregen.TopLevel
      - probes.misleading.FalseAssertion
      - probes.packagehallucination.Dart
      - probes.packagehallucination.JavaScript
      - probes.packagehallucination.Perl
      - probes.packagehallucination.Python
      - probes.packagehallucination.RakuLand
      - probes.packagehallucination.Ruby
      - probes.packagehallucination.Rust
      - probes.phrasing.FutureTense
      - probes.phrasing.PastTense
      - probes.promptinject.HijackHateHumans
      - probes.promptinject.HijackKillHumans
      - probes.promptinject.HijackLongPrompt
      - probes.realtoxicityprompts.RTPBlank
      - probes.snowball.GraphConnectivity
      - probes.suffix.GCGCached
      - probes.tap.TAPCached
      - probes.topic.WordnetControversial
      - probes.web_injection.ColabAIDataLeakage
      - probes.web_injection.MarkdownImageExfil
      - probes.web_injection.MarkdownURIImageExfilExtended
      - probes.web_injection.MarkdownURINonImageExfilExtended
      - probes.web_injection.MarkdownXSS
      - probes.web_injection.PlaygroundMarkdownExfil
      - probes.web_injection.StringAssemblyDataExfil
      - probes.web_injection.TaskXSS
    exclude: []
plugins:
  extended_detectors: true
  probes:
    encoding:
      payloads:
      - default
      - xss
      - slur_terms
  detectors:
    misleading:
      MustContradictNLI:
        hf_args:
          device: cuda
      MustRefuteClaimModel:
        hf_args:
          device: cuda
