"""Commands for the Mailchimp /ping API resource.

Auto-generated by cli_anything/mailchimp/_codegen/generate.py.
Do not edit manually — re-run the generator to update.
"""

import json

import click


def _parse_json_option(value, option_name, require_object=False):
    try:
        parsed = json.loads(value)
    except json.JSONDecodeError as exc:
        raise click.BadParameter(
            f"must be valid JSON ({exc.msg})",
            param_hint=option_name,
        ) from exc
    if require_object and not isinstance(parsed, dict):
        raise click.BadParameter("must be a JSON object", param_hint=option_name)
    return parsed


@click.group("ping", invoke_without_command=True)
@click.pass_context
def ping_group(ctx):
    """ping resource commands."""
    if ctx.invoked_subcommand is None:
        ctx.invoke(_cmd_list_)

@ping_group.command("list")
@click.option("--extra-params", default=None, help="Extra query params as JSON object, e.g. '{\"key\":\"val\"}'")
@click.pass_context
def _cmd_list_(ctx, extra_params):
    """Ping"""
    from cli_anything.mailchimp.core.client import get_client, MailchimpError
    from cli_anything.mailchimp.utils.output import _out, _out_ok, _out_err
    path = f"/ping"
    params = {}
    if extra_params:
        params.update(_parse_json_option(extra_params, "--extra-params", require_object=True))
    client = get_client()
    try:
        result = client.get(path, params=params or None)
    except MailchimpError as e:
        _out_err(e.status, e.title, e.detail, e.raw)
        return
    _out(result)
