export const symbols = {
  bar: '│',
  barEnd: '└',
  radioActive: '●',
  radioInactive: '○',
  checkboxActive: '◼',
  checkboxInactive: '◻',
  diamond: '◆',
  arrow: '›',
  arrowRight: '→',
  arrowUp: '↑',
  arrowDown: '↓',
  dot: '·',
  bullet: '▸',
  check: '✓',
  cross: '✗',
  star: '★',
  sparkle: '✦',
  installed: '●',
  warning: '⚠',
  info: 'ℹ',
} as const
