name: Publish Any Commit

permissions:
    contents: read

on:
    pull_request:
    push:
        branches:
            - '**'
        tags:
            - '!**'

jobs:
    pkg-publish:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v7

            - name: Install pnpm
              uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0
              with:
                  run_install: false

            - name: Setup Node.js
              uses: actions/setup-node@v6
              with:
                  node-version: 24
                  cache: pnpm
                  cache-dependency-path: pnpm-lock.yaml
                  registry-url: 'https://registry.npmjs.org'

            - name: Install dependencies
              run: pnpm install

            - name: Build packages
              run: pnpm run build:all

            - name: Publish preview packages
              run:
                  pnpm dlx pkg-pr-new publish --packageManager=npm --pnpm './packages/core' './packages/server' './packages/server-legacy' './packages/client'
                  './packages/codemod' './packages/middleware/express' './packages/middleware/fastify' './packages/middleware/hono' './packages/middleware/node'
