#!/usr/bin/env python3
"""Single-source-of-truth for rule count.

Reads the current signed bundle (or rebuilds it if missing) and rewrites
every place in the repo that advertises a specific rule count:

    - README.md            shields.io badge
    - action.yml           description:
    - agent_audit_kit/__init__.py  RULE_COUNT constant

Idempotent. Exits 0 when nothing needs changing, 0 when files were updated.
Exits 1 if the bundle can't be read or the regex anchor isn't found.

Runs as:
    * pre-commit hook (blocks human drift)
    * .github/workflows/sync-rule-count.yml (auto-commits after rules.json changes)

Usage:
    python scripts/sync_rule_count.py                # uses ./rules.json
    python scripts/sync_rule_count.py --bundle PATH  # explicit
    python scripts/sync_rule_count.py --regenerate   # (re)build bundle first
    python scripts/sync_rule_count.py --check        # fail if drift detected
"""

from __future__ import annotations

import argparse
import json
import pathlib
import re
import sys


REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
DEFAULT_BUNDLE = REPO_ROOT / "rules.json"

_README_BADGE_RE = re.compile(
    r"(img\.shields\.io/badge/rules-)\d+(-[a-z]+\.svg)"
)
# HTML-comment anchors are the canonical place the badge/phrase/total
# writes hit. Anything NOT inside an anchor is manual prose that we will
# not silently rewrite (the A2A "12 rules" cell on README line 320
# collided with the old phrase regex — we are not doing that again).
_README_ANCHOR_RE = re.compile(
    r"(<!--\s*rule-count:total\s*-->)(.*?)(<!--\s*/rule-count\s*-->)",
    re.DOTALL,
)
# Per-category anchors added v0.3.23 to fix the "What It Scans" table
# drifting independently of the total badge (the table sum was 81 rules
# under-counted before the anchors landed). Each anchor matches the
# Category enum name verbatim — e.g. `<!-- category-count:SUPPLY_CHAIN -->`.
# NOTE: must include `0-9` — `A2A_PROTOCOL` would otherwise be silently
# skipped, which is exactly the bug the v0.3.23 regression test caught.
_README_CATEGORY_ANCHOR_RE = re.compile(
    r"(<!--\s*category-count:([A-Z0-9_]+)\s*-->)(.*?)(<!--\s*/category-count\s*-->)",
    re.DOTALL,
)
_INIT_CONSTANT_RE = re.compile(
    r"^(RULE_COUNT\s*[:=]\s*)\d+(.*)$",
    re.MULTILINE,
)

# Docs that carry a `<!-- rule-count:total -->N<!-- /rule-count -->` anchor —
# same mechanism as the README total-anchor, so the number can never drift
# from len(RULES). Added v0.3.49: docs/rules.md and the comparison pages used
# to hard-code 221 while the registry was at 246.
_TOTAL_ANCHOR_DOCS = (
    "docs/comparison.md",
    "docs/comparison-gitlab-agentic-sast.md",
    "docs/STATE-OF-MCP-SECURITY-2026.md",
)

# docs/rules.md ships a per-category Summary table. It is regenerated wholesale
# from the registry between these markers so a new category (e.g. the 12th,
# MCP_SERVER_CARD) can never be silently omitted the way it was pre-v0.3.49.
_RULES_MD = "docs/rules.md"
_RULES_SUMMARY_BEGIN = "<!-- BEGIN rules-summary (generated by scripts/sync_rule_count.py) -->"
_RULES_SUMMARY_END = "<!-- END rules-summary -->"
_RULES_SUMMARY_RE = re.compile(
    re.escape(_RULES_SUMMARY_BEGIN) + r".*?" + re.escape(_RULES_SUMMARY_END),
    re.DOTALL,
)

# Category enum name → human display name. Mirrors the README "What It Scans"
# table verbatim (the one canonical place these strings live). A live category
# missing from this map fails the sync loudly rather than dropping a row.
_CATEGORY_DISPLAY = {
    "MCP_CONFIG": "MCP Configuration",
    "SUPPLY_CHAIN": "Supply Chain",
    "TOOL_POISONING": "Tool Poisoning",
    "SECRET_EXPOSURE": "Secret Exposure",
    "AGENT_CONFIG": "Agent Config",
    "A2A_PROTOCOL": "A2A Protocol",
    "TAINT_ANALYSIS": "Taint Analysis",
    "HOOK_INJECTION": "Hook Injection",
    "LEGAL_COMPLIANCE": "Legal Compliance",
    "TRUST_BOUNDARY": "Trust Boundaries",
    "TRANSPORT_SECURITY": "Transport Security",
    "MCP_SERVER_CARD": "MCP Server Card",
}


def _category_counts() -> dict[str, int]:
    """Group the live rule registry by Category.name → count."""
    from collections import Counter
    from agent_audit_kit.rules.builtin import RULES
    return {cat.name: n for cat, n in Counter(r.category for r in RULES.values()).items()}


def _load_rule_count(bundle: pathlib.Path, regenerate: bool) -> int:
    """Read rule count from the bundle (or regenerate then read)."""
    if regenerate or not bundle.is_file():
        # Prefer a clean rebuild via the public API — keeps the bundle in
        # lockstep with the code even if the on-disk rules.json is stale.
        from agent_audit_kit.bundle import write_bundle
        write_bundle(bundle)
    data = json.loads(bundle.read_text(encoding="utf-8"))
    rules = data.get("rules")
    if not isinstance(rules, list):
        raise SystemExit(f"Invalid rule bundle at {bundle}: missing 'rules' list")
    return len(rules)


def _update_readme(count: int, *, check: bool) -> bool:
    """Rewrite the badge URL + every `<!-- rule-count:total -->...<!-- /rule-count -->`
    anchor + every `<!-- category-count:NAME -->...<!-- /category-count -->`
    anchor. Also keep the shields alt-text in lockstep with the badge."""
    readme = REPO_ROOT / "README.md"
    text = readme.read_text(encoding="utf-8")
    original = text
    text = _README_BADGE_RE.sub(rf"\g<1>{count}\g<2>", text)
    text = re.sub(r"alt=\"Rules:\s*\d+\"", f'alt="Rules: {count}"', text)

    def _sub_total_anchor(match: re.Match) -> str:
        return f"{match.group(1)}{count}{match.group(3)}"

    text = _README_ANCHOR_RE.sub(_sub_total_anchor, text)

    # Per-category anchors — fail loudly if the README references a
    # Category name the registry doesn't have. That catches typos and
    # stops the table from claiming a category that no longer exists.
    cat_counts = _category_counts()

    def _sub_category_anchor(match: re.Match) -> str:
        cat_name = match.group(2)
        if cat_name not in cat_counts:
            raise SystemExit(
                f"sync_rule_count: README references unknown category "
                f"`{cat_name}` — valid Category enum names: "
                f"{sorted(cat_counts.keys())}"
            )
        return f"{match.group(1)}{cat_counts[cat_name]}{match.group(4)}"

    text = _README_CATEGORY_ANCHOR_RE.sub(_sub_category_anchor, text)
    if text == original:
        return False
    if check:
        return True
    readme.write_text(text, encoding="utf-8")
    return True


def _update_action_yml(count: int, *, check: bool) -> bool:
    action = REPO_ROOT / "action.yml"
    text = action.read_text(encoding="utf-8")
    original = text
    new_desc = (
        f"'AgentAuditKit — MCP Security Scan ({count} rules, "
        "OWASP Agentic Top 10 + MCP Top 10)'"
    )
    # Only rewrite the top-level `description:` line (the first one we see).
    pattern = re.compile(r"^description:\s*.+$", re.MULTILINE)
    match = pattern.search(text)
    if not match:
        raise SystemExit("Could not find a top-level 'description:' line in action.yml")
    text = pattern.sub(f"description: {new_desc}", text, count=1)
    if text == original:
        return False
    if check:
        return True
    action.write_text(text, encoding="utf-8")
    return True


def _update_init_py(count: int, *, check: bool) -> bool:
    init = REPO_ROOT / "agent_audit_kit" / "__init__.py"
    text = init.read_text(encoding="utf-8")
    original = text
    if _INIT_CONSTANT_RE.search(text):
        text = _INIT_CONSTANT_RE.sub(rf"\g<1>{count}\g<2>", text)
    else:
        text = text.rstrip() + f"\nRULE_COUNT = {count}\n"
    if text == original:
        return False
    if check:
        return True
    init.write_text(text, encoding="utf-8")
    return True


def _update_total_anchor_doc(rel: str, count: int, *, check: bool) -> bool:
    """Rewrite every `<!-- rule-count:total -->N<!-- /rule-count -->` anchor in
    a doc under docs/. Reuses the README anchor regex — anything outside an
    anchor is manual prose we never touch."""
    path = REPO_ROOT / rel
    if not path.is_file():
        return False
    text = path.read_text(encoding="utf-8")

    def _sub(match: re.Match) -> str:
        return f"{match.group(1)}{count}{match.group(3)}"

    new = _README_ANCHOR_RE.sub(_sub, text)
    if new == text:
        return False
    if check:
        return True
    path.write_text(new, encoding="utf-8")
    return True


def _render_rules_summary(count: int) -> str:
    """Build the docs/rules.md Summary table from the live registry, sorted by
    count desc then category name. Deterministic — byte-identical every run."""
    counts = _category_counts()
    rows = sorted(counts.items(), key=lambda kv: (-kv[1], kv[0]))
    lines = [
        _RULES_SUMMARY_BEGIN,
        "",
        "| Category | Rules |",
        "|----------|-------|",
    ]
    for name, n in rows:
        if name not in _CATEGORY_DISPLAY:
            raise SystemExit(
                f"sync_rule_count: no display name for category `{name}` — "
                f"add it to _CATEGORY_DISPLAY (valid: {sorted(_CATEGORY_DISPLAY)})"
            )
        lines.append(f"| {_CATEGORY_DISPLAY[name]} | {n} |")
    lines.append(f"| **Total** | **{count}** |")
    lines.extend(["", _RULES_SUMMARY_END])
    return "\n".join(lines)


def _update_docs_rules_md(count: int, *, check: bool) -> bool:
    """Regenerate the docs/rules.md Summary table between the BEGIN/END markers."""
    path = REPO_ROOT / _RULES_MD
    if not path.is_file():
        return False
    text = path.read_text(encoding="utf-8")
    if not _RULES_SUMMARY_RE.search(text):
        raise SystemExit(
            f"sync_rule_count: {_RULES_MD} is missing the rules-summary markers "
            f"({_RULES_SUMMARY_BEGIN!r} ... {_RULES_SUMMARY_END!r})"
        )
    block = _render_rules_summary(count)
    new = _RULES_SUMMARY_RE.sub(lambda _m: block, text)
    if new == text:
        return False
    if check:
        return True
    path.write_text(new, encoding="utf-8")
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--bundle", default=str(DEFAULT_BUNDLE), help="Path to rules.json")
    parser.add_argument(
        "--regenerate", action="store_true",
        help="(Re)build the bundle from agent_audit_kit.rules.builtin before reading it.",
    )
    parser.add_argument(
        "--check", action="store_true",
        help="Exit 1 if any file would change (for CI / pre-commit).",
    )
    args = parser.parse_args()
    bundle = pathlib.Path(args.bundle)

    count = _load_rule_count(bundle, args.regenerate)
    changed_readme = _update_readme(count, check=args.check)
    changed_action = _update_action_yml(count, check=args.check)
    changed_init = _update_init_py(count, check=args.check)
    changed_rules_md = _update_docs_rules_md(count, check=args.check)
    changed_docs = [
        _update_total_anchor_doc(rel, count, check=args.check)
        for rel in _TOTAL_ANCHOR_DOCS
    ]

    changed = any(
        (changed_readme, changed_action, changed_init, changed_rules_md, *changed_docs)
    )
    if args.check and changed:
        sys.stderr.write(
            f"sync_rule_count: drift detected (rule count = {count}). "
            "Run `python scripts/sync_rule_count.py` and commit the result.\n"
        )
        return 1
    if changed:
        sys.stdout.write(
            f"sync_rule_count: wrote {count} rules into README / action.yml / "
            "__init__.py / docs/rules.md / comparison pages\n"
        )
    else:
        sys.stdout.write(f"sync_rule_count: clean ({count} rules everywhere).\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
