// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        v4.25.3
// source: fieldmasktest.proto

package fieldmasktestpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestEnum int32

const (
	TestEnum_TEST_ENUM_UNSPECIFIED TestEnum = 0
	TestEnum_TEST_ENUM_FIRST       TestEnum = 1
	TestEnum_TEST_ENUM_SECOND      TestEnum = 2
)

// Enum value maps for TestEnum.
var (
	TestEnum_name = map[int32]string{
		0: "TEST_ENUM_UNSPECIFIED",
		1: "TEST_ENUM_FIRST",
		2: "TEST_ENUM_SECOND",
	}
	TestEnum_value = map[string]int32{
		"TEST_ENUM_UNSPECIFIED": 0,
		"TEST_ENUM_FIRST":       1,
		"TEST_ENUM_SECOND":      2,
	}
)

func (x TestEnum) Enum() *TestEnum {
	p := new(TestEnum)
	*p = x
	return p
}

func (x TestEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TestEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_fieldmasktest_proto_enumTypes[0].Descriptor()
}

func (TestEnum) Type() protoreflect.EnumType {
	return &file_fieldmasktest_proto_enumTypes[0]
}

func (x TestEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TestEnum.Descriptor instead.
func (TestEnum) EnumDescriptor() ([]byte, []int) {
	return file_fieldmasktest_proto_rawDescGZIP(), []int{0}
}

// TestMessage exercises every field kind the fieldmask package needs to
// handle correctly: plain and presence-tracking ("optional") scalars, an
// enum, a nested message reachable three levels deep (to exercise
// multi-level intermediate initialization), repeated scalar and message
// fields, string- and message-valued maps, and a oneof.
type TestMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	OptionalName  *string                `protobuf:"bytes,2,opt,name=optional_name,json=optionalName,proto3,oneof" json:"optional_name,omitempty"`
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	OptionalCount *int32                 `protobuf:"varint,4,opt,name=optional_count,json=optionalCount,proto3,oneof" json:"optional_count,omitempty"`
	Active        bool                   `protobuf:"varint,5,opt,name=active,proto3" json:"active,omitempty"`
	Payload       []byte                 `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	Kind          TestEnum               `protobuf:"varint,7,opt,name=kind,proto3,enum=fieldmasktest.TestEnum" json:"kind,omitempty"`
	Nested        *Nested                `protobuf:"bytes,8,opt,name=nested,proto3" json:"nested,omitempty"`
	Tags          []string               `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty"`
	Items         []*Nested              `protobuf:"bytes,10,rep,name=items,proto3" json:"items,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,11,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	NamedItems    map[string]*Nested     `protobuf:"bytes,12,rep,name=named_items,json=namedItems,proto3" json:"named_items,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Types that are valid to be assigned to Choice:
	//
	//	*TestMessage_ChoiceText
	//	*TestMessage_ChoiceNested
	Choice        isTestMessage_Choice `protobuf_oneof:"choice"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestMessage) Reset() {
	*x = TestMessage{}
	mi := &file_fieldmasktest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestMessage) ProtoMessage() {}

func (x *TestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_fieldmasktest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestMessage.ProtoReflect.Descriptor instead.
func (*TestMessage) Descriptor() ([]byte, []int) {
	return file_fieldmasktest_proto_rawDescGZIP(), []int{0}
}

func (x *TestMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TestMessage) GetOptionalName() string {
	if x != nil && x.OptionalName != nil {
		return *x.OptionalName
	}
	return ""
}

func (x *TestMessage) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *TestMessage) GetOptionalCount() int32 {
	if x != nil && x.OptionalCount != nil {
		return *x.OptionalCount
	}
	return 0
}

func (x *TestMessage) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *TestMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *TestMessage) GetKind() TestEnum {
	if x != nil {
		return x.Kind
	}
	return TestEnum_TEST_ENUM_UNSPECIFIED
}

func (x *TestMessage) GetNested() *Nested {
	if x != nil {
		return x.Nested
	}
	return nil
}

func (x *TestMessage) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *TestMessage) GetItems() []*Nested {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *TestMessage) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *TestMessage) GetNamedItems() map[string]*Nested {
	if x != nil {
		return x.NamedItems
	}
	return nil
}

func (x *TestMessage) GetChoice() isTestMessage_Choice {
	if x != nil {
		return x.Choice
	}
	return nil
}

func (x *TestMessage) GetChoiceText() string {
	if x != nil {
		if x, ok := x.Choice.(*TestMessage_ChoiceText); ok {
			return x.ChoiceText
		}
	}
	return ""
}

func (x *TestMessage) GetChoiceNested() *Nested {
	if x != nil {
		if x, ok := x.Choice.(*TestMessage_ChoiceNested); ok {
			return x.ChoiceNested
		}
	}
	return nil
}

type isTestMessage_Choice interface {
	isTestMessage_Choice()
}

type TestMessage_ChoiceText struct {
	ChoiceText string `protobuf:"bytes,13,opt,name=choice_text,json=choiceText,proto3,oneof"`
}

type TestMessage_ChoiceNested struct {
	ChoiceNested *Nested `protobuf:"bytes,14,opt,name=choice_nested,json=choiceNested,proto3,oneof"`
}

func (*TestMessage_ChoiceText) isTestMessage_Choice() {}

func (*TestMessage_ChoiceNested) isTestMessage_Choice() {}

type Nested struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Inner         *Inner                 `protobuf:"bytes,2,opt,name=inner,proto3" json:"inner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Nested) Reset() {
	*x = Nested{}
	mi := &file_fieldmasktest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Nested) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nested) ProtoMessage() {}

func (x *Nested) ProtoReflect() protoreflect.Message {
	mi := &file_fieldmasktest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nested.ProtoReflect.Descriptor instead.
func (*Nested) Descriptor() ([]byte, []int) {
	return file_fieldmasktest_proto_rawDescGZIP(), []int{1}
}

func (x *Nested) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Nested) GetInner() *Inner {
	if x != nil {
		return x.Inner
	}
	return nil
}

type Inner struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        int32                  `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Inner) Reset() {
	*x = Inner{}
	mi := &file_fieldmasktest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Inner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Inner) ProtoMessage() {}

func (x *Inner) ProtoReflect() protoreflect.Message {
	mi := &file_fieldmasktest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Inner.ProtoReflect.Descriptor instead.
func (*Inner) Descriptor() ([]byte, []int) {
	return file_fieldmasktest_proto_rawDescGZIP(), []int{2}
}

func (x *Inner) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

var File_fieldmasktest_proto protoreflect.FileDescriptor

const file_fieldmasktest_proto_rawDesc = "" +
	"\n" +
	"\x13fieldmasktest.proto\x12\rfieldmasktest\"\x8a\x06\n" +
	"\vTestMessage\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12(\n" +
	"\roptional_name\x18\x02 \x01(\tH\x01R\foptionalName\x88\x01\x01\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\x12*\n" +
	"\x0eoptional_count\x18\x04 \x01(\x05H\x02R\roptionalCount\x88\x01\x01\x12\x16\n" +
	"\x06active\x18\x05 \x01(\bR\x06active\x12\x18\n" +
	"\apayload\x18\x06 \x01(\fR\apayload\x12+\n" +
	"\x04kind\x18\a \x01(\x0e2\x17.fieldmasktest.TestEnumR\x04kind\x12-\n" +
	"\x06nested\x18\b \x01(\v2\x15.fieldmasktest.NestedR\x06nested\x12\x12\n" +
	"\x04tags\x18\t \x03(\tR\x04tags\x12+\n" +
	"\x05items\x18\n" +
	" \x03(\v2\x15.fieldmasktest.NestedR\x05items\x12>\n" +
	"\x06labels\x18\v \x03(\v2&.fieldmasktest.TestMessage.LabelsEntryR\x06labels\x12K\n" +
	"\vnamed_items\x18\f \x03(\v2*.fieldmasktest.TestMessage.NamedItemsEntryR\n" +
	"namedItems\x12!\n" +
	"\vchoice_text\x18\r \x01(\tH\x00R\n" +
	"choiceText\x12<\n" +
	"\rchoice_nested\x18\x0e \x01(\v2\x15.fieldmasktest.NestedH\x00R\fchoiceNested\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aT\n" +
	"\x0fNamedItemsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.fieldmasktest.NestedR\x05value:\x028\x01B\b\n" +
	"\x06choiceB\x10\n" +
	"\x0e_optional_nameB\x11\n" +
	"\x0f_optional_count\"J\n" +
	"\x06Nested\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12*\n" +
	"\x05inner\x18\x02 \x01(\v2\x14.fieldmasktest.InnerR\x05inner\"\x1f\n" +
	"\x05Inner\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x05R\x06number*P\n" +
	"\bTestEnum\x12\x19\n" +
	"\x15TEST_ENUM_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fTEST_ENUM_FIRST\x10\x01\x12\x14\n" +
	"\x10TEST_ENUM_SECOND\x10\x02BIZGgithub.com/agent-substrate/substrate/internal/fieldmask/fieldmasktestpbb\x06proto3"

var (
	file_fieldmasktest_proto_rawDescOnce sync.Once
	file_fieldmasktest_proto_rawDescData []byte
)

func file_fieldmasktest_proto_rawDescGZIP() []byte {
	file_fieldmasktest_proto_rawDescOnce.Do(func() {
		file_fieldmasktest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fieldmasktest_proto_rawDesc), len(file_fieldmasktest_proto_rawDesc)))
	})
	return file_fieldmasktest_proto_rawDescData
}

var file_fieldmasktest_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_fieldmasktest_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_fieldmasktest_proto_goTypes = []any{
	(TestEnum)(0),       // 0: fieldmasktest.TestEnum
	(*TestMessage)(nil), // 1: fieldmasktest.TestMessage
	(*Nested)(nil),      // 2: fieldmasktest.Nested
	(*Inner)(nil),       // 3: fieldmasktest.Inner
	nil,                 // 4: fieldmasktest.TestMessage.LabelsEntry
	nil,                 // 5: fieldmasktest.TestMessage.NamedItemsEntry
}
var file_fieldmasktest_proto_depIdxs = []int32{
	0, // 0: fieldmasktest.TestMessage.kind:type_name -> fieldmasktest.TestEnum
	2, // 1: fieldmasktest.TestMessage.nested:type_name -> fieldmasktest.Nested
	2, // 2: fieldmasktest.TestMessage.items:type_name -> fieldmasktest.Nested
	4, // 3: fieldmasktest.TestMessage.labels:type_name -> fieldmasktest.TestMessage.LabelsEntry
	5, // 4: fieldmasktest.TestMessage.named_items:type_name -> fieldmasktest.TestMessage.NamedItemsEntry
	2, // 5: fieldmasktest.TestMessage.choice_nested:type_name -> fieldmasktest.Nested
	3, // 6: fieldmasktest.Nested.inner:type_name -> fieldmasktest.Inner
	2, // 7: fieldmasktest.TestMessage.NamedItemsEntry.value:type_name -> fieldmasktest.Nested
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_fieldmasktest_proto_init() }
func file_fieldmasktest_proto_init() {
	if File_fieldmasktest_proto != nil {
		return
	}
	file_fieldmasktest_proto_msgTypes[0].OneofWrappers = []any{
		(*TestMessage_ChoiceText)(nil),
		(*TestMessage_ChoiceNested)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fieldmasktest_proto_rawDesc), len(file_fieldmasktest_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fieldmasktest_proto_goTypes,
		DependencyIndexes: file_fieldmasktest_proto_depIdxs,
		EnumInfos:         file_fieldmasktest_proto_enumTypes,
		MessageInfos:      file_fieldmasktest_proto_msgTypes,
	}.Build()
	File_fieldmasktest_proto = out.File
	file_fieldmasktest_proto_goTypes = nil
	file_fieldmasktest_proto_depIdxs = nil
}
