// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/agent-substrate/substrate/pkg/api/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ActorTemplateLister helps list ActorTemplates.
// All objects returned here must be treated as read-only.
type ActorTemplateLister interface {
	// List lists all ActorTemplates in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv1alpha1.ActorTemplate, err error)
	// ActorTemplates returns an object that can list and get ActorTemplates.
	ActorTemplates(namespace string) ActorTemplateNamespaceLister
	ActorTemplateListerExpansion
}

// actorTemplateLister implements the ActorTemplateLister interface.
type actorTemplateLister struct {
	listers.ResourceIndexer[*apiv1alpha1.ActorTemplate]
}

// NewActorTemplateLister returns a new ActorTemplateLister.
func NewActorTemplateLister(indexer cache.Indexer) ActorTemplateLister {
	return &actorTemplateLister{listers.New[*apiv1alpha1.ActorTemplate](indexer, apiv1alpha1.Resource("actortemplate"))}
}

// ActorTemplates returns an object that can list and get ActorTemplates.
func (s *actorTemplateLister) ActorTemplates(namespace string) ActorTemplateNamespaceLister {
	return actorTemplateNamespaceLister{listers.NewNamespaced[*apiv1alpha1.ActorTemplate](s.ResourceIndexer, namespace)}
}

// ActorTemplateNamespaceLister helps list and get ActorTemplates.
// All objects returned here must be treated as read-only.
type ActorTemplateNamespaceLister interface {
	// List lists all ActorTemplates in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv1alpha1.ActorTemplate, err error)
	// Get retrieves the ActorTemplate from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*apiv1alpha1.ActorTemplate, error)
	ActorTemplateNamespaceListerExpansion
}

// actorTemplateNamespaceLister implements the ActorTemplateNamespaceLister
// interface.
type actorTemplateNamespaceLister struct {
	listers.ResourceIndexer[*apiv1alpha1.ActorTemplate]
}
