// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/agent-substrate/substrate/pkg/api/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// SandboxConfigLister helps list SandboxConfigs.
// All objects returned here must be treated as read-only.
type SandboxConfigLister interface {
	// List lists all SandboxConfigs in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv1alpha1.SandboxConfig, err error)
	// Get retrieves the SandboxConfig from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*apiv1alpha1.SandboxConfig, error)
	SandboxConfigListerExpansion
}

// sandboxConfigLister implements the SandboxConfigLister interface.
type sandboxConfigLister struct {
	listers.ResourceIndexer[*apiv1alpha1.SandboxConfig]
}

// NewSandboxConfigLister returns a new SandboxConfigLister.
func NewSandboxConfigLister(indexer cache.Indexer) SandboxConfigLister {
	return &sandboxConfigLister{listers.New[*apiv1alpha1.SandboxConfig](indexer, apiv1alpha1.Resource("sandboxconfig"))}
}
