// <auto-generated/>

#nullable disable

using System;
using System.ClientModel;
using System.ClientModel.Primitives;
using System.Collections.Generic;

namespace AzureRetailPrices
{
    internal partial class RetailPricesGetPricesAsyncCollectionResult : AsyncCollectionResult
    {
        private readonly RetailPrices _client;
        private readonly string _currencyCode;
        private readonly string _filter;
        private readonly string _meterRegion;
        private readonly long? _skip;
        private readonly RequestOptions _options;

        /// <summary> Initializes a new instance of RetailPricesGetPricesAsyncCollectionResult, which is used to iterate over the pages of a collection. </summary>
        /// <param name="client"> The RetailPrices client used to send requests. </param>
        /// <param name="currencyCode">
        /// Currency code for pricing (e.g., "USD", "EUR").
        /// Default is USD. See supported currencies documentation.
        /// </param>
        /// <param name="filter">
        /// OData filter expression to filter results.
        /// Supported filter fields: armRegionName, Location, meterId, meterName,
        /// productid, skuId, productName, skuName, serviceName, serviceId,
        /// serviceFamily, priceType, armSkuName
        /// Examples:
        /// <list type="bullet"><item><description>serviceName eq 'Virtual Machines'</description></item><item><description>priceType eq 'Reservation'</description></item><item><description>serviceFamily eq 'Compute'</description></item><item><description>armRegionName eq 'westeurope' and armSkuName eq 'Standard_D2_v3'</description></item></list>
        /// Note: Filter values are case sensitive in API version 2023-01-01-preview and later.
        /// </param>
        /// <param name="meterRegion">
        /// Meter region filter. Set to 'primary' to retrieve only primary meter prices.
        /// Supported with API version 2021-10-01 and later.
        /// </param>
        /// <param name="skip"> Number of records to skip (for pagination). </param>
        /// <param name="options"> The request options, which can override default behaviors of the client pipeline on a per-call basis. </param>
        public RetailPricesGetPricesAsyncCollectionResult(RetailPrices client, string currencyCode, string filter, string meterRegion, long? skip, RequestOptions options)
        {
            _client = client;
            _currencyCode = currencyCode;
            _filter = filter;
            _meterRegion = meterRegion;
            _skip = skip;
            _options = options;
        }

        /// <summary> Gets the raw pages of the collection. </summary>
        /// <returns> The raw pages of the collection. </returns>
        public override async IAsyncEnumerable<ClientResult> GetRawPagesAsync()
        {
            PipelineMessage message = _client.CreateGetPricesRequest(_currencyCode, _filter, _meterRegion, _skip, _options);
            Uri nextPageUri = null;
            while (true)
            {
                ClientResult result = ClientResult.FromResponse(await _client.Pipeline.ProcessMessageAsync(message, _options).ConfigureAwait(false));
                yield return result;

                nextPageUri = ((RetailPricesResponse)result).NextPageLink;
                if (nextPageUri == null)
                {
                    yield break;
                }
                message = _client.CreateNextGetPricesRequest(nextPageUri, _currencyCode, _filter, _meterRegion, _skip, _options);
            }
        }

        /// <summary> Gets the continuation token from the specified page. </summary>
        /// <param name="page"></param>
        /// <returns> The continuation token for the specified page. </returns>
        public override ContinuationToken GetContinuationToken(ClientResult page)
        {
            Uri nextPage = ((RetailPricesResponse)page).NextPageLink;
            return nextPage != null  
                ? ContinuationToken.FromBytes(BinaryData.FromString(nextPage.AbsoluteUri))  
                : null;
        }
    }
}
