# Server-side connect-go exposure (issue #912 slice 2): a
# `New<Stem>Handler(impl)` wiring call marks the impl type's contract methods
# as EXPOSING the same unscoped `resource::RPC::<Stem>.<Method>` nodes that
# client sinks target, so caller and server join on one resource node.
from __future__ import annotations

from pathlib import Path
from unittest.mock import MagicMock

from codebase_rag import constants as cs
from codebase_rag.capture import resolve_capture
from codebase_rag.graph_updater import GraphUpdater
from codebase_rag.parser_loader import load_parsers

EXPOSES = cs.RelationshipType.EXPOSES.value
_CAPTURE_IO = resolve_capture([cs.CaptureGroup.IO.value])

_CONNECT_GEN = (
    "package userv1connect\n\n"
    "type UserServiceHandler interface {\n"
    "\tGetUser(id string) error\n"
    "\tPutUser(id string) error\n"
    "}\n\n"
    "func NewUserServiceHandler(svc UserServiceHandler) (string, int) {\n"
    '\treturn "", 0\n'
    "}\n"
)


def _run_exposes(tmp_path: Path, files: dict[str, str]) -> set[tuple[str, str]]:
    # Build the graph for `files` and return (source_qn, resource_qn) for
    # EXPOSES edges only.
    parsers, queries = load_parsers()
    for rel, content in files.items():
        p = tmp_path / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(content, encoding="utf-8")
    mock = MagicMock()
    GraphUpdater(
        ingestor=mock,
        repo_path=tmp_path,
        parsers=parsers,
        queries=queries,
        capture=_CAPTURE_IO,
    ).run()
    return {
        (c.args[0][2], c.args[2][2])
        for c in mock.ensure_relationship_batch.call_args_list
        if str(c.args[1]) == EXPOSES
    }


def test_ctor_bound_impl_exposes_contract_methods(tmp_path: Path) -> None:
    # The verified production shape: the impl comes from a cross-package
    # constructor and the generated package is imported under an alias.
    files = {
        "go.mod": "module example.com/app\n\ngo 1.22\n",
        "gen/userv1connect/user.connect.go": _CONNECT_GEN,
        "svc/server.go": (
            "package server\n\n"
            "type Server struct{}\n\n"
            "func New() *Server {\n\treturn &Server{}\n}\n\n"
            "func (s *Server) GetUser(id string) error {\n\treturn nil\n}\n\n"
            "func (s *Server) PutUser(id string) error {\n\treturn nil\n}\n\n"
            "func (s *Server) Extra() {}\n"
        ),
        "main.go": (
            "package main\n\n"
            'import userv1 "example.com/app/gen/userv1connect"\n'
            'import "example.com/app/svc"\n\n'
            "func main() {\n"
            "\tuSrv := server.New()\n"
            "\tpath, handler := userv1.NewUserServiceHandler(uSrv)\n"
            "\t_ = path\n"
            "\t_ = handler\n"
            "}\n"
        ),
    }
    rels = _run_exposes(tmp_path, files)
    project = tmp_path.name
    impl = f"{project}.svc.server.Server"
    assert (f"{impl}.GetUser", "resource::RPC::UserService.GetUser") in rels, rels
    assert (f"{impl}.PutUser", "resource::RPC::UserService.PutUser") in rels, rels
    # An exported method outside the generated contract is not an RPC.
    assert not any(src == f"{impl}.Extra" for src, _r in rels), rels


def test_composite_literal_impl_exposes(tmp_path: Path) -> None:
    # The impl bound from a composite literal in the wiring function itself.
    files = {
        "go.mod": "module example.com/app\n\ngo 1.22\n",
        "gen/userv1connect/user.connect.go": _CONNECT_GEN,
        "main.go": (
            "package main\n\n"
            'import "example.com/app/gen/userv1connect"\n\n'
            "type Impl struct{}\n\n"
            "func (i *Impl) GetUser(id string) error {\n\treturn nil\n}\n\n"
            "func main() {\n"
            "\timpl := &Impl{}\n"
            "\tpath, handler := userv1connect.NewUserServiceHandler(impl)\n"
            "\t_ = path\n"
            "\t_ = handler\n"
            "}\n"
        ),
    }
    rels = _run_exposes(tmp_path, files)
    project = tmp_path.name
    assert (
        f"{project}.main.Impl.GetUser",
        "resource::RPC::UserService.GetUser",
    ) in rels, rels
    # PutUser is in the contract but the impl does not define it: no edge.
    assert not any(res.endswith("PutUser") for _s, res in rels), rels


def test_non_connect_handler_ctor_is_not_rpc(tmp_path: Path) -> None:
    # `New<Stem>Handler` from a package NOT generated by connect-go carries no
    # contract evidence.
    files = {
        "go.mod": "module example.com/app\n\ngo 1.22\n",
        "web/handlers.go": (
            "package web\n\n"
            "type UserServiceHandler interface {\n\tGetUser(id string) error\n}\n\n"
            "func NewUserServiceHandler(svc UserServiceHandler) int {\n\treturn 0\n}\n"
        ),
        "main.go": (
            "package main\n\n"
            'import "example.com/app/web"\n\n'
            "type Impl struct{}\n\n"
            "func (i *Impl) GetUser(id string) error {\n\treturn nil\n}\n\n"
            "func main() {\n"
            "\timpl := &Impl{}\n"
            "\th := web.NewUserServiceHandler(impl)\n"
            "\t_ = h\n"
            "}\n"
        ),
    }
    rels = _run_exposes(tmp_path, files)
    assert not any("resource::RPC::" in res for _s, res in rels), rels


def test_multi_return_ctor_binding_exposes(tmp_path: Path) -> None:
    # `grpcSrv, err := grpc.New(...)` (the second verified wiring shape):
    # the call value types the first bound name.
    files = {
        "go.mod": "module example.com/app\n\ngo 1.22\n",
        "gen/userv1connect/user.connect.go": _CONNECT_GEN,
        "grpc/grpc.go": (
            "package grpc\n\n"
            "type GRPCServer struct{}\n\n"
            "func New() (*GRPCServer, error) {\n\treturn &GRPCServer{}, nil\n}\n\n"
            "func (g *GRPCServer) GetUser(id string) error {\n\treturn nil\n}\n"
        ),
        "main.go": (
            "package main\n\n"
            'import "example.com/app/gen/userv1connect"\n'
            'import "example.com/app/grpc"\n\n'
            "func main() {\n"
            "\tgrpcSrv, err := grpc.New()\n"
            "\t_ = err\n"
            "\tpath, handler := userv1connect.NewUserServiceHandler(grpcSrv)\n"
            "\t_ = path\n"
            "\t_ = handler\n"
            "}\n"
        ),
    }
    rels = _run_exposes(tmp_path, files)
    project = tmp_path.name
    assert (
        f"{project}.grpc.grpc.GRPCServer.GetUser",
        "resource::RPC::UserService.GetUser",
    ) in rels, rels


def test_promoted_method_from_embedded_base_exposes(tmp_path: Path) -> None:
    # The impl satisfies part of the contract through a method promoted from
    # an embedded type; the edge anchors on the promoted method's own node.
    files = {
        "go.mod": "module example.com/app\n\ngo 1.22\n",
        "gen/userv1connect/user.connect.go": _CONNECT_GEN,
        "main.go": (
            "package main\n\n"
            'import "example.com/app/gen/userv1connect"\n\n'
            "type Base struct{}\n\n"
            "func (b *Base) GetUser(id string) error {\n\treturn nil\n}\n\n"
            "type Impl struct {\n\tBase\n}\n\n"
            "func (i *Impl) PutUser(id string) error {\n\treturn nil\n}\n\n"
            "func main() {\n"
            "\tpath, handler := userv1connect.NewUserServiceHandler(&Impl{})\n"
            "\t_ = path\n"
            "\t_ = handler\n"
            "}\n"
        ),
    }
    rels = _run_exposes(tmp_path, files)
    project = tmp_path.name
    assert (
        f"{project}.main.Impl.PutUser",
        "resource::RPC::UserService.PutUser",
    ) in rels, rels
    assert (
        f"{project}.main.Base.GetUser",
        "resource::RPC::UserService.GetUser",
    ) in rels, rels


def test_unimplemented_embed_does_not_expose_stubs(tmp_path: Path) -> None:
    # connect-go servers embed the generated `Unimplemented<Stem>Handler` for
    # forward compatibility; its promoted stubs are NOT served RPCs.
    gen = _CONNECT_GEN + (
        "\ntype UnimplementedUserServiceHandler struct{}\n\n"
        "func (UnimplementedUserServiceHandler) GetUser(id string) error {\n"
        "\treturn nil\n"
        "}\n\n"
        "func (UnimplementedUserServiceHandler) PutUser(id string) error {\n"
        "\treturn nil\n"
        "}\n"
    )
    files = {
        "go.mod": "module example.com/app\n\ngo 1.22\n",
        "gen/userv1connect/user.connect.go": gen,
        "main.go": (
            "package main\n\n"
            'import "example.com/app/gen/userv1connect"\n\n'
            "type Impl struct {\n"
            "\tuserv1connect.UnimplementedUserServiceHandler\n"
            "}\n\n"
            "func (i *Impl) GetUser(id string) error {\n\treturn nil\n}\n\n"
            "func main() {\n"
            "\tpath, handler := userv1connect.NewUserServiceHandler(&Impl{})\n"
            "\t_ = path\n"
            "\t_ = handler\n"
            "}\n"
        ),
    }
    rels = _run_exposes(tmp_path, files)
    project = tmp_path.name
    assert (
        f"{project}.main.Impl.GetUser",
        "resource::RPC::UserService.GetUser",
    ) in rels, rels
    # PutUser exists only as the generated stub: not a served RPC.
    assert not any(res.endswith("PutUser") for _s, res in rels), rels


def test_earlier_nested_decoy_binding_does_not_win(tmp_path: Path) -> None:
    # A nested block binds the same name to a decoy BEFORE the real binding;
    # resolution must use the last binding preceding the wiring call, not the
    # first one found in a flat body scan.
    files = {
        "go.mod": "module example.com/app\n\ngo 1.22\n",
        "gen/userv1connect/user.connect.go": _CONNECT_GEN,
        "svc/server.go": (
            "package server\n\n"
            "type Server struct{}\n\n"
            "func New() *Server {\n\treturn &Server{}\n}\n\n"
            "func (s *Server) GetUser(id string) error {\n\treturn nil\n}\n"
        ),
        "decoy/decoy.go": (
            "package decoy\n\n"
            "type Decoy struct{}\n\n"
            "func New() *Decoy {\n\treturn &Decoy{}\n}\n\n"
            "func (d *Decoy) GetUser(id string) error {\n\treturn nil\n}\n"
        ),
        "main.go": (
            "package main\n\n"
            'import "example.com/app/gen/userv1connect"\n'
            'import "example.com/app/svc"\n'
            'import "example.com/app/decoy"\n\n'
            "func main() {\n"
            "\t{\n"
            "\t\tuSrv := decoy.New()\n"
            "\t\t_ = uSrv\n"
            "\t}\n"
            "\tuSrv := server.New()\n"
            "\tpath, handler := userv1connect.NewUserServiceHandler(uSrv)\n"
            "\t_ = path\n"
            "\t_ = handler\n"
            "}\n"
        ),
    }
    rels = _run_exposes(tmp_path, files)
    project = tmp_path.name
    assert (
        f"{project}.svc.server.Server.GetUser",
        "resource::RPC::UserService.GetUser",
    ) in rels, rels
    assert not any("Decoy" in src for src, _r in rels), rels


def test_shadow_after_wiring_does_not_suppress(tmp_path: Path) -> None:
    # A local shadowing the package name AFTER the wiring call is out of
    # scope at the call: the wiring is genuine and must still emit.
    files = {
        "go.mod": "module example.com/app\n\ngo 1.22\n",
        "gen/userv1connect/user.connect.go": _CONNECT_GEN,
        "main.go": (
            "package main\n\n"
            'import "example.com/app/gen/userv1connect"\n\n'
            "type Faker struct{}\n\n"
            "type Impl struct{}\n\n"
            "func (i *Impl) GetUser(id string) error {\n\treturn nil\n}\n\n"
            "func main() {\n"
            "\tpath, handler := userv1connect.NewUserServiceHandler(&Impl{})\n"
            "\t_ = path\n"
            "\t_ = handler\n"
            "\tuserv1connect := Faker{}\n"
            "\t_ = userv1connect\n"
            "}\n"
        ),
    }
    rels = _run_exposes(tmp_path, files)
    project = tmp_path.name
    assert (
        f"{project}.main.Impl.GetUser",
        "resource::RPC::UserService.GetUser",
    ) in rels, rels


def test_many_embedded_siblings_do_not_exhaust_promotion(tmp_path: Path) -> None:
    # Nine unrelated embedded types precede the one defining the contract
    # method: breadth must not count against the traversal's cycle budget.
    fillers = "".join(f"type Filler{i} struct{{}}\n\n" for i in range(9))
    embeds = "".join(f"\tFiller{i}\n" for i in range(9))
    files = {
        "go.mod": "module example.com/app\n\ngo 1.22\n",
        "gen/userv1connect/user.connect.go": _CONNECT_GEN,
        "main.go": (
            "package main\n\n"
            'import "example.com/app/gen/userv1connect"\n\n'
            + fillers
            + "type Base struct{}\n\n"
            "func (b *Base) GetUser(id string) error {\n\treturn nil\n}\n\n"
            "type Impl struct {\n" + embeds + "\tBase\n}\n\n"
            "func main() {\n"
            "\tpath, handler := userv1connect.NewUserServiceHandler(&Impl{})\n"
            "\t_ = path\n"
            "\t_ = handler\n"
            "}\n"
        ),
    }
    rels = _run_exposes(tmp_path, files)
    project = tmp_path.name
    assert (
        f"{project}.main.Base.GetUser",
        "resource::RPC::UserService.GetUser",
    ) in rels, rels


def test_deep_promotion_chain_exposes(tmp_path: Path) -> None:
    # A contract method promoted through six embedding levels with no
    # shallower path must still expose: real Go code has no depth limit.
    chain = "type A6 struct {\n\tBase\n}\n\n" + "".join(
        f"type A{i} struct {{\n\tA{i + 1}\n}}\n\n" for i in range(5, 0, -1)
    )
    files = {
        "go.mod": "module example.com/app\n\ngo 1.22\n",
        "gen/userv1connect/user.connect.go": _CONNECT_GEN,
        "main.go": (
            "package main\n\n"
            'import "example.com/app/gen/userv1connect"\n\n'
            "type Base struct{}\n\n"
            "func (b *Base) GetUser(id string) error {\n\treturn nil\n}\n\n"
            + chain
            + "type Impl struct {\n\tA1\n}\n\n"
            "func main() {\n"
            "\tpath, handler := userv1connect.NewUserServiceHandler(&Impl{})\n"
            "\t_ = path\n"
            "\t_ = handler\n"
            "}\n"
        ),
    }
    rels = _run_exposes(tmp_path, files)
    project = tmp_path.name
    assert (
        f"{project}.main.Base.GetUser",
        "resource::RPC::UserService.GetUser",
    ) in rels, rels


def test_diamond_embedding_finds_shallow_path(tmp_path: Path) -> None:
    # A deep chain (Impl -> A1 -> A2 -> A3 -> A4 -> Base) exhausts the depth
    # budget before reaching Base, while a direct embed of A4 reaches it two
    # levels down. The exhausted branch must not poison the shallow one.
    files = {
        "go.mod": "module example.com/app\n\ngo 1.22\n",
        "gen/userv1connect/user.connect.go": _CONNECT_GEN,
        "main.go": (
            "package main\n\n"
            'import "example.com/app/gen/userv1connect"\n\n'
            "type Base struct{}\n\n"
            "func (b *Base) GetUser(id string) error {\n\treturn nil\n}\n\n"
            "type A4 struct {\n\tBase\n}\n\n"
            "type A3 struct {\n\tA4\n}\n\n"
            "type A2 struct {\n\tA3\n}\n\n"
            "type A1 struct {\n\tA2\n}\n\n"
            "type Impl struct {\n\tA1\n\tA4\n}\n\n"
            "func main() {\n"
            "\tpath, handler := userv1connect.NewUserServiceHandler(&Impl{})\n"
            "\t_ = path\n"
            "\t_ = handler\n"
            "}\n"
        ),
    }
    rels = _run_exposes(tmp_path, files)
    project = tmp_path.name
    assert (
        f"{project}.main.Base.GetUser",
        "resource::RPC::UserService.GetUser",
    ) in rels, rels


def test_pointer_embedded_cross_package_base_exposes(tmp_path: Path) -> None:
    # `*base.Base` pointer embedding across packages still promotes.
    files = {
        "go.mod": "module example.com/app\n\ngo 1.22\n",
        "gen/userv1connect/user.connect.go": _CONNECT_GEN,
        "base/base.go": (
            "package base\n\n"
            "type Base struct{}\n\n"
            "func (b *Base) GetUser(id string) error {\n\treturn nil\n}\n"
        ),
        "main.go": (
            "package main\n\n"
            'import "example.com/app/gen/userv1connect"\n'
            'import "example.com/app/base"\n\n'
            "type Impl struct {\n\t*base.Base\n}\n\n"
            "func (i *Impl) PutUser(id string) error {\n\treturn nil\n}\n\n"
            "func main() {\n"
            "\tpath, handler := userv1connect.NewUserServiceHandler(&Impl{})\n"
            "\t_ = path\n"
            "\t_ = handler\n"
            "}\n"
        ),
    }
    rels = _run_exposes(tmp_path, files)
    project = tmp_path.name
    assert (
        f"{project}.base.base.Base.GetUser",
        "resource::RPC::UserService.GetUser",
    ) in rels, rels


def test_shadow_in_closed_block_does_not_suppress(tmp_path: Path) -> None:
    # A shadow inside an earlier, already-closed block is out of scope at
    # the wiring call: the wiring is genuine.
    files = {
        "go.mod": "module example.com/app\n\ngo 1.22\n",
        "gen/userv1connect/user.connect.go": _CONNECT_GEN,
        "main.go": (
            "package main\n\n"
            'import "example.com/app/gen/userv1connect"\n\n'
            "type Faker struct{}\n\n"
            "type Impl struct{}\n\n"
            "func (i *Impl) GetUser(id string) error {\n\treturn nil\n}\n\n"
            "func main() {\n"
            "\t{\n"
            "\t\tuserv1connect := Faker{}\n"
            "\t\t_ = userv1connect\n"
            "\t}\n"
            "\tpath, handler := userv1connect.NewUserServiceHandler(&Impl{})\n"
            "\t_ = path\n"
            "\t_ = handler\n"
            "}\n"
        ),
    }
    rels = _run_exposes(tmp_path, files)
    project = tmp_path.name
    assert (
        f"{project}.main.Impl.GetUser",
        "resource::RPC::UserService.GetUser",
    ) in rels, rels


def test_shadowed_qualifier_is_not_a_wiring(tmp_path: Path) -> None:
    # A local shadowing the imported package name makes the call a method on
    # the LOCAL value, not connect-go wiring (mirrors the client-side guard).
    files = {
        "go.mod": "module example.com/app\n\ngo 1.22\n",
        "gen/userv1connect/user.connect.go": _CONNECT_GEN,
        "main.go": (
            "package main\n\n"
            'import "example.com/app/gen/userv1connect"\n\n'
            "type Faker struct{}\n\n"
            "func (f Faker) NewUserServiceHandler(v any) (string, int) {\n"
            '\treturn "", 0\n'
            "}\n\n"
            "type Impl struct{}\n\n"
            "func (i *Impl) GetUser(id string) error {\n\treturn nil\n}\n\n"
            "func main() {\n"
            "\timpl := &Impl{}\n"
            "\tuserv1connect := Faker{}\n"
            "\tpath, handler := userv1connect.NewUserServiceHandler(impl)\n"
            "\t_ = path\n"
            "\t_ = handler\n"
            "}\n"
        ),
    }
    rels = _run_exposes(tmp_path, files)
    assert not any("resource::RPC::" in res for _s, res in rels), rels


def test_inline_composite_literal_arg_exposes(tmp_path: Path) -> None:
    # The impl passed inline: `NewUserServiceHandler(&Impl{})`.
    files = {
        "go.mod": "module example.com/app\n\ngo 1.22\n",
        "gen/userv1connect/user.connect.go": _CONNECT_GEN,
        "main.go": (
            "package main\n\n"
            'import "example.com/app/gen/userv1connect"\n\n'
            "type Impl struct{}\n\n"
            "func (i *Impl) GetUser(id string) error {\n\treturn nil\n}\n\n"
            "func main() {\n"
            "\tpath, handler := userv1connect.NewUserServiceHandler(&Impl{})\n"
            "\t_ = path\n"
            "\t_ = handler\n"
            "}\n"
        ),
    }
    rels = _run_exposes(tmp_path, files)
    project = tmp_path.name
    assert (
        f"{project}.main.Impl.GetUser",
        "resource::RPC::UserService.GetUser",
    ) in rels, rels


def test_inline_ctor_call_arg_exposes(tmp_path: Path) -> None:
    # The impl constructed inline: `NewUserServiceHandler(server.New())`.
    files = {
        "go.mod": "module example.com/app\n\ngo 1.22\n",
        "gen/userv1connect/user.connect.go": _CONNECT_GEN,
        "svc/server.go": (
            "package server\n\n"
            "type Server struct{}\n\n"
            "func New() *Server {\n\treturn &Server{}\n}\n\n"
            "func (s *Server) GetUser(id string) error {\n\treturn nil\n}\n"
        ),
        "main.go": (
            "package main\n\n"
            'import "example.com/app/gen/userv1connect"\n'
            'import "example.com/app/svc"\n\n'
            "func main() {\n"
            "\tpath, handler := userv1connect.NewUserServiceHandler(server.New())\n"
            "\t_ = path\n"
            "\t_ = handler\n"
            "}\n"
        ),
    }
    rels = _run_exposes(tmp_path, files)
    project = tmp_path.name
    assert (
        f"{project}.svc.server.Server.GetUser",
        "resource::RPC::UserService.GetUser",
    ) in rels, rels


def test_ambiguous_clause_fallback_stays_silent(tmp_path: Path) -> None:
    # TWO imported directories both declare `package server`; the unaliased
    # qualifier cannot be attributed, so no edge is emitted rather than a
    # guess against whichever import iterates first.
    files = {
        "go.mod": "module example.com/app\n\ngo 1.22\n",
        "gen/userv1connect/user.connect.go": _CONNECT_GEN,
        "svca/impl.go": (
            "package server\n\n"
            "type Server struct{}\n\n"
            "func New() *Server {\n\treturn &Server{}\n}\n\n"
            "func (s *Server) GetUser(id string) error {\n\treturn nil\n}\n"
        ),
        "svcb/impl.go": (
            "package server\n\n"
            "type Server struct{}\n\n"
            "func New() *Server {\n\treturn &Server{}\n}\n\n"
            "func (s *Server) GetUser(id string) error {\n\treturn nil\n}\n"
        ),
        "main.go": (
            "package main\n\n"
            'import "example.com/app/gen/userv1connect"\n'
            'import "example.com/app/svca"\n'
            'import "example.com/app/svcb"\n\n'
            "func main() {\n"
            "\tuSrv := server.New()\n"
            "\tpath, handler := userv1connect.NewUserServiceHandler(uSrv)\n"
            "\t_ = path\n"
            "\t_ = handler\n"
            "}\n"
        ),
    }
    rels = _run_exposes(tmp_path, files)
    assert not any("resource::RPC::" in res for _s, res in rels), rels


def test_clause_named_package_ctor_resolves(tmp_path: Path) -> None:
    # An unaliased import's qualifier is the target's `package` clause, which
    # may differ from the directory name (`svc/` declaring `package server`):
    # the import-map key is the path segment, so resolution must fall back to
    # matching the clause recorded for the imported package's modules.
    files = {
        "go.mod": "module example.com/app\n\ngo 1.22\n",
        "gen/userv1connect/user.connect.go": _CONNECT_GEN,
        "svc/impl.go": (
            "package server\n\n"
            "type Server struct{}\n\n"
            "func New() *Server {\n\treturn &Server{}\n}\n\n"
            "func (s *Server) GetUser(id string) error {\n\treturn nil\n}\n"
        ),
        "main.go": (
            "package main\n\n"
            'import "example.com/app/gen/userv1connect"\n'
            'import "example.com/app/svc"\n\n'
            "func main() {\n"
            "\tuSrv := server.New()\n"
            "\tpath, handler := userv1connect.NewUserServiceHandler(uSrv)\n"
            "\t_ = path\n"
            "\t_ = handler\n"
            "}\n"
        ),
    }
    rels = _run_exposes(tmp_path, files)
    project = tmp_path.name
    assert (
        f"{project}.svc.impl.Server.GetUser",
        "resource::RPC::UserService.GetUser",
    ) in rels, rels
