version: '3'

services:
  redis:
    image: redis:8
    ports:
      - '6379:6379'

  inngest:
    image: inngest/inngest:v1.34.0
    command: inngest dev -p 8288 -u http://host.docker.internal:4111/inngest/api --poll-interval=1
    ports:
      - '8288:8288'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
