// <auto-generated/>

#nullable disable

using System;
using System.ClientModel.Primitives;
using System.Threading;

namespace AzureRetailPrices
{
    /// <summary>
    /// Azure Retail Prices API
    /// Provides programmatic access to retrieve retail prices for all Azure services.
    /// Use this API to explore prices for Azure services against different regions and different SKUs.
    /// The API gives you an unauthenticated experience to get retail rates for all Azure services.
    /// </summary>
    public partial class AzureRetailPricesClient
    {
        private readonly Uri _endpoint;
        private readonly string _apiVersion;
        private RetailPrices _cachedRetailPrices;

        /// <summary> Initializes a new instance of AzureRetailPricesClient. </summary>
        public AzureRetailPricesClient() : this(new Uri("https://prices.azure.com"), new AzureRetailPricesClientOptions())
        {
        }

        /// <summary> Initializes a new instance of AzureRetailPricesClient. </summary>
        /// <param name="endpoint"> Service endpoint. </param>
        /// <param name="options"> The options for configuring the client. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="endpoint"/> is null. </exception>
        public AzureRetailPricesClient(Uri endpoint, AzureRetailPricesClientOptions options)
        {
            Argument.AssertNotNull(endpoint, nameof(endpoint));

            options ??= new AzureRetailPricesClientOptions();

            _endpoint = endpoint;
            Pipeline = ClientPipeline.Create(options, Array.Empty<PipelinePolicy>(), new PipelinePolicy[] { new UserAgentPolicy(typeof(AzureRetailPricesClient).Assembly) }, Array.Empty<PipelinePolicy>());
            _apiVersion = options.Version;
        }

        /// <summary> The HTTP pipeline for sending and receiving REST requests and responses. </summary>
        public ClientPipeline Pipeline { get; }

        /// <summary> Initializes a new instance of RetailPrices. </summary>
        public virtual RetailPrices GetRetailPricesClient()
        {
            return Volatile.Read(ref _cachedRetailPrices) ?? Interlocked.CompareExchange(ref _cachedRetailPrices, new RetailPrices(Pipeline, _endpoint, _apiVersion), null) ?? _cachedRetailPrices;
        }
    }
}
