// <auto-generated/>

#nullable disable

using System;
using System.ClientModel;
using System.ClientModel.Primitives;
using System.Threading;

namespace AzureRetailPrices
{
    /// <summary> Retail Prices API operations. </summary>
    public partial class RetailPrices
    {
        private readonly Uri _endpoint;
        private readonly string _apiVersion;

        /// <summary> Initializes a new instance of RetailPrices for mocking. </summary>
        protected RetailPrices()
        {
        }

        /// <summary> Initializes a new instance of RetailPrices. </summary>
        /// <param name="pipeline"> The HTTP pipeline for sending and receiving REST requests and responses. </param>
        /// <param name="endpoint"> Service endpoint. </param>
        /// <param name="apiVersion"></param>
        internal RetailPrices(ClientPipeline pipeline, Uri endpoint, string apiVersion)
        {
            _endpoint = endpoint;
            Pipeline = pipeline;
            _apiVersion = apiVersion;
        }

        /// <summary> The HTTP pipeline for sending and receiving REST requests and responses. </summary>
        public ClientPipeline Pipeline { get; }

        /// <summary>
        /// [Protocol Method] Get Azure Retail Prices
        /// Retrieves retail prices for Azure services. Results are paginated with a maximum
        /// of 1,000 records per request. Use the NextPageLink in the response to retrieve
        /// additional pages.
        /// This is an unauthenticated API - no authentication is required.
        /// <list type="bullet">
        /// <item>
        /// <description> This <see href="https://aka.ms/azsdk/net/protocol-methods">protocol method</see> allows explicit creation of the request and processing of the response for advanced scenarios. </description>
        /// </item>
        /// </list>
        /// </summary>
        /// <param name="currencyCode">
        /// Currency code for pricing (e.g., "USD", "EUR").
        /// Default is USD. See supported currencies documentation.
        /// </param>
        /// <param name="filter">
        /// OData filter expression to filter results.
        /// Supported filter fields: armRegionName, Location, meterId, meterName,
        /// productid, skuId, productName, skuName, serviceName, serviceId,
        /// serviceFamily, priceType, armSkuName
        /// Examples:
        /// <list type="bullet"><item><description>serviceName eq 'Virtual Machines'</description></item><item><description>priceType eq 'Reservation'</description></item><item><description>serviceFamily eq 'Compute'</description></item><item><description>armRegionName eq 'westeurope' and armSkuName eq 'Standard_D2_v3'</description></item></list>
        /// Note: Filter values are case sensitive in API version 2023-01-01-preview and later.
        /// </param>
        /// <param name="meterRegion">
        /// Meter region filter. Set to 'primary' to retrieve only primary meter prices.
        /// Supported with API version 2021-10-01 and later.
        /// </param>
        /// <param name="skip"> Number of records to skip (for pagination). </param>
        /// <param name="options"> The request options, which can override default behaviors of the client pipeline on a per-call basis. </param>
        /// <exception cref="ClientResultException"> Service returned a non-success status code. </exception>
        /// <returns> The response returned from the service. </returns>
        public virtual CollectionResult GetPrices(string currencyCode, string filter, string meterRegion, long? skip, RequestOptions options)
        {
            return new RetailPricesGetPricesCollectionResult(
                this,
                currencyCode,
                filter,
                meterRegion,
                skip,
                options);
        }

        /// <summary>
        /// [Protocol Method] Get Azure Retail Prices
        /// Retrieves retail prices for Azure services. Results are paginated with a maximum
        /// of 1,000 records per request. Use the NextPageLink in the response to retrieve
        /// additional pages.
        /// This is an unauthenticated API - no authentication is required.
        /// <list type="bullet">
        /// <item>
        /// <description> This <see href="https://aka.ms/azsdk/net/protocol-methods">protocol method</see> allows explicit creation of the request and processing of the response for advanced scenarios. </description>
        /// </item>
        /// </list>
        /// </summary>
        /// <param name="currencyCode">
        /// Currency code for pricing (e.g., "USD", "EUR").
        /// Default is USD. See supported currencies documentation.
        /// </param>
        /// <param name="filter">
        /// OData filter expression to filter results.
        /// Supported filter fields: armRegionName, Location, meterId, meterName,
        /// productid, skuId, productName, skuName, serviceName, serviceId,
        /// serviceFamily, priceType, armSkuName
        /// Examples:
        /// <list type="bullet"><item><description>serviceName eq 'Virtual Machines'</description></item><item><description>priceType eq 'Reservation'</description></item><item><description>serviceFamily eq 'Compute'</description></item><item><description>armRegionName eq 'westeurope' and armSkuName eq 'Standard_D2_v3'</description></item></list>
        /// Note: Filter values are case sensitive in API version 2023-01-01-preview and later.
        /// </param>
        /// <param name="meterRegion">
        /// Meter region filter. Set to 'primary' to retrieve only primary meter prices.
        /// Supported with API version 2021-10-01 and later.
        /// </param>
        /// <param name="skip"> Number of records to skip (for pagination). </param>
        /// <param name="options"> The request options, which can override default behaviors of the client pipeline on a per-call basis. </param>
        /// <exception cref="ClientResultException"> Service returned a non-success status code. </exception>
        /// <returns> The response returned from the service. </returns>
        public virtual AsyncCollectionResult GetPricesAsync(string currencyCode, string filter, string meterRegion, long? skip, RequestOptions options)
        {
            return new RetailPricesGetPricesAsyncCollectionResult(
                this,
                currencyCode,
                filter,
                meterRegion,
                skip,
                options);
        }

        /// <summary>
        /// Get Azure Retail Prices
        /// Retrieves retail prices for Azure services. Results are paginated with a maximum
        /// of 1,000 records per request. Use the NextPageLink in the response to retrieve
        /// additional pages.
        /// This is an unauthenticated API - no authentication is required.
        /// </summary>
        /// <param name="currencyCode">
        /// Currency code for pricing (e.g., "USD", "EUR").
        /// Default is USD. See supported currencies documentation.
        /// </param>
        /// <param name="filter">
        /// OData filter expression to filter results.
        /// Supported filter fields: armRegionName, Location, meterId, meterName,
        /// productid, skuId, productName, skuName, serviceName, serviceId,
        /// serviceFamily, priceType, armSkuName
        /// Examples:
        /// <list type="bullet"><item><description>serviceName eq 'Virtual Machines'</description></item><item><description>priceType eq 'Reservation'</description></item><item><description>serviceFamily eq 'Compute'</description></item><item><description>armRegionName eq 'westeurope' and armSkuName eq 'Standard_D2_v3'</description></item></list>
        /// Note: Filter values are case sensitive in API version 2023-01-01-preview and later.
        /// </param>
        /// <param name="meterRegion">
        /// Meter region filter. Set to 'primary' to retrieve only primary meter prices.
        /// Supported with API version 2021-10-01 and later.
        /// </param>
        /// <param name="skip"> Number of records to skip (for pagination). </param>
        /// <param name="cancellationToken"> The cancellation token that can be used to cancel the operation. </param>
        /// <exception cref="ClientResultException"> Service returned a non-success status code. </exception>
        public virtual CollectionResult<RetailPriceItem> GetPrices(string currencyCode = default, string filter = default, string meterRegion = default, long? skip = default, CancellationToken cancellationToken = default)
        {
            return new RetailPricesGetPricesCollectionResultOfT(
                this,
                currencyCode,
                filter,
                meterRegion,
                skip,
                cancellationToken.ToRequestOptions());
        }

        /// <summary>
        /// Get Azure Retail Prices
        /// Retrieves retail prices for Azure services. Results are paginated with a maximum
        /// of 1,000 records per request. Use the NextPageLink in the response to retrieve
        /// additional pages.
        /// This is an unauthenticated API - no authentication is required.
        /// </summary>
        /// <param name="currencyCode">
        /// Currency code for pricing (e.g., "USD", "EUR").
        /// Default is USD. See supported currencies documentation.
        /// </param>
        /// <param name="filter">
        /// OData filter expression to filter results.
        /// Supported filter fields: armRegionName, Location, meterId, meterName,
        /// productid, skuId, productName, skuName, serviceName, serviceId,
        /// serviceFamily, priceType, armSkuName
        /// Examples:
        /// <list type="bullet"><item><description>serviceName eq 'Virtual Machines'</description></item><item><description>priceType eq 'Reservation'</description></item><item><description>serviceFamily eq 'Compute'</description></item><item><description>armRegionName eq 'westeurope' and armSkuName eq 'Standard_D2_v3'</description></item></list>
        /// Note: Filter values are case sensitive in API version 2023-01-01-preview and later.
        /// </param>
        /// <param name="meterRegion">
        /// Meter region filter. Set to 'primary' to retrieve only primary meter prices.
        /// Supported with API version 2021-10-01 and later.
        /// </param>
        /// <param name="skip"> Number of records to skip (for pagination). </param>
        /// <param name="cancellationToken"> The cancellation token that can be used to cancel the operation. </param>
        /// <exception cref="ClientResultException"> Service returned a non-success status code. </exception>
        public virtual AsyncCollectionResult<RetailPriceItem> GetPricesAsync(string currencyCode = default, string filter = default, string meterRegion = default, long? skip = default, CancellationToken cancellationToken = default)
        {
            return new RetailPricesGetPricesAsyncCollectionResultOfT(
                this,
                currencyCode,
                filter,
                meterRegion,
                skip,
                cancellationToken.ToRequestOptions());
        }
    }
}
