// <auto-generated/>

#nullable disable

using System;
using System.ClientModel.Primitives;

namespace AzureRetailPrices
{
    /// <summary></summary>
    public partial class RetailPrices
    {
        private static PipelineMessageClassifier _pipelineMessageClassifier200;

        private static PipelineMessageClassifier PipelineMessageClassifier200 => _pipelineMessageClassifier200 = PipelineMessageClassifier.Create(stackalloc ushort[] { 200 });

        internal PipelineMessage CreateGetPricesRequest(string currencyCode, string filter, string meterRegion, long? skip, RequestOptions options)
        {
            ClientUriBuilder uri = new ClientUriBuilder();
            uri.Reset(_endpoint);
            uri.AppendPath("/api/retail/prices", false);
            if (_apiVersion != null)
            {
                uri.AppendQuery("api-version", _apiVersion, true);
            }
            if (currencyCode != null)
            {
                uri.AppendQuery("currencyCode", currencyCode, true);
            }
            if (filter != null)
            {
                uri.AppendQuery("$filter", filter, true);
            }
            if (meterRegion != null)
            {
                uri.AppendQuery("meterRegion", meterRegion, true);
            }
            if (skip != null)
            {
                uri.AppendQuery("$skip", TypeFormatters.ConvertToString(skip), true);
            }
            PipelineMessage message = Pipeline.CreateMessage(uri.ToUri(), "GET", PipelineMessageClassifier200);
            PipelineRequest request = message.Request;
            request.Headers.Set("Accept", "application/json");
            message.Apply(options);
            return message;
        }

        internal PipelineMessage CreateNextGetPricesRequest(Uri nextPage, string currencyCode, string filter, string meterRegion, long? skip, RequestOptions options)
        {
            ClientUriBuilder uri = new ClientUriBuilder();
            uri.Reset(nextPage);
            PipelineMessage message = Pipeline.CreateMessage(uri.ToUri(), "GET", PipelineMessageClassifier200);
            PipelineRequest request = message.Request;
            request.Headers.Set("Accept", "application/json");
            message.Apply(options);
            return message;
        }
    }
}
