"""Shared fixtures for shotcut tests."""

import os
import subprocess
import tempfile

import pytest

from cli_anything.shotcut.core.session import Session
from cli_anything.shotcut.core import project as proj_mod
from cli_anything.shotcut.core import timeline as tl_mod
from cli_anything.shotcut.core import media as media_mod

PROFILE_HD1080 = {
    "width": "1920", "height": "1080",
    "frame_rate_num": "30000", "frame_rate_den": "1001",
    "sample_aspect_num": "1", "sample_aspect_den": "1",
    "display_aspect_num": "16", "display_aspect_den": "9",
    "progressive": "1", "colorspace": "709",
}


def generate_video(path=None):
    """Generate a 10-second test video using ffmpeg."""
    if path is None:
        fd, path = tempfile.mkstemp(suffix=".mp4", prefix="shotcut_test_")
        os.close(fd)
    subprocess.run([
        "ffmpeg", "-y",
        "-f", "lavfi", "-i", "color=c=red:s=1920x1080:d=10:r=30000/1001",
        "-c:v", "libx264", "-pix_fmt", "yuv420p",
        "-preset", "ultrafast", "-crf", "35",
        path,
    ], check=True, capture_output=True)
    return path


@pytest.fixture(scope="session")
def video():
    """Session-scoped test video generated by ffmpeg."""
    path = generate_video()
    yield path
    os.unlink(path)


@pytest.fixture
def dummy_file(tmp_path):
    """Temp .mp4 with dummy bytes for unit tests."""
    p = tmp_path / "dummy.mp4"
    p.write_bytes(b"dummy")
    return str(p)


@pytest.fixture
def session():
    """Session with a new hd1080p30 project."""
    s = Session()
    proj_mod.new_project(s, "hd1080p30")
    return s


@pytest.fixture
def session_with_track(session):
    """Session with one video track."""
    tl_mod.add_track(session, "video")
    return session


@pytest.fixture
def imported_clip(session_with_track, dummy_file):
    """Import a dummy media file and return its clip_id."""
    result = media_mod.import_media(session_with_track, dummy_file)
    return result["clip_id"]


@pytest.fixture
def session_with_clip(session_with_track, imported_clip):
    """Session with one video track and one clip."""
    tl_mod.add_clip(session_with_track, imported_clip, 1,
                    in_point="00:00:00.000", out_point="00:00:05.000")
    return session_with_track


@pytest.fixture
def session_with_two_clips(session_with_track, imported_clip):
    """Session with one video track and two 10s clips."""
    for _ in range(2):
        tl_mod.add_clip(session_with_track, imported_clip, 1,
                        in_point="00:00:00.000", out_point="00:00:10.000")
    return session_with_track


@pytest.fixture
def session_with_three_clips(session_with_track, imported_clip):
    """Session with one video track and three 10s clips."""
    for _ in range(3):
        tl_mod.add_clip(session_with_track, imported_clip, 1,
                        in_point="00:00:00.000", out_point="00:00:10.000")
    return session_with_track


@pytest.fixture
def session_with_two_tracks(session, dummy_file):
    """Session with two video tracks, each with one clip."""
    tl_mod.add_track(session, "video")
    tl_mod.add_track(session, "video")
    clip_id = media_mod.import_media(session, dummy_file)["clip_id"]
    tl_mod.add_clip(session, clip_id, 1,
                    in_point="00:00:00.000", out_point="00:00:05.000")
    tl_mod.add_clip(session, clip_id, 2,
                    in_point="00:00:00.000", out_point="00:00:05.000")
    return session
