schemaVersion: 1
enabledWorkflows:
  - swift-package
  - project-discovery
debug: false
sentryDisabled: true
sessionDefaults:
  workspacePath: .swiftpm/xcode/package.xcworkspace
  scheme: spm-Package
setupPreferences:
  platforms:
    - macOS
