// <auto-generated/>

#nullable disable

namespace AzureRetailPrices
{
    /// <summary> Price type enumeration. </summary>
    public enum PriceType
    {
        /// <summary> Reserved instance pricing. </summary>
        Reservation,
        /// <summary> On-demand consumption pricing. </summary>
        Consumption,
        /// <summary> Dev/Test consumption pricing. </summary>
        DevTestConsumption
    }
}
