// <auto-generated/>

#nullable disable

namespace AzureRetailPrices
{
    /// <summary> Supported service family values. </summary>
    public enum ServiceFamily
    {
        /// <summary> Analytics. </summary>
        Analytics,
        /// <summary> AzureArc. </summary>
        AzureArc,
        /// <summary> AzureCommunicationServices. </summary>
        AzureCommunicationServices,
        /// <summary> AzureSecurity. </summary>
        AzureSecurity,
        /// <summary> AzureStack. </summary>
        AzureStack,
        /// <summary> Compute. </summary>
        Compute,
        /// <summary> Containers. </summary>
        Containers,
        /// <summary> Data. </summary>
        Data,
        /// <summary> Databases. </summary>
        Databases,
        /// <summary> DeveloperTools. </summary>
        DeveloperTools,
        /// <summary> Dynamics. </summary>
        Dynamics,
        /// <summary> Gaming. </summary>
        Gaming,
        /// <summary> Integration. </summary>
        Integration,
        /// <summary> InternetOfThings. </summary>
        InternetOfThings,
        /// <summary> ManagementAndGovernance. </summary>
        ManagementAndGovernance,
        /// <summary> MicrosoftSyntex. </summary>
        MicrosoftSyntex,
        /// <summary> MixedReality. </summary>
        MixedReality,
        /// <summary> Networking. </summary>
        Networking,
        /// <summary> Other. </summary>
        Other,
        /// <summary> PowerPlatform. </summary>
        PowerPlatform,
        /// <summary> QuantumComputing. </summary>
        QuantumComputing,
        /// <summary> Security. </summary>
        Security,
        /// <summary> Storage. </summary>
        Storage,
        /// <summary> Telecommunications. </summary>
        Telecommunications,
        /// <summary> Web. </summary>
        Web,
        /// <summary> WindowsVirtualDesktop. </summary>
        WindowsVirtualDesktop
    }
}
