// <auto-generated/>

#nullable disable

using System;

namespace AzureRetailPrices
{
    internal static partial class ServiceFamilyExtensions
    {
        /// <param name="value"> The value to serialize. </param>
        public static string ToSerialString(this ServiceFamily value) => value switch
        {
            ServiceFamily.Analytics => "Analytics",
            ServiceFamily.AzureArc => "Azure Arc",
            ServiceFamily.AzureCommunicationServices => "Azure Communication Services",
            ServiceFamily.AzureSecurity => "Azure Security",
            ServiceFamily.AzureStack => "Azure Stack",
            ServiceFamily.Compute => "Compute",
            ServiceFamily.Containers => "Containers",
            ServiceFamily.Data => "Data",
            ServiceFamily.Databases => "Databases",
            ServiceFamily.DeveloperTools => "Developer Tools",
            ServiceFamily.Dynamics => "Dynamics",
            ServiceFamily.Gaming => "Gaming",
            ServiceFamily.Integration => "Integration",
            ServiceFamily.InternetOfThings => "Internet Of Things",
            ServiceFamily.ManagementAndGovernance => "Management and Governance",
            ServiceFamily.MicrosoftSyntex => "Microsoft Syntex",
            ServiceFamily.MixedReality => "Mixed Reality",
            ServiceFamily.Networking => "Networking",
            ServiceFamily.Other => "Other",
            ServiceFamily.PowerPlatform => "Power Platform",
            ServiceFamily.QuantumComputing => "Quantum Computing",
            ServiceFamily.Security => "Security",
            ServiceFamily.Storage => "Storage",
            ServiceFamily.Telecommunications => "Telecommunications",
            ServiceFamily.Web => "Web",
            ServiceFamily.WindowsVirtualDesktop => "Windows Virtual Desktop",
            _ => throw new ArgumentOutOfRangeException(nameof(value), value, "Unknown ServiceFamily value.")
        };

        /// <param name="value"> The value to deserialize. </param>
        public static ServiceFamily ToServiceFamily(this string value)
        {
            if (StringComparer.OrdinalIgnoreCase.Equals(value, "Analytics"))
            {
                return ServiceFamily.Analytics;
            }
            if (StringComparer.OrdinalIgnoreCase.Equals(value, "Azure Arc"))
            {
                return ServiceFamily.AzureArc;
            }
            if (StringComparer.OrdinalIgnoreCase.Equals(value, "Azure Communication Services"))
            {
                return ServiceFamily.AzureCommunicationServices;
            }
            if (StringComparer.OrdinalIgnoreCase.Equals(value, "Azure Security"))
            {
                return ServiceFamily.AzureSecurity;
            }
            if (StringComparer.OrdinalIgnoreCase.Equals(value, "Azure Stack"))
            {
                return ServiceFamily.AzureStack;
            }
            if (StringComparer.OrdinalIgnoreCase.Equals(value, "Compute"))
            {
                return ServiceFamily.Compute;
            }
            if (StringComparer.OrdinalIgnoreCase.Equals(value, "Containers"))
            {
                return ServiceFamily.Containers;
            }
            if (StringComparer.OrdinalIgnoreCase.Equals(value, "Data"))
            {
                return ServiceFamily.Data;
            }
            if (StringComparer.OrdinalIgnoreCase.Equals(value, "Databases"))
            {
                return ServiceFamily.Databases;
            }
            if (StringComparer.OrdinalIgnoreCase.Equals(value, "Developer Tools"))
            {
                return ServiceFamily.DeveloperTools;
            }
            if (StringComparer.OrdinalIgnoreCase.Equals(value, "Dynamics"))
            {
                return ServiceFamily.Dynamics;
            }
            if (StringComparer.OrdinalIgnoreCase.Equals(value, "Gaming"))
            {
                return ServiceFamily.Gaming;
            }
            if (StringComparer.OrdinalIgnoreCase.Equals(value, "Integration"))
            {
                return ServiceFamily.Integration;
            }
            if (StringComparer.OrdinalIgnoreCase.Equals(value, "Internet Of Things"))
            {
                return ServiceFamily.InternetOfThings;
            }
            if (StringComparer.OrdinalIgnoreCase.Equals(value, "Management and Governance"))
            {
                return ServiceFamily.ManagementAndGovernance;
            }
            if (StringComparer.OrdinalIgnoreCase.Equals(value, "Microsoft Syntex"))
            {
                return ServiceFamily.MicrosoftSyntex;
            }
            if (StringComparer.OrdinalIgnoreCase.Equals(value, "Mixed Reality"))
            {
                return ServiceFamily.MixedReality;
            }
            if (StringComparer.OrdinalIgnoreCase.Equals(value, "Networking"))
            {
                return ServiceFamily.Networking;
            }
            if (StringComparer.OrdinalIgnoreCase.Equals(value, "Other"))
            {
                return ServiceFamily.Other;
            }
            if (StringComparer.OrdinalIgnoreCase.Equals(value, "Power Platform"))
            {
                return ServiceFamily.PowerPlatform;
            }
            if (StringComparer.OrdinalIgnoreCase.Equals(value, "Quantum Computing"))
            {
                return ServiceFamily.QuantumComputing;
            }
            if (StringComparer.OrdinalIgnoreCase.Equals(value, "Security"))
            {
                return ServiceFamily.Security;
            }
            if (StringComparer.OrdinalIgnoreCase.Equals(value, "Storage"))
            {
                return ServiceFamily.Storage;
            }
            if (StringComparer.OrdinalIgnoreCase.Equals(value, "Telecommunications"))
            {
                return ServiceFamily.Telecommunications;
            }
            if (StringComparer.OrdinalIgnoreCase.Equals(value, "Web"))
            {
                return ServiceFamily.Web;
            }
            if (StringComparer.OrdinalIgnoreCase.Equals(value, "Windows Virtual Desktop"))
            {
                return ServiceFamily.WindowsVirtualDesktop;
            }
            throw new ArgumentOutOfRangeException(nameof(value), value, "Unknown ServiceFamily value.");
        }
    }
}
