name: Labeler

permissions:
  contents: read
  pull-requests: write

on:
  - pull_request_target

jobs:
  labeler:
    runs-on: starsling-ubuntu-24.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@e8d4307400f9427dba7cb98e488d6ab85f1cec5f
        with:
          fetch-depth: 1
          fetch-tags: false
          filter: 'blob:none'
          show-progress: false
      - uses: actions/labeler@v6
