<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
    <OutputType>Exe</OutputType>
    <HasLiveTests>false</HasLiveTests>
    <HasUnitTests>true</HasUnitTests>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="$(RepoRoot)core\Azure.Mcp.Core\tests\Azure.Mcp.Tests\Azure.Mcp.Tests.csproj" />
    <ProjectReference Include="..\..\src\Azure.Mcp.Tools.Insights.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="NSubstitute.Analyzers.CSharp" />
    <PackageReference Include="xunit.v3.mtp-v2" />
    <PackageReference Include="coverlet.MTP" />
  </ItemGroup>
</Project>
