/**
 * Per-IDE skill-hook emitter.
 *
 * Writes one `SKILL.md` file per public instruction into a client-specific
 * directory so target IDEs (Copilot, Claude Code, Codex) can auto-load them
 * as skills.  Extracted from the old `OnboardingWizard.emitSkillHooks` (the
 * wizard and the TOON-based onboarding stack have since been deleted).
 *
 * Layout:
 *
 *   | Client   | Local                | Global                       |
 *   |----------|----------------------|------------------------------|
 *   | copilot  | .github/skills/      | ~/.copilot/skills/           |
 *   | claude   | .claude/skills/      | ~/.claude/skills/            |
 *   | codex    | .agents/skills/      | ~/.agents/skills/            |
 *
 * "Local" = workspace-relative; "global" = under the user's home directory.
 */

import { mkdir, writeFile } from "node:fs/promises";
import { homedir } from "node:os";
import { join } from "node:path";
import chalk from "chalk";
import { INSTRUCTION_SPECS } from "../instructions/instruction-specs.js";

export type SkillHookClient = "copilot" | "claude" | "codex";

export const SKILL_HOOK_CLIENTS: readonly SkillHookClient[] = [
	"copilot",
	"claude",
	"codex",
];

const SKILL_HOOK_DIRS: Record<
	SkillHookClient,
	{ local: string[]; global: string[] }
> = {
	copilot: {
		local: [".github", "skills"],
		global: [".copilot", "skills"],
	},
	claude: {
		local: [".claude", "skills"],
		global: [".claude", "skills"],
	},
	codex: {
		local: [".agents", "skills"],
		global: [".agents", "skills"],
	},
};

export interface EmitSkillHooksOptions {
	/** When true, write to user-home paths instead of workspace-relative ones. */
	global?: boolean;
	/** Subset of clients to target.  Defaults to all three. */
	clients?: readonly SkillHookClient[];
	/** Override the workspace root used for "local" writes (defaults to cwd). */
	cwd?: string;
	/** Override `homedir()` (test seam). */
	home?: string;
	/** Disable the per-client console summary (test seam). */
	quiet?: boolean;
}

/**
 * Emit one SKILL.md per public instruction into the requested clients'
 * skill-hook directories.  Returns the total file count.
 */
export async function emitSkillHooks(
	options: EmitSkillHooksOptions = {},
): Promise<number> {
	const {
		global = false,
		clients = SKILL_HOOK_CLIENTS,
		cwd = process.cwd(),
		home = homedir(),
		quiet = false,
	} = options;

	const publicSpecs = INSTRUCTION_SPECS.filter((spec) => spec.public);
	let written = 0;

	for (const client of clients) {
		const segments = global
			? SKILL_HOOK_DIRS[client].global
			: SKILL_HOOK_DIRS[client].local;
		const rootDir = join(global ? home : cwd, ...segments);

		for (const spec of publicSpecs) {
			const skillDir = join(rootDir, spec.toolName);
			await mkdir(skillDir, { recursive: true });
			const content = [
				"---",
				`name: "${spec.toolName}"`,
				"description: |",
				...spec.description.split("\n").map((line) => `  ${line}`),
				"---",
				"",
				`<!-- Generated by mcp-cli onboard skills${global ? " --global" : ""} --client ${client} -->`,
				`<!-- Source: ${spec.sourcePath} -->`,
				"",
			].join("\n");
			await writeFile(join(skillDir, "SKILL.md"), content, "utf8");
			written++;
		}

		if (!quiet) {
			const destLabel = global
				? `~/${segments.join("/")}/ `
				: `${segments.join("/")}/ `;
			console.log(
				chalk.cyan(
					`  📁 [${client}] Skill hooks → ${destLabel}(${publicSpecs.length} files)`,
				),
			);
		}
	}

	return written;
}
