/**
 * Atlas Pulse module — read-only surface over the Atlas asset graph.
 *
 * Routes:
 *   GET  /api/atlas                    → redacted snapshot (assets, edges, observations, gaps)
 *   GET  /api/atlas/insights           → deterministic metrics + cached AI narrative (+ stale flag)
 *   POST /api/atlas/insights/regenerate → force a fresh Inference pass (202 + generating)
 *
 * Holds ZERO truth: the snapshot is produced by `atlas export`; metrics by
 * `atlas insights` (read-only SQL). The AI narrative is generated by shelling
 * `Inference.ts` over the metrics — cached to MEMORY/STATE/atlas-insights.json,
 * keyed by a metric content hash, regenerated when the graph changes (mirrors
 * the algorithm-tab summary pattern). No secrets in this module or its payloads.
 */
import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";

const MODULE_NAME = "atlas";
const CLAUDE_DIR = process.env.CLAUDE_CONFIG_DIR || join(homedir(), ".claude");
const LIFEOS_DIR = join(CLAUDE_DIR, "LIFEOS");
const ATLAS_CLI = join(LIFEOS_DIR, "ATLAS", "Atlas.ts");
const INFERENCE = join(LIFEOS_DIR, "TOOLS", "Inference.ts");
const SNAPSHOT_PATH =
  process.env.ATLAS_SNAPSHOT_PATH || join(homedir(), ".local/state/lifeos/atlas/snapshot.json");
const INSIGHTS_CACHE = join(LIFEOS_DIR, "MEMORY", "STATE", "atlas-insights.json");

const CACHE_MS = 30_000;
const state: {
  running: boolean;
  cached: string | null;
  cachedAt: number;
  generating: boolean;
} = { running: false, cached: null, cachedAt: 0, generating: false };

export function start() {
  state.running = true;
}

export function health() {
  return { module: MODULE_NAME, running: state.running, snapshot_present: existsSync(SNAPSHOT_PATH) };
}

// ── Metrics + inference ───────────────────────────────────────────────

async function metrics(): Promise<Record<string, unknown> | null> {
  const proc = Bun.spawn(["bun", ATLAS_CLI, "insights"], { stdout: "pipe", stderr: "pipe" });
  const [out, code] = await Promise.all([new Response(proc.stdout).text(), proc.exited]);
  if (code !== 0 || !out.trim()) return null;
  try {
    return JSON.parse(out);
  } catch {
    return null;
  }
}

function metricHash(m: Record<string, unknown>): string {
  return createHash("sha256").update(JSON.stringify(m)).digest("hex").slice(0, 16);
}

const SYSTEM_PROMPT = `You are writing the Insights panel for Atlas, the LifeOS asset graph — the graph of everything the principal's system owns (Cloudflare workers, domains, DNS, repos, projects, data stores, security-scanner targets, services, devices). You are given the current deterministic structural metrics as JSON.

Write a sharp, specific analysis in plain Paul-Graham-plain language across EXACTLY these three sections:

## Running the system
Describe operational shape from the metrics. worker_wiring shows how workers are actually invoked — served (custom domain / workers.dev / route), cron, or service-binding target; most workers serve traffic one of these ways. unwired_workers is the count with NO invocation path at all — that is the only "dead deploy" signal, and it is usually small. Report worker_wiring honestly; do NOT call a worker unused just because it lacks a custom domain. Mention data-store counts as capacity, not waste.

## Security
What the graph reveals about coverage: auth_curation_gaps domains are served but have no curated auth-boundary target — note these are still hygiene-scanned hourly and that the gap matters for auth-bearing apps, not static sites. Give the ratio of curated targets to total domains. Flag concentration risk only if a metric supports it.

## How things interconnect
What the edge structure shows: which zones carry the most blast radius (blast_zones — deleting them orphans the most owned records), and where convergence/single-points-of-failure sit (e.g. RUNS_ON onto one machine, CALLS fan-in). Name the top zones and their owned counts.

Rules: 200-320 words. Every sentence tied to a number in the data. CRITICAL: never state a worker/asset is "unused", "dead", "orphaned", or "burning money" unless unwired_workers or a stale count backs it — absence of one edge type is not absence of use. No marketing register, no dramatization, no filler. Output ONLY markdown — no preamble, no closing notes.`;

async function inference(userJson: string): Promise<string | null> {
  const proc = Bun.spawn(
    ["bun", INFERENCE, "--level", "high", "--timeout", "120000", SYSTEM_PROMPT, userJson],
    { stdout: "pipe", stderr: "pipe" },
  );
  const [out, err, code] = await Promise.all([
    new Response(proc.stdout).text(),
    new Response(proc.stderr).text(),
    proc.exited,
  ]);
  if (code !== 0 || !out.trim()) {
    console.log(`[${MODULE_NAME}] inference failed (exit ${code}): ${err.slice(0, 200)}`);
    return null;
  }
  const paras = out.trim().split(/\n{2,}/);
  while (paras.length > 1 && /^[*_(\s]*Note[:\s]/i.test(paras[paras.length - 1])) paras.pop();
  return paras.join("\n\n").trim();
}

function readCache(): { hash: string; narrative: string; generated_at: string } | null {
  if (!existsSync(INSIGHTS_CACHE)) return null;
  try {
    return JSON.parse(readFileSync(INSIGHTS_CACHE, "utf8"));
  } catch {
    return null;
  }
}

async function regenerate(m: Record<string, unknown>): Promise<void> {
  if (state.generating) return;
  state.generating = true;
  try {
    const narrative = await inference(JSON.stringify(m));
    if (narrative) {
      mkdirSync(join(LIFEOS_DIR, "MEMORY", "STATE"), { recursive: true });
      writeFileSync(
        INSIGHTS_CACHE,
        JSON.stringify({ hash: metricHash(m), narrative, generated_at: new Date().toISOString() }, null, 2),
      );
    }
  } finally {
    state.generating = false;
  }
}

// ── Request handling ──────────────────────────────────────────────────

export async function handleRequest(req: Request, pathname: string): Promise<Response | null> {
  if (pathname === "/api/atlas/insights/regenerate" && req.method === "POST") {
    const m = await metrics();
    if (!m) return Response.json({ error: "metrics unavailable" }, { status: 503 });
    regenerate(m).catch((e) => console.log(`[${MODULE_NAME}] regen: ${e}`));
    return Response.json({ generating: true }, { status: 202 });
  }

  if (pathname === "/api/atlas/insights") {
    const m = await metrics();
    if (!m) return Response.json({ available: false, error: "run an atlas sync first" });
    const hash = metricHash(m);
    const cache = readCache();
    const stale = !cache || cache.hash !== hash;
    // Fire-and-forget regeneration the moment the graph has moved on.
    if (stale && !state.generating) regenerate(m).catch(() => {});
    return Response.json({
      available: true,
      metrics: m,
      narrative: cache?.narrative ?? null,
      narrative_generated_at: cache?.generated_at ?? null,
      stale,
      generating: state.generating,
    });
  }

  if (pathname !== "/api/atlas") return null;

  const now = Date.now();
  if (state.cached && now - state.cachedAt < CACHE_MS) {
    return new Response(state.cached, { headers: { "Content-Type": "application/json" } });
  }
  try {
    if (!existsSync(SNAPSHOT_PATH)) {
      return Response.json({ available: false, error: "no snapshot — run: bun ~/.claude/LIFEOS/ATLAS/Atlas.ts sync" });
    }
    const snapshot = JSON.parse(readFileSync(SNAPSHOT_PATH, "utf8")) as Record<string, unknown>;
    const body = JSON.stringify({ available: true, snapshot_age_ms: now - statSync(SNAPSHOT_PATH).mtimeMs, ...snapshot });
    state.cached = body;
    state.cachedAt = now;
    return new Response(body, { headers: { "Content-Type": "application/json" } });
  } catch (err) {
    return Response.json({ available: false, error: String(err) });
  }
}
