COINBASE_DEFAULT_RATE_LIMIT = 2
COINBASE_MARKET_DATA_RATE_LIMIT = 2
COINBASE_ACCOUNTS_RATE_LIMIT = 2
COINBASE_PRODUCTS_RATE_LIMIT = 2
COINBASE_MAX_RETRY_ATTEMPTS = 3
COINBASE_INITIAL_DELAY = 1.0
COINBASE_MAX_DELAY = 10.0
COINBASE_BACKOFF_FACTOR = 2.0
