// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	apiv1alpha1 "github.com/agent-substrate/substrate/pkg/api/v1alpha1"
	scheme "github.com/agent-substrate/substrate/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// CSIDriverConfigsGetter has a method to return a CSIDriverConfigInterface.
// A group's client should implement this interface.
type CSIDriverConfigsGetter interface {
	CSIDriverConfigs() CSIDriverConfigInterface
}

// CSIDriverConfigInterface has methods to work with CSIDriverConfig resources.
type CSIDriverConfigInterface interface {
	Create(ctx context.Context, cSIDriverConfig *apiv1alpha1.CSIDriverConfig, opts v1.CreateOptions) (*apiv1alpha1.CSIDriverConfig, error)
	Update(ctx context.Context, cSIDriverConfig *apiv1alpha1.CSIDriverConfig, opts v1.UpdateOptions) (*apiv1alpha1.CSIDriverConfig, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*apiv1alpha1.CSIDriverConfig, error)
	List(ctx context.Context, opts v1.ListOptions) (*apiv1alpha1.CSIDriverConfigList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *apiv1alpha1.CSIDriverConfig, err error)
	CSIDriverConfigExpansion
}

// cSIDriverConfigs implements CSIDriverConfigInterface
type cSIDriverConfigs struct {
	*gentype.ClientWithList[*apiv1alpha1.CSIDriverConfig, *apiv1alpha1.CSIDriverConfigList]
}

// newCSIDriverConfigs returns a CSIDriverConfigs
func newCSIDriverConfigs(c *ApiV1alpha1Client) *cSIDriverConfigs {
	return &cSIDriverConfigs{
		gentype.NewClientWithList[*apiv1alpha1.CSIDriverConfig, *apiv1alpha1.CSIDriverConfigList](
			"csidriverconfigs",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *apiv1alpha1.CSIDriverConfig { return &apiv1alpha1.CSIDriverConfig{} },
			func() *apiv1alpha1.CSIDriverConfigList { return &apiv1alpha1.CSIDriverConfigList{} },
		),
	}
}
