// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	apiv1alpha1 "github.com/agent-substrate/substrate/pkg/api/v1alpha1"
	scheme "github.com/agent-substrate/substrate/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// SandboxConfigsGetter has a method to return a SandboxConfigInterface.
// A group's client should implement this interface.
type SandboxConfigsGetter interface {
	SandboxConfigs() SandboxConfigInterface
}

// SandboxConfigInterface has methods to work with SandboxConfig resources.
type SandboxConfigInterface interface {
	Create(ctx context.Context, sandboxConfig *apiv1alpha1.SandboxConfig, opts v1.CreateOptions) (*apiv1alpha1.SandboxConfig, error)
	Update(ctx context.Context, sandboxConfig *apiv1alpha1.SandboxConfig, opts v1.UpdateOptions) (*apiv1alpha1.SandboxConfig, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*apiv1alpha1.SandboxConfig, error)
	List(ctx context.Context, opts v1.ListOptions) (*apiv1alpha1.SandboxConfigList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *apiv1alpha1.SandboxConfig, err error)
	SandboxConfigExpansion
}

// sandboxConfigs implements SandboxConfigInterface
type sandboxConfigs struct {
	*gentype.ClientWithList[*apiv1alpha1.SandboxConfig, *apiv1alpha1.SandboxConfigList]
}

// newSandboxConfigs returns a SandboxConfigs
func newSandboxConfigs(c *ApiV1alpha1Client) *sandboxConfigs {
	return &sandboxConfigs{
		gentype.NewClientWithList[*apiv1alpha1.SandboxConfig, *apiv1alpha1.SandboxConfigList](
			"sandboxconfigs",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *apiv1alpha1.SandboxConfig { return &apiv1alpha1.SandboxConfig{} },
			func() *apiv1alpha1.SandboxConfigList { return &apiv1alpha1.SandboxConfigList{} },
		),
	}
}
