"""Render the usage-report markdown deterministically from analyzer outputs.

This module replaces LLM-driven report generation with a pure-data pipeline:

  metrics-*.json  +  liveness-*.json  +  ltv-spend-*.json  +
  install-forecast-*.json  +  github_stats.json  +  active-instances-*.csv  +
  lifetime-buckets-*.csv  +  compute-platform-snapshots-*.md  +  tables-*.md
            |
            v
  report_template.md  ->  rendered ai-registry-usage-report-YYYY-MM-DD.md

Every cell value comes from JSON or CSV files. The Recommendations section
is generated by rule-based triggers (see recommendations.py). The LLM is
not in the report-content path.

Usage:
    /usr/bin/python3 .claude/skills/usage-report/render_report.py \\
        --date YYYY-MM-DD \\
        --output-dir .scratchpad/usage-reports/YYYY-MM-DD/ \\
        --search-dir .scratchpad/usage-reports/

Reads from:
  $output-dir/metrics-{date}.json
  $output-dir/liveness-{date}.json
  $output-dir/ltv-spend-{date}.json
  $output-dir/install-forecast-{date}.json
  $output-dir/github_stats.json
  $output-dir/active-instances-{date}.csv
  $output-dir/lifetime-buckets-{date}.csv
  $output-dir/compute-platform-snapshots-{date}.md
  $output-dir/tables-{date}.md  (for the few sub-tables we reuse verbatim)

  Plus the previous report's metrics-*.json (auto-discovered under search-dir)
  for delta calculations.
"""

from __future__ import annotations

import argparse
import csv
import json
import logging
import os
import re
import sys
from datetime import datetime, timedelta
from pathlib import Path

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s,p%(process)s,{%(filename)s:%(lineno)d},%(levelname)s,%(message)s",
)
logger = logging.getLogger(__name__)

DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")


def _previous_date(
    date_str: str,
) -> str:
    """Return YYYY-MM-DD for date - 1."""
    d = datetime.strptime(date_str, "%Y-%m-%d")
    return (d - timedelta(days=1)).strftime("%Y-%m-%d")


def _find_previous_metrics(
    search_dir: str,
    current_date: str,
) -> str | None:
    """Find the most recent metrics-*.json file before current_date."""
    candidates: list[tuple[str, str]] = []
    for entry in os.listdir(search_dir):
        full = os.path.join(search_dir, entry)
        if not os.path.isdir(full) or not DATE_RE.match(entry):
            continue
        if entry >= current_date:
            continue
        candidate = os.path.join(full, f"metrics-{entry}.json")
        if os.path.exists(candidate):
            candidates.append((entry, candidate))
    if not candidates:
        return None
    candidates.sort(reverse=True)
    return candidates[0][1]


def _find_previous_liveness(
    search_dir: str,
    current_date: str,
) -> str | None:
    """Find the most recent liveness-*.json file before current_date."""
    candidates: list[tuple[str, str]] = []
    for entry in os.listdir(search_dir):
        full = os.path.join(search_dir, entry)
        if not os.path.isdir(full) or not DATE_RE.match(entry):
            continue
        if entry >= current_date:
            continue
        candidate = os.path.join(full, f"liveness-{entry}.json")
        if os.path.exists(candidate):
            candidates.append((entry, candidate))
    if not candidates:
        return None
    candidates.sort(reverse=True)
    return candidates[0][1]


def _find_previous_github_stats(
    search_dir: str,
    current_date: str,
) -> str | None:
    """Find the most recent github_stats.json file before current_date."""
    candidates: list[tuple[str, str]] = []
    for entry in os.listdir(search_dir):
        full = os.path.join(search_dir, entry)
        if not os.path.isdir(full) or not DATE_RE.match(entry):
            continue
        if entry >= current_date:
            continue
        candidate = os.path.join(full, "github_stats.json")
        if os.path.exists(candidate):
            candidates.append((entry, candidate))
    if not candidates:
        return None
    candidates.sort(reverse=True)
    return candidates[0][1]


def _format_delta_int(
    delta: int,
) -> str:
    """Format an integer delta with sign and a +N / -N / 0 string."""
    if delta > 0:
        return f"+{delta:,}"
    if delta < 0:
        return f"{delta:,}"
    return "0"


def _format_delta_pct(
    current: int | float,
    previous: int | float,
) -> str:
    """Compute % change and format with sign."""
    if previous == 0:
        return ""
    pct = (current - previous) / previous * 100
    if abs(pct) < 0.5:
        return "(0%)"
    sign = "+" if pct >= 0 else ""
    return f"({sign}{pct:.0f}%)"


def _format_combined_delta(
    current: int | float,
    previous: int | float,
) -> str:
    """Render '+N (+X%)' for a delta + percent change."""
    delta = current - previous
    delta_str = _format_delta_int(int(delta)) if isinstance(current, int) else f"{delta:+.2f}"
    pct_str = _format_delta_pct(current, previous)
    if pct_str:
        return f"{delta_str} {pct_str}".strip()
    return delta_str


def _short_id(
    full_id: str,
    length: int = 12,
) -> str:
    """Truncate a UUID to its first N chars + ellipsis."""
    if not full_id:
        return ""
    return f"{full_id[:length]}..."


def _read_json(
    path: str,
) -> dict:
    """Read a JSON file, returning empty dict if missing."""
    if not os.path.exists(path):
        logger.warning(f"File not found: {path}")
        return {}
    with open(path) as f:
        return json.load(f)


def _read_active_instances_csv(
    path: str,
) -> list[dict]:
    """Read active-instances CSV, return list of row dicts."""
    if not os.path.exists(path):
        return []
    with open(path) as f:
        return list(csv.DictReader(f))


def _count_reporters_on_day(
    csv_path: str,
    day: str,
    internal_ids: set[str],
) -> int:
    """Count unique customer registry instances that sent any event on a day.

    Reads the raw registry_metrics.csv and counts distinct registry_id values
    whose `ts` falls on the given day, excluding known-internal instances. Used
    for the report-day reporter count in the executive summary. The report day
    is typically in-progress at export time, so this is a partial-day figure.
    """
    if not os.path.exists(csv_path):
        return 0

    reporters = set()
    with open(csv_path) as f:
        for row in csv.DictReader(f):
            registry_id = row.get("registry_id") or ""
            if not registry_id or registry_id in internal_ids:
                continue
            if (row.get("ts") or "")[:10] == day:
                reporters.add(registry_id)

    return len(reporters)


def _read_lifetime_buckets_csv(
    path: str,
) -> list[dict]:
    """Read lifetime-buckets CSV. Each row has date + per-threshold pct columns."""
    if not os.path.exists(path):
        return []
    with open(path) as f:
        return list(csv.DictReader(f))


def _build_cloud_installs_table(
    metrics: dict,
    prev_metrics: dict,
) -> str:
    """Render the lifetime cloud-installs comparison table.

    Returns a markdown table string identical to what analyze_telemetry's
    tables-*.md produces but built straight from per_cloud_unique_installs.
    """
    current = metrics.get("per_cloud_unique_installs", {})
    previous = prev_metrics.get("per_cloud_unique_installs", {}) if prev_metrics else {}

    last_seen_per_cloud = _last_seen_per_cloud_from_metrics(metrics)

    lines = [
        "| Cloud Provider | Previous | Current | Change | Last Startup | Last Heartbeat |",
        "|----------------|---------:|--------:|-------:|--------------|----------------|",
    ]
    for cloud in sorted(current.keys()):
        cur = current.get(cloud, 0)
        prev = previous.get(cloud, 0) if prev_metrics else 0
        delta = _format_combined_delta(cur, prev)
        last_startup = last_seen_per_cloud.get(cloud, {}).get("last_startup", "n/a")
        last_heartbeat = last_seen_per_cloud.get(cloud, {}).get("last_heartbeat", "n/a")
        lines.append(f"| {cloud} | {prev} | {cur} | {delta} | {last_startup} | {last_heartbeat} |")
    return "\n".join(lines)


def _last_seen_per_cloud_from_metrics(
    metrics: dict,
) -> dict[str, dict[str, str]]:
    """Walk identified_instances and compute last startup/heartbeat date per cloud."""
    out: dict[str, dict[str, str]] = {}
    for inst in metrics.get("identified_instances", []):
        cloud = inst.get("cloud") or "unknown"
        latest = inst.get("latest_seen", "")[:10]
        first = inst.get("first_seen", "")[:10]
        if cloud not in out:
            out[cloud] = {"last_startup": first, "last_heartbeat": latest}
        else:
            if first > out[cloud]["last_startup"]:
                out[cloud]["last_startup"] = first
            if latest > out[cloud]["last_heartbeat"]:
                out[cloud]["last_heartbeat"] = latest
    return out


def _build_engagement_table(
    active_csv_rows: list[dict],
    n_recent: int = 3,
) -> str:
    """Render the recent-days DAI table."""
    if not active_csv_rows:
        return "| (no data) | | | | | | |"
    last_n = active_csv_rows[-n_recent:]
    lines = []
    for row in last_n:
        # Column names from generate_active_instances_chart.py:
        # date, daily_active, ma7, streak7, cumulative_installs,
        # dai_pct_of_total, likely_alive_7d, dai_pct_of_likely_alive
        lines.append(
            f"| {row['date']} | {row['daily_active']} | {row['ma7']} | "
            f"{row['streak7']} | {row['cumulative_installs']} | "
            f"{row['dai_pct_of_total']}% | {row['dai_pct_of_likely_alive']}% |"
        )
    return "\n".join(lines)


def _semver_sort_key(
    version: str,
) -> tuple[int, int, int]:
    """Parse a version string into a (major, minor, patch) tuple for sorting.

    Strips a leading "v" and any "-..." suffix (git-describe, branch, -pN),
    then splits on ".". Non-numeric or non-semver strings (commit hashes,
    "dev") yield (0, 0, 0) so they sort to the bottom in descending order.
    """
    core = version.lstrip("v").split("-")[0]
    parts = core.split(".")
    nums = [int(p) if p.isdigit() else 0 for p in parts[:3]]
    while len(nums) < 3:
        nums.append(0)
    return (nums[0], nums[1], nums[2])


def _build_version_adoption_table(
    metrics: dict,
    top_n: int = 15,
) -> str:
    """Render the version-adoption table from metrics.version_adoption.

    Selects the top N versions (by the metric's existing order, i.e. events),
    then displays them sorted by semantic version descending.
    """
    rows = metrics.get("version_adoption", [])[:top_n]
    if not rows:
        return "| (no data) | | | | | |"
    rows = sorted(rows, key=lambda r: _semver_sort_key(r["version"]), reverse=True)
    lines = [
        "| Version | Type | Events | % Events | Instances | % Instances |",
        "|---------|------|-------:|---------:|----------:|------------:|",
    ]
    for r in rows:
        lines.append(
            f"| `{r['version']}` | {r['type'].title()} | {r['events']:,} | "
            f"{r['percentage']} | {r['instances']} | {r['instance_percentage']} |"
        )
    return "\n".join(lines)


def _build_upgrade_trajectories_table(
    metrics: dict,
    top_n: int = 10,
) -> str:
    """Render the upgrade-trajectories table from metrics.upgrade_trajectories."""
    rows = metrics.get("upgrade_trajectories", [])[:top_n]
    if not rows:
        return "| (no data) | | | |"

    # Build a registry_id -> profile map from identified_instances
    profile = {}
    for inst in metrics.get("identified_instances", []):
        rid = inst.get("registry_id_full") or inst.get("registry_id", "")
        cloud = inst.get("cloud", "?")
        compute = inst.get("compute", "?")
        auth = inst.get("auth", "?")
        profile[rid] = f"{cloud}/{compute}/{auth}"

    lines = [
        "| Registry ID | Cloud/Compute/Auth | Changes | Trajectory |",
        "|-------------|-------------------|--------:|------------|",
    ]
    for r in rows:
        rid = r.get("registry_id_full") or r.get("registry_id", "")
        prof = profile.get(rid, "?")
        traj = " -> ".join(r.get("trajectory", []))
        # Truncate very long trajectories
        if len(traj) > 150:
            parts = r.get("trajectory", [])
            traj = f"{parts[0]} -> ... -> {parts[-1]}"
        lines.append(
            f"| `{r.get('registry_id', '')[:12]}...` | {prof} | {r['version_changes']} | {traj} |"
        )
    return "\n".join(lines)


def _build_feature_adoption_table(
    metrics: dict,
) -> str:
    """Render feature_adoption from metrics.feature_adoption."""
    rows = metrics.get("feature_adoption", [])
    if not rows:
        return "| (no data) | | |"
    lines = [
        "| Feature | Enabled | Rate |",
        "|---------|--------:|-----:|",
    ]
    for r in rows:
        lines.append(f"| {r['feature']} | {r['enabled']:,} | {r['rate']} |")
    return "\n".join(lines)


def _build_embeddings_backend_table(
    metrics: dict,
) -> str:
    """Render embeddings_backend_breakdown from metrics."""
    rows = metrics.get("embeddings_backend_breakdown", [])
    if not rows:
        return "| (no data) | | |"
    lines = [
        "| Backend Kind | Unique Instances | % of Fleet |",
        "|--------------|-----------------:|-----------:|",
    ]
    for r in rows:
        kind = r["kind"] if r["kind"] != "unknown" else "`unknown` (pre-v1.0.22)"
        if r["kind"] != "unknown":
            kind = f"`{r['kind']}`"
        lines.append(f"| {kind} | {r['instances']} | {r['percentage']} |")
    return "\n".join(lines)


def _build_sticky_cloud_compute_table(
    metrics: dict,
    prev_metrics: dict,
) -> str:
    """Render the sticky breakdown by cloud + compute."""
    current = metrics.get("sticky_cloud_compute", {})
    previous = prev_metrics.get("sticky_cloud_compute", {}) if prev_metrics else {}

    if not current:
        return "| (no data) | | | | |"

    total = sum(current.values()) or 1
    lines = [
        "| Cloud | Compute | Instances | % | Change vs Previous |",
        "|-------|---------|----------:|---|-------------------:|",
    ]
    # Sort by count descending
    for key, count in sorted(current.items(), key=lambda x: -x[1]):
        cloud, compute = key.split("/", 1)
        prev_count = previous.get(key, 0)
        delta = count - prev_count
        delta_str = _format_delta_int(delta) if delta != 0 else "0"
        pct = count / total * 100
        lines.append(f"| {cloud} | {compute} | {count} | {pct:.0f}% | {delta_str} |")
    return "\n".join(lines)


def _read_section_from_tables_md(
    path: str,
    section_header: str,
) -> str:
    """Extract a markdown section (between `## section_header` and the next `## `)."""
    if not os.path.exists(path):
        return f"(tables file not found at {path})"
    with open(path) as f:
        content = f.read()

    pattern = re.compile(
        rf"##\s+{re.escape(section_header)}.*?\n(.*?)(?=\n##\s+|\Z)",
        re.DOTALL,
    )
    match = pattern.search(content)
    if not match:
        return f"(section '{section_header}' not found in tables file)"
    return match.group(1).strip()


def _build_detection_by_version_narrative(
    csv_path: str,
) -> str:
    """Render a data-driven narrative about cloud_detection_method by version.

    Reads the detection-by-version CSV (which has columns: version, env, dmi,
    ecs_meta, k8s_heuristic, imds, unknown, (field absent), total). Picks the
    two newest non-dev release versions and the two oldest (still in top N),
    and builds a comparison sentence based on actual green/red/grey shares.
    """
    if not os.path.exists(csv_path):
        return "_Detection-by-version data not available for narrative._"

    with open(csv_path) as f:
        rows = list(csv.DictReader(f))

    if not rows:
        return "_Detection-by-version data is empty._"

    GREEN = ("env", "dmi", "ecs_meta", "k8s_heuristic", "imds")
    RED = "unknown"
    GREY = "(field absent)"

    def _share(row: dict, methods: tuple[str, ...] | str) -> float:
        total = int(row.get("total", 0)) or 1
        if isinstance(methods, str):
            return int(row.get(methods, 0)) / total * 100
        return sum(int(row.get(m, 0)) for m in methods) / total * 100

    # Identify "release" versions (skip the "other" rollup, dev branches, sha-only refs)
    is_release_re = re.compile(r"^v?\d+\.\d+\.\d+(?:-p\d+)?$")
    releases = [
        r for r in rows if is_release_re.match(r.get("version", "")) and int(r.get("total", 0)) >= 5
    ]

    if not releases:
        return "_No release-version rows with sufficient sample size for narrative._"

    # Sort releases descending: newest version strings last
    def _version_key(v: str) -> tuple:
        v = v.lstrip("v").split("-")[0]
        parts = v.split(".")
        return tuple(int(p) if p.isdigit() else 0 for p in parts)

    releases.sort(key=lambda r: _version_key(r["version"]))
    newest = releases[-2:]
    oldest = releases[:2]

    parts = []
    for row in reversed(newest):
        green_pct = _share(row, GREEN)
        red_pct = _share(row, RED)
        v = row["version"]
        n = row["total"]
        parts.append(
            f"`{v}` (n={n}): {green_pct:.0f}% successful detection (env, dmi, ecs_meta, k8s_heuristic, imds), "
            f"{red_pct:.0f}% unknown."
        )

    if oldest and oldest[0]["version"] != newest[-1]["version"]:
        oldest_release = oldest[0]
        red_pct = _share(oldest_release, RED)
        grey_pct = _share(oldest_release, GREY)
        v = oldest_release["version"]
        n = oldest_release["total"]
        parts.append(
            f"For comparison, the oldest tracked release `{v}` (n={n}) has "
            f"{red_pct:.0f}% unknown and {grey_pct:.0f}% field-absent. The "
            f"unknown share is dominated by the EKS+Helm gap that #1093 / PR #1106 "
            f"closed in 1.24.2; field-absent represents pre-1.23.0 instances that "
            f"never emit `cloud_detection_method`."
        )
    return " ".join(parts)


def _build_architecture_patterns(
    metrics: dict,
    liveness: dict,
) -> str:
    """Generate architecture-pattern bullets from data.

    Looks at:
      - longest-running customer profile
      - top Most-Active profile (search-heavy)
      - top Largest-Catalog profile (catalog-heavy)
      - top upgrade-trajectory profile (release-tracking)
      - smallest cloud cohort with sticky representation (GCP/Azure surprising survivor)
    """
    bullets = []

    instances = metrics.get("identified_instances", [])
    internal_ids = set(metrics.get("internal_instance_ids", []))
    customers = [
        i
        for i in instances
        if (i.get("registry_id_full") or i.get("registry_id", "")) not in internal_ids
    ]
    # Index by both truncated and full IDs since stickiness.longest_non_internal_id
    # is stored as the truncated form
    by_id = {}
    for i in customers:
        full_id = i.get("registry_id_full", "")
        short_id = i.get("registry_id", "")
        if full_id:
            by_id[full_id] = i
        if short_id:
            by_id[short_id] = i

    # 1. Longest-running profile
    stickiness = metrics.get("stickiness", {})
    longest_id = stickiness.get("longest_non_internal_id", "")
    longest_days = stickiness.get("longest_non_internal_days", 0)
    if longest_id and longest_id in by_id:
        inst = by_id[longest_id]
        bullets.append(
            f"**{inst['cloud'].upper()} / {inst['compute']} / {inst['auth']} long-running stack.** "
            f"`{longest_id}` is the longest-running non-internal instance at "
            f"{longest_days} days. Customer-story candidate."
        )

    # 2. Most active (highest activity score = max_servers + max_agents + max_skills + total_search_queries)
    def _activity_score(i):
        return (
            i.get("max_servers", 0)
            + i.get("max_agents", 0)
            + i.get("max_skills", 0)
            + i.get("total_search_queries", 0)
        )

    if customers:
        most_active = max(customers, key=_activity_score)
        bullets.append(
            f"**{most_active['cloud'].upper()} / {most_active['compute']} / {most_active['auth']} most-active stack.** "
            f"`{most_active.get('registry_id', '')[:12]}...` (version `{most_active.get('version', '?')}`) "
            f"leads the Most Active table with {most_active.get('total_search_queries', 0):,} lifetime search queries."
        )

    # 3. Largest catalog
    def _catalog_score(i):
        return i.get("max_servers", 0) + i.get("max_agents", 0) + i.get("max_skills", 0)

    if customers:
        largest = max(customers, key=_catalog_score)
        score = _catalog_score(largest)
        if score > 0:
            bullets.append(
                f"**{largest['cloud'].upper()} / {largest['compute']} / {largest['auth']} catalog-heavy stack.** "
                f"`{largest.get('registry_id', '')[:12]}...` leads with {score:,} "
                f"registered objects (servers + agents + skills)."
            )

    # 4. Most engaged operator (longest upgrade chain)
    trajectories = metrics.get("upgrade_trajectories", [])
    if trajectories:
        top_traj = trajectories[0]
        # Try full id first, fall back to short id (both are indexed in by_id)
        rid_full = top_traj.get("registry_id_full", "")
        rid_short = top_traj.get("registry_id", "")
        inst = by_id.get(rid_full) or by_id.get(rid_short)
        if inst:
            bullets.append(
                f"**{inst['cloud'].upper()} / {inst['compute']} / {inst['auth']} upgrade-ladder stack.** "
                f"`{rid_short}` has tracked "
                f"{top_traj.get('version_changes', 0)} version changes, the deepest upgrade chain in the fleet."
            )

    # 5. Surprising survivor: longest-running customer NOT on AWS
    non_aws = [c for c in customers if c.get("cloud") not in ("aws", "unknown")]
    if non_aws:
        longest_non_aws = max(non_aws, key=lambda i: i.get("events", 0))
        bullets.append(
            f"**{longest_non_aws['cloud'].upper()} / {longest_non_aws['compute']} / {longest_non_aws['auth']} surprising survivor.** "
            f"`{longest_non_aws.get('registry_id', '')[:12]}...` represents the largest non-AWS cohort. "
            f"Disproportionately sticky for the smallest cloud segments."
        )

    return "\n".join(f"{i + 1}. {b}" for i, b in enumerate(bullets))


def _read_compute_snapshots(
    path: str,
    top_n: int = 10,
) -> str:
    """Read the per-platform-snapshots markdown file and return its table.

    Trims to the top N most recent snapshots after the bolded current row.
    """
    if not os.path.exists(path):
        return "(compute-platform-snapshots file not found)"
    with open(path) as f:
        content = f.read()
    # The file is just a table; return it as-is, trimmed
    lines = content.splitlines()
    if len(lines) <= top_n + 2:
        return content
    # Keep header (2 lines) + bolded current row + top N other rows
    return "\n".join(lines[: top_n + 3])


def _build_prod_internal_version_table(
    prod_internal: dict,
    class_key: str,
    top_n: int = 15,
) -> str:
    """Render a per-version instance-count table for one class.

    class_key is "community" or "internal". Rows beyond top_n are folded
    into a single "(N more versions)" summary row so the table stays short.
    """
    rows = prod_internal.get("per_version", {}).get(class_key, [])
    if not rows:
        return "| (no data) | |"

    lines = [
        "| Version | Instances |",
        "|---------|----------:|",
    ]
    for r in rows[:top_n]:
        lines.append(f"| `{r['version']}` | {r['instances']} |")

    remaining = rows[top_n:]
    if remaining:
        other_instances = sum(r["instances"] for r in remaining)
        noun = "version" if len(remaining) == 1 else "versions"
        lines.append(f"| _({len(remaining)} more {noun})_ | {other_instances} |")
    return "\n".join(lines)


def _build_template_vars(
    args: argparse.Namespace,
) -> dict:
    """Assemble the full dict of template substitution values."""
    date_str = args.date
    output_dir = Path(args.output_dir)
    search_dir = args.search_dir or str(output_dir.parent)

    # Load all the structured outputs
    metrics_path = output_dir / f"metrics-{date_str}.json"
    liveness_path = output_dir / f"liveness-{date_str}.json"
    ltv_path = output_dir / f"ltv-spend-{date_str}.json"
    forecast_path = output_dir / f"install-forecast-{date_str}.json"
    github_path = output_dir / "github_stats.json"
    contributors_path = output_dir / "github_contributors_count.txt"
    active_csv_path = output_dir / f"active-instances-{date_str}.csv"
    lifetime_buckets_csv_path = output_dir / f"lifetime-buckets-{date_str}.csv"
    compute_snapshots_path = output_dir / f"compute-platform-snapshots-{date_str}.md"
    tables_md_path = output_dir / f"tables-{date_str}.md"
    prod_internal_path = output_dir / f"prod-internal-{date_str}.json"

    metrics = _read_json(str(metrics_path))
    liveness = _read_json(str(liveness_path))
    ltv = _read_json(str(ltv_path))
    forecast = _read_json(str(forecast_path))
    github = _read_json(str(github_path))
    prod_internal = _read_json(str(prod_internal_path)) if prod_internal_path.exists() else {}

    # Previous report
    prev_metrics_path = _find_previous_metrics(search_dir, date_str)
    prev_metrics = _read_json(prev_metrics_path) if prev_metrics_path else {}
    prev_liveness_path = _find_previous_liveness(search_dir, date_str)
    prev_liveness = _read_json(prev_liveness_path) if prev_liveness_path else {}
    prev_github_path = _find_previous_github_stats(search_dir, date_str)
    prev_github = _read_json(prev_github_path) if prev_github_path else {}

    prev_date = ""
    if prev_metrics_path:
        prev_date = prev_metrics_path.split("/metrics-")[1].replace(".json", "")

    # Contributors
    github_contributors = 0
    if contributors_path.exists():
        github_contributors = int(contributors_path.read_text().strip())

    # Engagement CSV
    active_rows = _read_active_instances_csv(str(active_csv_path))

    # Lifetime buckets CSV (for retention-over-time table)
    lifetime_rows = _read_lifetime_buckets_csv(str(lifetime_buckets_csv_path))

    # ===== Compute all the variables =====

    km = metrics.get("key_metrics", {})
    stickiness = metrics.get("stickiness", {})
    counts = liveness.get("counts", {})
    customer_total = counts.get("customer_total", stickiness.get("total_non_internal", 0))
    internal_count = len(metrics.get("internal_instance_ids", []))
    total_instances = km.get("identified_instances", 0)

    # Lifetime bucket retention deltas
    earliest_pct = lifetime_rows[0] if lifetime_rows else {}
    latest_pct = lifetime_rows[-1] if lifetime_rows else {}

    def _pct_change_str(curr_key: str, earliest_key: str) -> str:
        try:
            curr = float(latest_pct.get(curr_key, 0))
            earliest = float(earliest_pct.get(earliest_key, 0))
            return f"+{curr - earliest:.1f}pp"
        except (ValueError, TypeError):
            return "n/a"

    # Lifetime stats
    lifetime_list = metrics.get("instance_lifetime", [])
    customer_lifetimes = [
        i["age_days"]
        for i in lifetime_list
        if i.get("registry_id_full", i.get("registry_id", ""))
        not in metrics.get("internal_instance_ids", [])
    ]
    avg_lifetime = (
        (sum(customer_lifetimes) / len(customer_lifetimes)) if customer_lifetimes else 0.0
    )
    multi_day = sum(1 for d in customer_lifetimes if d > 0)
    multi_day_pct = (multi_day / len(customer_lifetimes) * 100) if customer_lifetimes else 0

    # Longest non-internal profile
    longest_id = stickiness.get("longest_non_internal_id", "")
    longest_profile = "?"
    for inst in metrics.get("identified_instances", []):
        if (
            inst.get("registry_id_full") == longest_id
            or inst.get("registry_id") == longest_id[:12] + "..."
        ):
            longest_profile = f"{inst['cloud']}/{inst['compute']}/{inst['auth']}"
            break
        # Also try registry_id (truncated form)
        if inst.get("registry_id", "").startswith(longest_id[:8]):
            longest_profile = f"{inst['cloud']}/{inst['compute']}/{inst['auth']}"
            break

    # LTV
    ltv_yesterday = ltv.get("yesterday", {})
    ltv_last_7d = ltv.get("last_7_days", {})
    ltv_total = ltv.get("ltv", {})

    proven_7d = ltv_last_7d.get("proven_total_usd", 0)
    all_days_7d = ltv_last_7d.get("all_days_total_usd", 0)
    persisted_7d = ltv_last_7d.get("persisted_total_usd", 0)
    proven_avg = proven_7d / 7 if proven_7d else 0
    all_days_avg = all_days_7d / 7 if all_days_7d else 0
    persisted_avg = persisted_7d / 7 if persisted_7d else 0
    arr_proven = (proven_avg * 365) / 1_000_000
    arr_all_days = (all_days_avg * 365) / 1_000_000
    arr_persisted = (persisted_avg * 365) / 1_000_000

    # Instance-day decomposition for the formula-clarification block. The three
    # rules differ only in which (instance, day) pairs they count; the per-day
    # rate is identical. all-days >= persisted >= proven, and the two gaps are:
    #   all-days - persisted = single-calendar-day (install-and-vanish) days
    #   persisted - proven   = exactly one free first-day per persisted instance
    id_all_days = ltv_total.get("all_days", {}).get("total_instance_days", 0)
    id_persisted = ltv_total.get("persisted", {}).get("total_instance_days", 0)
    id_proven = ltv_total.get("proven", {}).get("total_instance_days", 0)
    gap_install_vanish_days = id_all_days - id_persisted
    gap_first_free_days = id_persisted - id_proven

    # Community vs internal (by version-string classification)
    pi_yesterday = prod_internal.get("yesterday", {})
    pi_cumulative = prod_internal.get("cumulative", {})
    pi_yesterday_date = prod_internal.get("yesterday_date", prev_date)
    pi_y_prod = pi_yesterday.get("community", 0)
    pi_y_internal = pi_yesterday.get("internal", 0)
    pi_y_total = pi_yesterday.get("total", 0)
    pi_c_prod = pi_cumulative.get("community", 0)
    pi_c_internal = pi_cumulative.get("internal", 0)
    pi_c_total = pi_cumulative.get("total", 0)
    pi_y_prod_pct = f"{(pi_y_prod / pi_y_total * 100):.1f}" if pi_y_total else "0.0"
    pi_y_internal_pct = f"{(pi_y_internal / pi_y_total * 100):.1f}" if pi_y_total else "0.0"
    pi_c_prod_pct = f"{(pi_c_prod / pi_c_total * 100):.1f}" if pi_c_total else "0.0"
    pi_c_internal_pct = f"{(pi_c_internal / pi_c_total * 100):.1f}" if pi_c_total else "0.0"

    # Forecast
    fc_linear = forecast.get("linear", {})
    fc_recent = forecast.get("recent_pace", {})

    # Forecast narrative (deterministic)
    linear_eta = fc_linear.get("eta", "?")
    recent_eta = fc_recent.get("eta", "?")
    linear_rate = fc_linear.get("slope_per_day", 0)
    recent_rate = fc_recent.get("daily_add_rate", 0)
    today_count = forecast.get("today", {}).get("installs", total_instances)
    target = forecast.get("target", 2000)
    remaining = target - today_count
    if recent_rate > linear_rate:
        forecast_narrative = (
            f"Recent pace is ahead of the 14-day OLS slope, indicating sustained acceleration. "
            f"**{remaining} installs from the {target:,}-install milestone.**"
        )
    elif recent_rate < linear_rate * 0.85:
        forecast_narrative = (
            f"Recent pace is behind the 14-day OLS slope, indicating a slowdown. "
            f"**{remaining} installs from the {target:,}-install milestone.**"
        )
    else:
        forecast_narrative = (
            f"Recent pace and 14-day OLS are converged. "
            f"**{remaining} installs from the {target:,}-install milestone.**"
        )

    # ===== One-day-wonder trend =====
    odw_pct = stickiness.get("one_day_wonder_pct", 0)
    prev_odw_pct = (
        prev_metrics.get("stickiness", {}).get("one_day_wonder_pct", odw_pct)
        if prev_metrics
        else odw_pct
    )
    if odw_pct < prev_odw_pct:
        one_day_wonder_trend = (
            f"Down from {prev_odw_pct:.1f}% in the previous report (retention strengthening)."
        )
    elif odw_pct > prev_odw_pct:
        one_day_wonder_trend = f"Up from {prev_odw_pct:.1f}% (acquisition outpacing aging-in)."
    else:
        one_day_wonder_trend = f"Unchanged from {prev_odw_pct:.1f}%."

    # ===== Executive summary lead =====
    sticky_now = stickiness.get("sticky_3plus_days", 0)
    prev_sticky = (
        prev_metrics.get("stickiness", {}).get("sticky_3plus_days", 0) if prev_metrics else 0
    )
    confirmed_now = counts.get("confirmed", 0)
    prev_confirmed = prev_liveness.get("counts", {}).get("confirmed", 0) if prev_liveness else 0
    instance_delta = (
        total_instances
        - prev_metrics.get("key_metrics", {}).get("identified_instances", total_instances)
        if prev_metrics
        else 0
    )

    # Customer instances that reported on the last complete day (report date - 1).
    # The report day itself is usually in-progress at export time, so we use the
    # previous calendar day to cover a full 24-hour window.
    last_complete_day = _previous_date(date_str)
    report_day_reporters = _count_reporters_on_day(
        str(output_dir / f"registry_metrics-{date_str}.csv")
        if (output_dir / f"registry_metrics-{date_str}.csv").exists()
        else str(output_dir / "registry_metrics.csv"),
        last_complete_day,
        set(metrics.get("internal_instance_ids", [])),
    )

    exec_lead_parts = []
    if instance_delta > 0:
        exec_lead_parts.append(
            f"{instance_delta} new install{'s' if instance_delta != 1 else ''} since the previous report."
        )
    if confirmed_now > prev_confirmed:
        exec_lead_parts.append(f"Confirmed Alive moved from {prev_confirmed} to {confirmed_now}.")
    elif confirmed_now == prev_confirmed and confirmed_now > 0:
        exec_lead_parts.append(f"Confirmed Alive holds steady at {confirmed_now}.")
    if report_day_reporters > 0:
        exec_lead_parts.append(
            f"**{report_day_reporters} customer instances reported in on {last_complete_day} "
            f"(last complete day).**"
        )
    executive_summary_lead = " ".join(exec_lead_parts) or "No major shifts since the last report."

    # ===== Build the variable dict =====

    vars_ = {
        # Dates
        "date": date_str,
        "report_date": date_str,
        "prev_date": _previous_date(date_str),
        "prev_report_date": prev_date or "(none)",
        "collection_period_start": km.get("earliest_ts", "")[:10],
        "collection_period_end": km.get("latest_ts", "")[:10],
        "collection_period_days": _days_between(
            km.get("earliest_ts", "")[:10], km.get("latest_ts", "")[:10]
        ),
        # Headline counts
        "total_events": f"{km.get('total_events', 0):,}",
        "startup_events": f"{km.get('startup_events', 0):,}",
        "heartbeat_events": f"{km.get('heartbeat_events', 0):,}",
        "total_instances": total_instances,
        "internal_instances": internal_count,
        "customer_instances": customer_total,
        # Stickiness
        "sticky_3plus_days": sticky_now,
        "one_day_wonders": stickiness.get("one_day_wonders", 0),
        "one_day_wonder_pct_str": f"{odw_pct:.1f}",
        "one_day_wonder_trend": one_day_wonder_trend,
        "longest_non_internal_id_short": _short_id(longest_id),
        "longest_non_internal_days": stickiness.get("longest_non_internal_days", 0),
        "longest_non_internal_profile": longest_profile,
        "avg_lifetime_days": f"{avg_lifetime:.1f}",
        "multi_day_customers": multi_day,
        "multi_day_pct_str": f"{multi_day_pct:.1f}",
        # Liveness
        "confirmed_alive": counts.get("confirmed", 0),
        "stronger_alive": counts.get("stronger", 0),
        "likely_alive": counts.get("likely", 0),
        "silent_but_recent": counts.get("silent_but_recent", 0),
        "dormant": counts.get("dormant", 0),
        "confirmed_alive_pct": f"{counts.get('confirmed', 0) / customer_total * 100:.1f}"
        if customer_total
        else "0.0",
        "stronger_alive_pct": f"{counts.get('stronger', 0) / customer_total * 100:.1f}"
        if customer_total
        else "0.0",
        "likely_alive_pct": f"{counts.get('likely', 0) / customer_total * 100:.1f}"
        if customer_total
        else "0.0",
        "silent_but_recent_pct": f"{counts.get('silent_but_recent', 0) / customer_total * 100:.1f}"
        if customer_total
        else "0.0",
        "dormant_pct": f"{counts.get('dormant', 0) / customer_total * 100:.1f}"
        if customer_total
        else "0.0",
        # Adoption funnel counts (cumulative thresholds)
        "weekly_count": stickiness.get("lifetime_bucket_counts", {}).get("7", 0),
        "biweekly_count": stickiness.get("lifetime_bucket_counts", {}).get("14", 0),
        "monthly_count": stickiness.get("lifetime_bucket_counts", {}).get("30", 0),
        "pct_3d": f"{stickiness.get('lifetime_bucket_pct', {}).get('3', 0):.1f}",
        "pct_7d": f"{stickiness.get('lifetime_bucket_pct', {}).get('7', 0):.1f}",
        "pct_14d": f"{stickiness.get('lifetime_bucket_pct', {}).get('14', 0):.1f}",
        "pct_30d": f"{stickiness.get('lifetime_bucket_pct', {}).get('30', 0):.1f}",
        # Lifetime retention over time
        "earliest_snapshot_date": earliest_pct.get("date", "(unknown)"),
        "earliest_pct_3d": f"{float(earliest_pct.get('pct_ge_3d', 0)):.1f}",
        "earliest_pct_7d": f"{float(earliest_pct.get('pct_ge_7d', 0)):.1f}",
        "earliest_pct_14d": f"{float(earliest_pct.get('pct_ge_14d', 0)):.1f}",
        "earliest_pct_30d": f"{float(earliest_pct.get('pct_ge_30d', 0)):.1f}",
        "earliest_pct_odw": f"{float(earliest_pct.get('one_day_wonder_pct', 0)):.0f}",
        "pct_3d_change_str": _pct_change_str("pct_ge_3d", "pct_ge_3d"),
        "pct_7d_change_str": _pct_change_str("pct_ge_7d", "pct_ge_7d"),
        "pct_14d_change_str": _pct_change_str("pct_ge_14d", "pct_ge_14d"),
        "pct_30d_change_str": _pct_change_str("pct_ge_30d", "pct_ge_30d"),
        "pct_odw_change_str": _pct_change_str("one_day_wonder_pct", "one_day_wonder_pct"),
        # Search
        "search_active_instances": metrics.get("search_stats", {}).get("instances_with_search", 0),
        "search_total_queries": f"{metrics.get('search_stats', {}).get('lifetime_sum', 0):,}",
        "search_avg_per_instance": f"{metrics.get('search_stats', {}).get('lifetime_avg', 0):.1f}",
        "search_max_single_instance": f"{metrics.get('search_stats', {}).get('lifetime_max', 0):,}",
        # Forecast
        "forecast_linear_rate": f"{linear_rate:.1f}",
        "forecast_linear_eta": linear_eta,
        "forecast_recent_rate": f"{recent_rate:.1f}",
        "forecast_recent_eta": recent_eta,
        "forecast_target": f"{target:,}",
        "forecast_narrative": forecast_narrative,
        # LTV
        "yesterday_label": ltv_yesterday.get("date", "?"),
        "ltv_yesterday_proven": f"${ltv_yesterday.get('proven', {}).get('total_usd', 0):,.2f}",
        "ltv_yesterday_all_days": f"${ltv_yesterday.get('all_days', {}).get('total_usd', 0):,.2f}",
        "ltv_yesterday_persisted": f"${ltv_yesterday.get('persisted', {}).get('total_usd', 0):,.2f}",
        "ltv_last_7_days_proven": f"${proven_7d:,.2f}",
        "ltv_last_7_days_all_days": f"${all_days_7d:,.2f}",
        "ltv_last_7_days_persisted": f"${persisted_7d:,.2f}",
        "ltv_7day_daily_avg_proven": f"${proven_avg:,.2f}",
        "ltv_7day_daily_avg_all_days": f"${all_days_avg:,.2f}",
        "ltv_7day_daily_avg_persisted": f"${persisted_avg:,.2f}",
        "ltv_cumulative_proven": f"${ltv_total.get('proven', {}).get('total_usd', 0):,.0f}",
        "ltv_cumulative_all_days": f"${ltv_total.get('all_days', {}).get('total_usd', 0):,.0f}",
        "ltv_cumulative_persisted": f"${ltv_total.get('persisted', {}).get('total_usd', 0):,.0f}",
        "arr_proven_str": f"${arr_proven:.2f}M",
        "arr_all_days_str": f"${arr_all_days:.2f}M",
        "arr_persisted_str": f"${arr_persisted:.2f}M",
        "ltv_instance_days_all_days": f"{id_all_days:,}",
        "ltv_instance_days_persisted": f"{id_persisted:,}",
        "ltv_instance_days_proven": f"{id_proven:,}",
        "ltv_gap_install_vanish_days": f"{gap_install_vanish_days:,}",
        "ltv_gap_first_free_days": f"{gap_first_free_days:,}",
        # Comparison-with-previous
        "prev_total_events": f"{prev_metrics.get('key_metrics', {}).get('total_events', 0):,}",
        "prev_startup_events": f"{prev_metrics.get('key_metrics', {}).get('startup_events', 0):,}",
        "prev_heartbeat_events": f"{prev_metrics.get('key_metrics', {}).get('heartbeat_events', 0):,}",
        "prev_total_instances": prev_metrics.get("key_metrics", {}).get("identified_instances", 0),
        "prev_sticky_3plus_days": prev_sticky,
        "prev_confirmed_alive": prev_confirmed,
        "prev_stronger_alive": prev_liveness.get("counts", {}).get("stronger", 0)
        if prev_liveness
        else 0,
        "prev_likely_alive": prev_liveness.get("counts", {}).get("likely", 0)
        if prev_liveness
        else 0,
        "prev_silent_but_recent": prev_liveness.get("counts", {}).get("silent_but_recent", 0)
        if prev_liveness
        else 0,
        "prev_dormant": prev_liveness.get("counts", {}).get("dormant", 0) if prev_liveness else 0,
        "total_events_delta_str": _format_combined_delta(
            km.get("total_events", 0),
            prev_metrics.get("key_metrics", {}).get("total_events", 0),
        )
        if prev_metrics
        else "(no prior)",
        "startup_events_delta_str": _format_combined_delta(
            km.get("startup_events", 0),
            prev_metrics.get("key_metrics", {}).get("startup_events", 0),
        )
        if prev_metrics
        else "(no prior)",
        "heartbeat_events_delta_str": _format_combined_delta(
            km.get("heartbeat_events", 0),
            prev_metrics.get("key_metrics", {}).get("heartbeat_events", 0),
        )
        if prev_metrics
        else "(no prior)",
        "total_instances_delta_str": _format_combined_delta(
            total_instances,
            prev_metrics.get("key_metrics", {}).get("identified_instances", 0),
        )
        if prev_metrics
        else "(no prior)",
        "sticky_delta_str": _format_delta_int(sticky_now - prev_sticky),
        "confirmed_alive_delta_str": _format_delta_int(counts.get("confirmed", 0) - prev_confirmed),
        "stronger_alive_delta_str": _format_delta_int(
            counts.get("stronger", 0)
            - (prev_liveness.get("counts", {}).get("stronger", 0) if prev_liveness else 0)
        ),
        "likely_alive_delta_str": _format_delta_int(
            counts.get("likely", 0)
            - (prev_liveness.get("counts", {}).get("likely", 0) if prev_liveness else 0)
        ),
        "silent_but_recent_delta_str": _format_delta_int(
            counts.get("silent_but_recent", 0)
            - (prev_liveness.get("counts", {}).get("silent_but_recent", 0) if prev_liveness else 0)
        ),
        "dormant_delta_str": _format_delta_int(
            counts.get("dormant", 0)
            - (prev_liveness.get("counts", {}).get("dormant", 0) if prev_liveness else 0)
        ),
        # GitHub
        "github_stars": github.get("stars", 0),
        "github_forks": github.get("forks", 0),
        "github_watchers": github.get("watchers", 0),
        "github_open_issues": github.get("open_issues", 0),
        "github_contributors": github_contributors,
        "prev_github_stars": prev_github.get("stars", 0),
        "prev_github_forks": prev_github.get("forks", 0),
        "prev_github_watchers": prev_github.get("watchers", 0),
        "prev_github_open_issues": prev_github.get("open_issues", 0),
        "prev_github_contributors": github_contributors,  # contributors not stored historically
        "github_stars_delta_str": _format_delta_int(
            github.get("stars", 0) - prev_github.get("stars", 0)
        ),
        "github_forks_delta_str": _format_delta_int(
            github.get("forks", 0) - prev_github.get("forks", 0)
        ),
        "github_watchers_delta_str": _format_delta_int(
            github.get("watchers", 0) - prev_github.get("watchers", 0)
        ),
        "github_open_issues_delta_str": _format_delta_int(
            github.get("open_issues", 0) - prev_github.get("open_issues", 0)
        ),
        "github_contributors_delta_str": "0",
        # Narrative
        "executive_summary_lead": executive_summary_lead,
        # Sub-tables (markdown blocks)
        "cloud_installs_table": _build_cloud_installs_table(metrics, prev_metrics),
        "engagement_recent_days_table": _build_engagement_table(active_rows),
        "compute_platform_snapshots_table": _read_compute_snapshots(str(compute_snapshots_path)),
        "version_adoption_table": _build_version_adoption_table(metrics),
        "upgrade_trajectories_count": len(metrics.get("upgrade_trajectories", [])),
        "upgrade_trajectories_table": _build_upgrade_trajectories_table(metrics),
        "feature_adoption_table": _build_feature_adoption_table(metrics),
        "embeddings_backend_table": _build_embeddings_backend_table(metrics),
        "sticky_cloud_compute_table": _build_sticky_cloud_compute_table(metrics, prev_metrics),
        "most_active_instances_table": _read_section_from_tables_md(
            str(tables_md_path), "Most Active Instances (by Feature Usage)"
        ),
        "largest_catalogs_table": _read_section_from_tables_md(
            str(tables_md_path), "Largest Catalogs (by Registered Servers + Agents + Skills)"
        ),
        "most_engaged_operators_table": _read_section_from_tables_md(
            str(tables_md_path), "Most Engaged Operators (by Upgrade-Chain Length)"
        ),
        "detection_by_version_narrative": _build_detection_by_version_narrative(
            str(output_dir / f"detection-by-version-{date_str}.csv")
        ),
        "architecture_patterns": _build_architecture_patterns(metrics, liveness),
        # Community vs internal split (by version-string classification)
        "prod_internal_yesterday_date": pi_yesterday_date,
        "prod_internal_yesterday_total": pi_y_total,
        "prod_internal_yesterday_production": pi_y_prod,
        "prod_internal_yesterday_internal": pi_y_internal,
        "prod_internal_yesterday_production_pct": pi_y_prod_pct,
        "prod_internal_yesterday_internal_pct": pi_y_internal_pct,
        "prod_internal_cumulative_total": pi_c_total,
        "prod_internal_cumulative_production": pi_c_prod,
        "prod_internal_cumulative_internal": pi_c_internal,
        "prod_internal_cumulative_production_pct": pi_c_prod_pct,
        "prod_internal_cumulative_internal_pct": pi_c_internal_pct,
        "prod_version_table": _build_prod_internal_version_table(prod_internal, "community"),
        "internal_version_table": _build_prod_internal_version_table(prod_internal, "internal"),
    }

    return vars_


def _days_between(
    start: str,
    end: str,
) -> int:
    """Return integer days between two YYYY-MM-DD dates."""
    try:
        s = datetime.strptime(start, "%Y-%m-%d")
        e = datetime.strptime(end, "%Y-%m-%d")
        return (e - s).days
    except (ValueError, TypeError):
        return 0


def _render(
    template: str,
    vars_: dict,
) -> str:
    """Substitute {var} placeholders in template with values from vars_.

    Uses Python str.format_map with a defaulting wrapper so a missing key
    becomes a visible "(missing: keyname)" rather than crashing the run.
    """

    class DefaultDict(dict):
        def __missing__(self, key):
            logger.warning(f"Template key missing: {key!r}")
            return f"(missing: {key})"

    return template.format_map(DefaultDict(vars_))


def main() -> None:
    """Entry point: render the report markdown."""
    parser = argparse.ArgumentParser(
        description="Render the usage-report markdown deterministically",
    )
    parser.add_argument(
        "--date",
        required=True,
        help="Report date YYYY-MM-DD",
    )
    parser.add_argument(
        "--output-dir",
        required=True,
        help="Dated subfolder containing the per-day analyzer outputs",
    )
    parser.add_argument(
        "--search-dir",
        default=None,
        help="Parent dir for cross-snapshot lookups (defaults to parent of --output-dir)",
    )
    parser.add_argument(
        "--template",
        default=None,
        help="Path to report_template.md (defaults to skill-relative path)",
    )
    parser.add_argument(
        "--output",
        default=None,
        help="Output markdown path (defaults to ai-registry-usage-report-DATE.md in output-dir)",
    )
    args = parser.parse_args()

    if args.template is None:
        args.template = os.path.join(
            os.path.dirname(os.path.abspath(__file__)),
            "report_template.md",
        )
    if args.output is None:
        args.output = str(Path(args.output_dir) / f"ai-registry-usage-report-{args.date}.md")

    if not os.path.exists(args.template):
        logger.error(f"Template not found: {args.template}")
        raise SystemExit(1)

    template_text = Path(args.template).read_text()
    logger.info(f"Loaded template ({len(template_text)} bytes) from {args.template}")

    vars_ = _build_template_vars(args)
    logger.info(f"Built {len(vars_)} template vars")

    # Inject the recommendations section last (depends on all other vars + extras)
    from recommendations import build_recommendations  # noqa: E402

    vars_["recommendations_section"] = build_recommendations(vars_, args)
    logger.info("Generated recommendations section")

    rendered = _render(template_text, vars_)
    Path(args.output).write_text(rendered)
    logger.info(f"Report rendered: {args.output} ({len(rendered)} bytes)")


if __name__ == "__main__":
    sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
    main()
