// Code generated by MockGen. DO NOT EDIT.
// Source: elicitation.go
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_elicitation_requester.go -package=mocks -source=elicitation.go ElicitationRequester
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	vmcp "github.com/stacklok/toolhive/pkg/vmcp"
	gomock "go.uber.org/mock/gomock"
)

// MockElicitationRequester is a mock of ElicitationRequester interface.
type MockElicitationRequester struct {
	ctrl     *gomock.Controller
	recorder *MockElicitationRequesterMockRecorder
	isgomock struct{}
}

// MockElicitationRequesterMockRecorder is the mock recorder for MockElicitationRequester.
type MockElicitationRequesterMockRecorder struct {
	mock *MockElicitationRequester
}

// NewMockElicitationRequester creates a new mock instance.
func NewMockElicitationRequester(ctrl *gomock.Controller) *MockElicitationRequester {
	mock := &MockElicitationRequester{ctrl: ctrl}
	mock.recorder = &MockElicitationRequesterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockElicitationRequester) EXPECT() *MockElicitationRequesterMockRecorder {
	return m.recorder
}

// RequestElicitation mocks base method.
func (m *MockElicitationRequester) RequestElicitation(ctx context.Context, req vmcp.ElicitationRequest) (*vmcp.ElicitationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequestElicitation", ctx, req)
	ret0, _ := ret[0].(*vmcp.ElicitationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RequestElicitation indicates an expected call of RequestElicitation.
func (mr *MockElicitationRequesterMockRecorder) RequestElicitation(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestElicitation", reflect.TypeOf((*MockElicitationRequester)(nil).RequestElicitation), ctx, req)
}
