# Copyright (c) ModelScope Contributors. All rights reserved.
# yapf: disable
import argparse
import asyncio
import json
import os
import sys
import tempfile

MS_AGENT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))

# Ensure ms_agent is importable
if MS_AGENT_ROOT not in sys.path:
    sys.path.insert(0, MS_AGENT_ROOT)


async def connect(stack):
    """Connect to the ms-agent MCP server and return a session.

    Uses the provided AsyncExitStack to manage transport and session lifetimes.
    """
    from mcp import ClientSession, StdioServerParameters
    from mcp.client.stdio import stdio_client

    params = StdioServerParameters(
        command=sys.executable,
        args=['-m', 'ms_agent.capabilities.mcp_server'],
        env={**os.environ, 'PYTHONPATH': MS_AGENT_ROOT},
    )

    read, write = await stack.enter_async_context(stdio_client(params))
    session = await stack.enter_async_context(ClientSession(read, write))
    await session.initialize()
    return session


async def list_tools(session):
    """List all available MCP tools."""
    result = await session.list_tools()
    print(f'\n{"=" * 60}')
    print(f'  Available MCP Tools ({len(result.tools)} total)')
    print(f'{"=" * 60}\n')
    for tool in result.tools:
        desc = (tool.description or '')[:70]
        print(f'  {tool.name:35s}  {desc}')
    print()
    return result.tools


async def call_tool(session, name: str, args: dict):
    """Call an MCP tool and return the parsed result."""
    from mcp import types

    print(f'\n--- Calling: {name}({json.dumps(args, ensure_ascii=False)[:100]}) ---')
    result = await asyncio.wait_for(
        session.call_tool(name, arguments=args),
        timeout=60,
    )
    parts = []
    for block in result.content:
        if isinstance(block, types.TextContent):
            parts.append(block.text)
    text = '\n'.join(parts)
    try:
        parsed = json.loads(text)
        print(json.dumps(parsed, indent=2, ensure_ascii=False))
        return parsed
    except json.JSONDecodeError:
        print(text[:500])
        return text


async def test_filesystem(session):
    """Test filesystem tools: write a file, then replace contents."""
    print(f'\n{"=" * 60}')
    print('  TEST: Filesystem Tools')
    print(f'{"=" * 60}')

    with tempfile.NamedTemporaryFile(mode='w', suffix='.py', delete=False) as f:
        f.write('def hello():\n    print("Hello, World!")\n\nhello()\n')
        test_file = f.name

    print(f'\n  Created test file: {test_file}')
    print(f'  Original content:')
    with open(test_file) as f:
        for line in f:
            print(f'    {line}', end='')

    result = await call_tool(session, 'replace_file_contents', {
        'path': test_file,
        'source': 'def hello():\n    print("Hello, World!")',
        'target': 'def greet(name: str = "World"):\n    print(f"Hello, {name}!")',
    })
    assert 'error' not in result, f'replace_file_contents failed: {result}'

    print(f'\n  After replace_file_contents:')
    with open(test_file) as f:
        for line in f:
            print(f'    {line}', end='')

    result = await call_tool(session, 'replace_file_lines', {
        'path': test_file,
        'content': '# Auto-generated by ms-agent test\n',
        'start_line': 0,
    })
    assert 'error' not in result, f'replace_file_lines failed: {result}'

    print(f'\n  After replace_file_lines (insert at top):')
    with open(test_file) as f:
        for line in f:
            print(f'    {line}', end='')

    os.unlink(test_file)
    print(f'\n  Cleaned up: {test_file}')
    print('\n  FILESYSTEM TESTS: PASSED')


async def test_deep_research_async(session):
    """Test async deep research tools (submit/check/get without actually running)."""
    print(f'\n{"=" * 60}')
    print('  TEST: Deep Research Async Tools')
    print(f'{"=" * 60}')

    # submit_research_task should return immediately with a task_id
    # (it will fail to find the config in CI, but the response format is testable)
    result = await call_tool(session, 'submit_research_task', {
        'query': 'Test query for integration verification',
    })

    if 'error' in result:
        print(f'\n  submit_research_task returned error (expected if no config): {result["error"]}')
        print('  Testing check/get with a fake task_id...')

        result = await call_tool(session, 'check_research_progress', {
            'task_id': 'nonexistent',
        })
        assert 'error' in result
        print('  check_research_progress correctly returned error for unknown task_id')

        result = await call_tool(session, 'get_research_report', {
            'task_id': 'nonexistent',
        })
        assert 'error' in result
        print('  get_research_report correctly returned error for unknown task_id')
    else:
        task_id = result['task_id']
        print(f'\n  Task submitted: {task_id}')
        assert result['status'] == 'running'

        await asyncio.sleep(1)
        progress = await call_tool(session, 'check_research_progress', {
            'task_id': task_id,
        })
        print(f'  Progress check: status={progress["status"]}')

        report = await call_tool(session, 'get_research_report', {
            'task_id': task_id,
        })
        print(f'  Report check: status={report["status"]}')

    print('\n  DEEP RESEARCH ASYNC TESTS: PASSED')


async def test_web_search(session):
    """Test web_search tool with arxiv (no API key required)."""
    print(f'\n{"=" * 60}')
    print('  TEST: Web Search')
    print(f'{"=" * 60}')

    result = await call_tool(session, 'web_search', {
        'query': 'large language model agent framework',
        'engine_type': 'arxiv',
        'num_results': 3,
    })

    if 'error' in result:
        print(f'\n  web_search returned error: {result["error"]}')
        print('  (This may happen if arxiv is unreachable)')
    else:
        assert result['status'] == 'ok', f'Unexpected status: {result["status"]}'
        assert result['engine'] == 'arxiv'
        print(f'\n  Returned {result["count"]} results:')
        for i, r in enumerate(result.get('results', []), 1):
            print(f'    {i}. {r.get("title", "No title")[:60]}')
            print(f'       {r.get("url", "")}')

    print('\n  WEB SEARCH TESTS: PASSED')


async def test_agent_delegate(session):
    """Test agent delegate tools (async pattern only, to avoid blocking)."""
    print(f'\n{"=" * 60}')
    print('  TEST: Agent Delegate (Async)')
    print(f'{"=" * 60}')

    # Test check/get/cancel with unknown task_id (safe, no LLM needed)
    result = await call_tool(session, 'check_agent_task', {
        'task_id': 'nonexistent',
    })
    assert 'error' in result
    print('  check_agent_task correctly returned error for unknown task_id')

    result = await call_tool(session, 'get_agent_result', {
        'task_id': 'nonexistent',
    })
    assert 'error' in result
    print('  get_agent_result correctly returned error for unknown task_id')

    result = await call_tool(session, 'cancel_agent_task', {
        'task_id': 'nonexistent',
    })
    assert 'error' in result
    print('  cancel_agent_task correctly returned error for unknown task_id')

    print('\n  AGENT DELEGATE TESTS: PASSED')
    print('  (Note: submit/delegate tests skipped -- they require LLM API keys)')


async def main():
    parser = argparse.ArgumentParser(description='Test ms-agent MCP tools')
    parser.add_argument('--list', action='store_true', help='List tools only')
    parser.add_argument('--test', choices=['fs', 'dr', 'ws', 'ad', 'all'], default='all',
                        help='Which tests to run (fs=filesystem, dr=deep_research, ws=web_search, ad=agent_delegate)')
    args = parser.parse_args()

    try:
        from mcp import ClientSession  # noqa: F401
    except ImportError:
        print('ERROR: mcp package not installed. Run: pip install mcp')
        sys.exit(1)

    from contextlib import AsyncExitStack

    async with AsyncExitStack() as stack:
        session = await connect(stack)

        tools = await list_tools(session)

        if args.list:
            return

        if args.test in ('fs', 'all'):
            await test_filesystem(session)

        if args.test in ('dr', 'all'):
            await test_deep_research_async(session)

        if args.test in ('ws', 'all'):
            await test_web_search(session)

        if args.test in ('ad', 'all'):
            await test_agent_delegate(session)

        print(f'\n{"=" * 60}')
        print('  ALL TESTS PASSED')
        print(f'{"=" * 60}\n')


if __name__ == '__main__':
    asyncio.run(main())
