import type { SquidConfig } from '../types';
import { parseDomainConfig } from './domain-acl';
import { generateUpstreamProxySection } from './upstream-proxy';
import { generateAclSections } from './acl-generator';
import { generateAccessRules } from './access-rules';
import { buildConfigSections } from './config-sections';
import { validateApiProxyIp } from './validation';

// eslint-disable-next-line @typescript-eslint/no-require-imports
const { version: AWF_VERSION } = require('../../package.json') as { version: string };

/**
 * Generates Squid proxy configuration with domain whitelisting and optional blocklisting
 *
 * Supports both plain domains and wildcard patterns:
 * - Plain domains use dstdomain ACL (efficient, fast matching)
 * - Wildcard patterns use dstdom_regex ACL (regex matching)
 *
 * Blocked domains take precedence over allowed domains.
 *
 * Supports protocol-specific domain restrictions:
 * - http://domain.com  -> allow only HTTP traffic
 * - https://domain.com -> allow only HTTPS traffic
 * - domain.com         -> allow both HTTP and HTTPS (default)
 *
 * When sslBump is enabled, adds SSL Bump configuration for HTTPS inspection.
 *
 * @example
 * // Plain domain: github.com -> acl allowed_domains dstdomain .github.com
 * // Wildcard: *.github.com -> acl allowed_domains_regex dstdom_regex -i ^.*\.github\.com$
 * // HTTP only: http://api.example.com -> separate ACL with !CONNECT rule
 * // Blocked: internal.example.com -> acl blocked_domains dstdomain .internal.example.com
 */
export function generateSquidConfig(config: SquidConfig): string {
  const { domains, blockedDomains, port, sslBump, caFiles, sslDbPath, urlPatterns, enableHostAccess, allowHostPorts, enableDlp, dnsServers, upstreamProxy, apiProxyIp, apiProxyPorts, topologyPeers } = config;

  validateApiProxyIp(apiProxyIp);

  const { domainsByProto, patternsByProto } = parseDomainConfig(domains);
  const { aclLines, blockedDomainConfig } = generateAclSections(domainsByProto, patternsByProto, blockedDomains);
  const { accessRulesSection, denyRule } = generateAccessRules(
    domainsByProto,
    patternsByProto,
    blockedDomainConfig.accessRules
  );

  const allAclLines = [...blockedDomainConfig.aclLines];
  if (blockedDomainConfig.aclLines.length > 0 && aclLines.length > 0) {
    allAclLines.push('');
  }
  allAclLines.push(...aclLines);

  const aclSection = allAclLines.length > 0 ? allAclLines.join('\n') : '# No domains configured';
  const {
    dlpAclSection,
    dlpAccessSection,
    portConfig,
    sslBumpSection,
    sslBumpUrlAccessSection,
    portAclsAndRules,
    apiProxySection,
    allowedIpSection,
    dnsSection,
    topologyPeersSection,
  } = buildConfigSections({
    enableDlp,
    port,
    sslBump,
    caFiles,
    sslDbPath,
    urlPatterns,
    domains,
    domainsByProto,
    patternsByProto,
    enableHostAccess,
    allowHostPorts,
    apiProxyPorts,
    apiProxyIp,
    dnsServers,
    topologyPeers,
  });

  return `# Squid configuration for egress traffic control
# Generated by awf
${sslBump ? '\n# SSL Bump mode enabled - HTTPS traffic will be intercepted for URL inspection' : ''}

# Disable pinger (ICMP) - requires NET_RAW capability which we don't have for security
pinger_enable off

# PID file location - use proxy-owned directory since container runs as non-root
pid_filename /var/run/squid/squid.pid

# Custom log format with detailed connection information
# Format: timestamp client_ip:port dest_domain dest_ip:port protocol method status decision url user_agent
# Note: For CONNECT requests (HTTPS), the domain is in the URL field
logformat firewall_detailed %ts.%03tu %>a:%>p %{Host}>h %<a:%<p %rv %rm %>Hs %Ss:%Sh %ru "%{User-Agent}>h"

# Structured JSONL audit log for machine-readable analysis
# Note: Squid logformat does not JSON-escape strings, so fields like User-Agent
# could break JSON parsing. We omit User-Agent to reduce breakage risk.
logformat audit_jsonl {"_schema":"audit/v${AWF_VERSION}","timestamp":"%{%Y-%m-%dT%H:%M:%S}tg.%03tuZ","event":"http_access","client":"%>a","host":"%{Host}>h","dest":"%<a:%<p","method":"%rm","status":%>Hs,"decision":"%Ss","url":"%ru"}

# Access log and cache configuration
# Don't log healthcheck probes from localhost (using ACL filter on access_log)
acl healthcheck_localhost src 127.0.0.1 ::1
access_log /var/log/squid/access.log firewall_detailed !healthcheck_localhost
access_log /var/log/squid/audit.jsonl audit_jsonl !healthcheck_localhost
cache_log /var/log/squid/cache.log
cache deny all

${aclSection}
${dlpAclSection}
# Port configuration
${portConfig}
${sslBumpSection}

# Network ACLs
acl localnet src 10.0.0.0/8
acl localnet src 172.16.0.0/12
acl localnet src 192.168.0.0/16
acl localnet src fc00::/7
acl localnet src fe80::/10

${topologyPeersSection}${portAclsAndRules}
${apiProxySection}
${allowedIpSection}# Deny CONNECT to raw IP addresses (IPv4 and IPv6)
# Prevents bypassing domain-based filtering via direct IP connections
acl dst_ipv4 dstdom_regex ^[0-9]+\\.[0-9]+\\.[0-9]+\\.[0-9]+$
acl dst_ipv6 dstdom_regex ^\\[?[0-9a-fA-F:]+\\]?$
http_access deny dst_ipv4
http_access deny dst_ipv6
${dlpAccessSection}
${sslBumpUrlAccessSection}
${accessRulesSection}# Deny requests to unknown domains (not in allow-list)
# This applies to all sources including localnet
${denyRule}

# Allow from trusted sources (after domain filtering)
http_access allow localnet
http_access allow localhost

# Deny everything else
http_access deny all

# Disable caching
cache deny all

# DNS settings - Squid resolves all domains for HTTP/HTTPS traffic
${dnsSection}
${upstreamProxy ? '\n' + generateUpstreamProxySection(upstreamProxy) : ''}
# Forwarded headers
forwarded_for delete
via off

# Error page customization
error_directory /usr/share/squid/errors/en

# Memory and file descriptor limits
cache_mem 64 MB
maximum_object_size 0 KB

# Timeout settings for streaming/long-lived connections (AI inference APIs)
# read_timeout: Time to wait for data from server before giving up
# Increased to accommodate long AI inference calls and SSE streaming
read_timeout 30 minutes

# connect_timeout: Time to wait for TCP connection to origin server
connect_timeout 30 seconds

# request_timeout: Time to wait for client to send first request after connection
request_timeout 2 minutes

# persistent_request_timeout: Time to wait for next request on persistent connection
persistent_request_timeout 2 minutes

# pconn_timeout: How long to keep idle persistent connections to servers
pconn_timeout 2 minutes

# client_lifetime: Maximum time a client connection can be open
# Set high to accommodate long streaming sessions
client_lifetime 8 hours

# half_closed_clients: Allow half-closed connections for streaming
# Critical for SSE where server sends but client doesn't respond
half_closed_clients on

# shutdown_lifetime: Time to wait for active connections during shutdown
# Set to 0 because this is an ephemeral proxy — no connection draining needed
shutdown_lifetime 0 seconds

# Debugging (can be enabled for troubleshooting)
# debug_options ALL,1 33,2
`;
}
