PLUGIN_NAME = "_telegram_integration"
DOWNLOAD_FOLDER = "usr/uploads"
STATE_FILE = "usr/plugins/_telegram_integration/state.json"

# Context data keys
CTX_TG_BOT = "telegram_bot"
CTX_TG_BOT_CFG = "telegram_bot_cfg"
CTX_TG_CHAT_ID = "telegram_chat_id"
CTX_TG_CHAT_TYPE = "telegram_chat_type"
CTX_TG_USER_ID = "telegram_user_id"
CTX_TG_USERNAME = "telegram_username"
CTX_TG_TYPING_STOP = "_telegram_typing_stop"
CTX_TG_REPLY_TO = "_telegram_reply_to_message_id"
CTX_TG_STREAM_ENABLED = "telegram_stream_enabled"
CTX_TG_TOOLS_ENABLED = "telegram_tools_enabled"

# Transient
CTX_TG_ATTACHMENTS = "_telegram_response_attachments"
CTX_TG_KEYBOARD = "_telegram_response_keyboard"
CTX_TG_PROGRESS_MESSAGE_ID = "_telegram_progress_message_id"
CTX_TG_PROGRESS_LINES = "_telegram_progress_lines"
CTX_TG_RESPONSE_MESSAGE_ID = "_telegram_response_message_id"
CTX_TG_RESPONSE_TEXT = "_telegram_response_text"
CTX_TG_RESPONSE_LAST_UPDATE = "_telegram_response_last_update"
CTX_TG_ERROR_SENT = "_telegram_error_sent"
CTX_TG_HEARTBEAT_TASK = "_telegram_heartbeat_task"
CTX_TG_HEARTBEAT_STOP = "_telegram_heartbeat_stop"
