#!/usr/bin/env python3
"""Generate TODO-missing-tests.md and TODO-biome-issues.md at the repo root.

Combines output from generate-test-mirrors.py (for test placement issues)
and audit-biome-issues.py (for lint/format issues) into two actionable
markdown todo lists.

Usage
-----
    python3 scripts/generate-todo-lists.py [--dry-run]

Options
-------
--dry-run   Print the file contents to stdout instead of writing them.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

# Load sibling scripts by file path (names contain hyphens, not valid identifiers)
import importlib.util as _ilu

_SCRIPTS_DIR = Path(__file__).resolve().parent


def _load(name: str, filename: str):
    spec = _ilu.spec_from_file_location(name, _SCRIPTS_DIR / filename)
    mod = _ilu.module_from_spec(spec)  # type: ignore[arg-type]
    spec.loader.exec_module(mod)  # type: ignore[union-attr]
    return mod


REPO_ROOT = _SCRIPTS_DIR.parent
SRC_DIR = REPO_ROOT / "src"
TESTS_DIR = SRC_DIR / "tests"

MISSING_TESTS_OUT = REPO_ROOT / "TODO-missing-tests.md"
BIOME_ISSUES_OUT = REPO_ROOT / "TODO-biome-issues.md"

# ---------------------------------------------------------------------------
# Re-use logic from sibling scripts
# ---------------------------------------------------------------------------

def collect_test_issues() -> tuple[list[tuple[str, str, str]], list[str]]:
    """Return (warn_entries, missing_entries).

    warn_entries  : [(source_rel, flat_test_rel, mirror_test_rel), ...]
    missing_entries: [source_rel, ...]  — no test exists at all
    """
    _mirrors = _load("generate_test_mirrors", "generate-test-mirrors.py")
    collect_source_files = _mirrors.collect_source_files
    flat_test_path = _mirrors.flat_test_path
    mirror_test_path = _mirrors.mirror_test_path

    warns: list[tuple[str, str, str]] = []
    missing: list[str] = []

    for source in collect_source_files():
        mirror = mirror_test_path(source)
        flat = flat_test_path(source)
        source_rel = str(source.relative_to(SRC_DIR)).replace("\\", "/")

        if mirror.exists():
            continue  # properly mirrored — nothing to report
        if flat.exists() and flat != mirror:
            flat_rel = str(flat.relative_to(TESTS_DIR)).replace("\\", "/")
            mirror_rel = str(mirror.relative_to(TESTS_DIR)).replace("\\", "/")
            warns.append((source_rel, flat_rel, mirror_rel))
        else:
            missing.append(source_rel)

    return warns, missing


def collect_biome_issues() -> tuple[dict[str, int], dict[str, list[tuple[str, int, str]]]]:
    """Return (category_counts, {category: [(file, line, msg), ...]})."""
    _biome = _load("audit_biome_issues", "audit-biome-issues.py")
    diags = _biome.run_biome()
    return _biome.parse_diagnostics(diags)


# ---------------------------------------------------------------------------
# Renderers
# ---------------------------------------------------------------------------

def render_missing_tests(
    warns: list[tuple[str, str, str]],
    missing: list[str],
) -> str:
    lines: list[str] = []
    lines.append("# TODO — Missing / Misplaced Tests")
    lines.append("")
    lines.append(
        "> Auto-generated by `scripts/generate-todo-lists.py`.  "
        "Re-run after adding or moving tests."
    )
    lines.append("")

    # ── Section 1: misplaced flat tests ────────────────────────────────────
    lines.append(f"## Misplaced flat tests  ({len(warns)})")
    lines.append("")
    lines.append(
        "These source files have a test, but the test lives at the wrong "
        "path (flat, not mirrored).  Move/rename the test file to the "
        "**Target** path."
    )
    lines.append("")
    if warns:
        lines.append("| Source | Current test | Target (mirrored) |")
        lines.append("|--------|-------------|-------------------|")
        for src, flat, mirror in sorted(warns):
            lines.append(f"| `{src}` | `tests/{flat}` | `tests/{mirror}` |")
    else:
        lines.append("_None — all existing tests are correctly placed._")
    lines.append("")

    # ── Section 2: no test at all ──────────────────────────────────────────
    lines.append(f"## No test file at all  ({len(missing)})")
    lines.append("")
    lines.append(
        "These source files have no test stub anywhere.  "
        "Run `npm run generate:test-mirrors` to create stubs, "
        "then fill in the `it.todo()` placeholders."
    )
    lines.append("")
    if missing:
        for src in sorted(missing):
            lines.append(f"- [ ] `{src}`")
    else:
        lines.append("_None — every source file has a test stub._")
    lines.append("")

    return "\n".join(lines)


CATEGORY_NOTES: dict[str, str] = {
    "lint/suspicious/noExplicitAny": "Replace `any` with a proper type or `unknown`.",
    "lint/correctness/noUnusedImports": "Remove the unused import.",
    "lint/correctness/noUnusedVariables": "Remove or use the variable.",
    "lint/correctness/noUnusedFunctionParameters": "Prefix with `_` or remove the parameter.",
    "lint/correctness/noUnusedPrivateClassMembers": "Remove or use the private member.",
    "lint/style/noNonNullAssertion": "Replace `!` with a proper null-check.",
    "lint/complexity/noStaticOnlyClass": "Convert to a plain module/namespace.",
    "assist/source/organizeImports": "Run `npm run check:fix` to auto-sort imports.",
    "format": "Run `npm run format:fix` to auto-fix formatting.",
    "lint/style/useTemplate": "Use a template literal instead of string concatenation.",
    "lint/complexity/useOptionalChain": "Replace `&&` chain with optional chaining `?.`.",
    "lint/complexity/useLiteralKeys": "Use a literal key instead of computed expression.",
    "lint/style/useImportType": "Use `import type` for type-only imports.",
    "lint/complexity/noBannedTypes": "Replace the banned type with the recommended alternative.",
}

AUTO_FIXABLE = {
    "assist/source/organizeImports",
    "format",
    "lint/style/useTemplate",
    "lint/complexity/useOptionalChain",
    "lint/complexity/useLiteralKeys",
    "lint/style/useImportType",
}


def render_biome_issues(
    cats: dict[str, int],
    by_cat: dict[str, list[tuple[str, int, str]]],
) -> str:
    from collections import defaultdict

    lines: list[str] = []
    lines.append("# TODO — Biome Lint / Format Issues")
    lines.append("")
    lines.append(
        "> Auto-generated by `scripts/generate-todo-lists.py`.  "
        "Re-run after fixing issues.  "
        "Auto-fixable categories are marked **[auto-fix]** — "
        "run `npm run check:fix` to resolve them in bulk."
    )
    lines.append("")

    total = sum(cats.values())
    lines.append(f"**Total diagnostics: {total}**")
    lines.append("")

    # Summary table
    lines.append("## Summary")
    lines.append("")
    lines.append("| Category | Count | Auto-fix? | Guidance |")
    lines.append("|----------|------:|:---------:|---------|")
    for cat, count in sorted(cats.items(), key=lambda x: -x[1]):
        auto = "✅" if cat in AUTO_FIXABLE else ""
        note = CATEGORY_NOTES.get(cat, "")
        lines.append(f"| `{cat}` | {count} | {auto} | {note} |")
    lines.append("")

    # Group by file across all categories for a per-file view
    file_issues: dict[str, list[tuple[str, int, str]]] = defaultdict(list)
    for cat, entries in by_cat.items():
        for path, lineno, msg in entries:
            try:
                rel = str(Path(path).relative_to(REPO_ROOT)).replace("\\", "/")
            except ValueError:
                rel = path
            file_issues[rel].append((cat, lineno, msg))

    lines.append("## Detail by file")
    lines.append("")
    for filepath in sorted(file_issues):
        issues = sorted(file_issues[filepath], key=lambda x: x[1])
        lines.append(f"### `{filepath}`")
        lines.append("")
        for cat, lineno, msg in issues:
            loc = f"L{lineno} " if lineno else ""
            auto_tag = " **[auto-fix]**" if cat in AUTO_FIXABLE else ""
            lines.append(f"- [ ] {loc}`{cat}`{auto_tag} — {msg}")
        lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dry-run", action="store_true", help="Print to stdout, don't write files.")
    args = parser.parse_args(argv)

    print("Collecting test mirror issues…")
    warns, missing = collect_test_issues()
    print(f"  misplaced: {len(warns)}  missing: {len(missing)}")

    print("Running Biome audit…")
    cats, by_cat = collect_biome_issues()
    total_biome = sum(cats.values())
    print(f"  {total_biome} diagnostics across {len(cats)} categories")

    tests_content = render_missing_tests(warns, missing)
    biome_content = render_biome_issues(cats, by_cat)

    if args.dry_run:
        print("\n" + "=" * 60)
        print(f"  {MISSING_TESTS_OUT.name}  (dry-run)")
        print("=" * 60)
        print(tests_content)
        print("\n" + "=" * 60)
        print(f"  {BIOME_ISSUES_OUT.name}  (dry-run)")
        print("=" * 60)
        print(biome_content)
        return 0

    MISSING_TESTS_OUT.write_text(tests_content, encoding="utf-8")
    print(f"Written: {MISSING_TESTS_OUT.relative_to(REPO_ROOT)}")

    BIOME_ISSUES_OUT.write_text(biome_content, encoding="utf-8")
    print(f"Written: {BIOME_ISSUES_OUT.relative_to(REPO_ROOT)}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
