// Copyright 2026 The Kubernetes Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	gentype "k8s.io/client-go/gentype"
	apiv1beta1 "sigs.k8s.io/agent-sandbox/clients/k8s/extensions/clientset/versioned/typed/api/v1beta1"
	v1beta1 "sigs.k8s.io/agent-sandbox/extensions/api/v1beta1"
)

// fakeSandboxWarmPools implements SandboxWarmPoolInterface
type fakeSandboxWarmPools struct {
	*gentype.FakeClientWithList[*v1beta1.SandboxWarmPool, *v1beta1.SandboxWarmPoolList]
	Fake *FakeExtensionsV1beta1
}

func newFakeSandboxWarmPools(fake *FakeExtensionsV1beta1, namespace string) apiv1beta1.SandboxWarmPoolInterface {
	return &fakeSandboxWarmPools{
		gentype.NewFakeClientWithList[*v1beta1.SandboxWarmPool, *v1beta1.SandboxWarmPoolList](
			fake.Fake,
			namespace,
			v1beta1.SchemeGroupVersion.WithResource("sandboxwarmpools"),
			v1beta1.SchemeGroupVersion.WithKind("SandboxWarmPool"),
			func() *v1beta1.SandboxWarmPool { return &v1beta1.SandboxWarmPool{} },
			func() *v1beta1.SandboxWarmPoolList { return &v1beta1.SandboxWarmPoolList{} },
			func(dst, src *v1beta1.SandboxWarmPoolList) { dst.ListMeta = src.ListMeta },
			func(list *v1beta1.SandboxWarmPoolList) []*v1beta1.SandboxWarmPool {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1beta1.SandboxWarmPoolList, items []*v1beta1.SandboxWarmPool) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
