/*
 * Copyright 2024-2026 Embabel Pty Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package architecture

import com.embabel.agent.api.common.Asyncer
import com.tngtech.archunit.core.domain.JavaClass
import com.tngtech.archunit.core.domain.JavaField
import com.tngtech.archunit.core.domain.JavaModifier
import com.tngtech.archunit.core.importer.ImportOption
import com.tngtech.archunit.junit.AnalyzeClasses
import com.tngtech.archunit.junit.ArchTest
import com.tngtech.archunit.lang.ArchCondition
import com.tngtech.archunit.lang.ArchRule
import com.tngtech.archunit.lang.ConditionEvents
import com.tngtech.archunit.lang.SimpleConditionEvent
import com.tngtech.archunit.lang.syntax.ArchRuleDefinition.classes
import org.junit.jupiter.api.Tag
import javax.annotation.concurrent.GuardedBy
import javax.annotation.concurrent.ThreadSafe

/**
 * Thread-safety architecture rules.
 *
 * These tests enforce thread-safety contracts at the architectural level:
 * 1. Asyncer implementations must be annotated @ThreadSafe
 * 2. @ThreadSafe classes must not have unguarded mutable fields
 *
 * Run tests:
 * mvn test -Dtest=ThreadSafetyRulesTest -Dsurefire.failIfNoSpecifiedTests=false
 */
@Tag("architecture")
@AnalyzeClasses(
    packages = ["com.embabel.agent"],
    importOptions = [ImportOption.DoNotIncludeTests::class]
)
class ThreadSafetyRulesTest {

    /**
     * Asyncer implementations must be explicitly marked as thread-safe.
     * This ensures developers consciously design for concurrent execution.
     */
    @ArchTest
    val asyncerImplementationsShouldBeThreadSafe: ArchRule =
        classes().that().implement(Asyncer::class.java)
            .should().beAnnotatedWith(ThreadSafe::class.java)
            .because("Asyncer implementations handle concurrent execution and must be thread-safe")

    /**
     * Classes annotated @ThreadSafe must not have mutable (non-final) fields
     * unless those fields are annotated with @GuardedBy to document synchronization.
     *
     * This catches:
     * - var fields without @GuardedBy → FAIL
     * - val fields → PASS (final reference)
     * - var fields with @GuardedBy → PASS (documented synchronization)
     */
    @ArchTest
    val threadSafeClassesShouldNotHaveUnguardedMutableFields: ArchRule =
        classes().that().areAnnotatedWith(ThreadSafe::class.java)
            .should(haveNoUnguardedMutableFields())
            .because("@ThreadSafe classes must not have mutable fields without @GuardedBy annotation")

    /**
     * ArchCondition that checks for non-final fields without @GuardedBy in @ThreadSafe classes.
     */
    private fun haveNoUnguardedMutableFields() = object : ArchCondition<JavaClass>(
        "have no unguarded mutable fields"
    ) {
        override fun check(javaClass: JavaClass, events: ConditionEvents) {
            javaClass.fields
                .filter { field -> isUnguardedMutableField(field) }
                .forEach { field ->
                    val message = "${javaClass.name} has non-final field '${field.name}' without @GuardedBy. " +
                        "Either make it final (val) or add @GuardedBy to document synchronization."
                    events.add(SimpleConditionEvent.violated(field, message))
                }
        }

        private fun isUnguardedMutableField(field: JavaField): Boolean {
            // Skip static fields (class-level, different concern)
            if (field.modifiers.contains(JavaModifier.STATIC)) return false

            // Skip final fields (immutable reference)
            if (field.modifiers.contains(JavaModifier.FINAL)) return false

            // Skip synthetic fields (generated by compiler, e.g., for lambdas)
            if (field.modifiers.contains(JavaModifier.SYNTHETIC)) return false

            // Non-final field - must have @GuardedBy
            return !field.isAnnotatedWith(GuardedBy::class.java)
        }
    }
}
