//go:build !ignore_autogenerated

/*
Copyright 2025 Stacklok

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package config

import (
	"github.com/stacklok/toolhive/pkg/audit"
	"github.com/stacklok/toolhive/pkg/ratelimit/types"
	"github.com/stacklok/toolhive/pkg/telemetry"
	authtypes "github.com/stacklok/toolhive/pkg/vmcp/auth/types"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AggregationConfig) DeepCopyInto(out *AggregationConfig) {
	*out = *in
	if in.ConflictResolutionConfig != nil {
		in, out := &in.ConflictResolutionConfig, &out.ConflictResolutionConfig
		*out = new(ConflictResolutionConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Tools != nil {
		in, out := &in.Tools, &out.Tools
		*out = make([]*WorkloadToolConfig, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(WorkloadToolConfig)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AggregationConfig.
func (in *AggregationConfig) DeepCopy() *AggregationConfig {
	if in == nil {
		return nil
	}
	out := new(AggregationConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthzConfig) DeepCopyInto(out *AuthzConfig) {
	*out = *in
	if in.Policies != nil {
		in, out := &in.Policies, &out.Policies
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthzConfig.
func (in *AuthzConfig) DeepCopy() *AuthzConfig {
	if in == nil {
		return nil
	}
	out := new(AuthzConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CircuitBreakerConfig) DeepCopyInto(out *CircuitBreakerConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CircuitBreakerConfig.
func (in *CircuitBreakerConfig) DeepCopy() *CircuitBreakerConfig {
	if in == nil {
		return nil
	}
	out := new(CircuitBreakerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CodeModeConfig) DeepCopyInto(out *CodeModeConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CodeModeConfig.
func (in *CodeModeConfig) DeepCopy() *CodeModeConfig {
	if in == nil {
		return nil
	}
	out := new(CodeModeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CompositeToolConfig) DeepCopyInto(out *CompositeToolConfig) {
	*out = *in
	in.Parameters.DeepCopyInto(&out.Parameters)
	if in.Steps != nil {
		in, out := &in.Steps, &out.Steps
		*out = make([]WorkflowStepConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Output != nil {
		in, out := &in.Output, &out.Output
		*out = new(OutputConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = new(ToolAnnotationsOverride)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CompositeToolConfig.
func (in *CompositeToolConfig) DeepCopy() *CompositeToolConfig {
	if in == nil {
		return nil
	}
	out := new(CompositeToolConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CompositeToolRef) DeepCopyInto(out *CompositeToolRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CompositeToolRef.
func (in *CompositeToolRef) DeepCopy() *CompositeToolRef {
	if in == nil {
		return nil
	}
	out := new(CompositeToolRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Config) DeepCopyInto(out *Config) {
	*out = *in
	if in.Backends != nil {
		in, out := &in.Backends, &out.Backends
		*out = make([]StaticBackendConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.IncomingAuth != nil {
		in, out := &in.IncomingAuth, &out.IncomingAuth
		*out = new(IncomingAuthConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.OutgoingAuth != nil {
		in, out := &in.OutgoingAuth, &out.OutgoingAuth
		*out = new(OutgoingAuthConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Aggregation != nil {
		in, out := &in.Aggregation, &out.Aggregation
		*out = new(AggregationConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.CompositeTools != nil {
		in, out := &in.CompositeTools, &out.CompositeTools
		*out = make([]CompositeToolConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CompositeToolRefs != nil {
		in, out := &in.CompositeToolRefs, &out.CompositeToolRefs
		*out = make([]CompositeToolRef, len(*in))
		copy(*out, *in)
	}
	if in.Operational != nil {
		in, out := &in.Operational, &out.Operational
		*out = new(OperationalConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Telemetry != nil {
		in, out := &in.Telemetry, &out.Telemetry
		*out = new(telemetry.Config)
		(*in).DeepCopyInto(*out)
	}
	if in.Audit != nil {
		in, out := &in.Audit, &out.Audit
		*out = new(audit.Config)
		(*in).DeepCopyInto(*out)
	}
	if in.Optimizer != nil {
		in, out := &in.Optimizer, &out.Optimizer
		*out = new(OptimizerConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.CodeMode != nil {
		in, out := &in.CodeMode, &out.CodeMode
		*out = new(CodeModeConfig)
		**out = **in
	}
	if in.SessionStorage != nil {
		in, out := &in.SessionStorage, &out.SessionStorage
		*out = new(SessionStorageConfig)
		**out = **in
	}
	if in.RateLimiting != nil {
		in, out := &in.RateLimiting, &out.RateLimiting
		*out = new(types.RateLimitConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.PassthroughHeaders != nil {
		in, out := &in.PassthroughHeaders, &out.PassthroughHeaders
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Config.
func (in *Config) DeepCopy() *Config {
	if in == nil {
		return nil
	}
	out := new(Config)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConflictResolutionConfig) DeepCopyInto(out *ConflictResolutionConfig) {
	*out = *in
	if in.PriorityOrder != nil {
		in, out := &in.PriorityOrder, &out.PriorityOrder
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConflictResolutionConfig.
func (in *ConflictResolutionConfig) DeepCopy() *ConflictResolutionConfig {
	if in == nil {
		return nil
	}
	out := new(ConflictResolutionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElicitationResponseConfig) DeepCopyInto(out *ElicitationResponseConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElicitationResponseConfig.
func (in *ElicitationResponseConfig) DeepCopy() *ElicitationResponseConfig {
	if in == nil {
		return nil
	}
	out := new(ElicitationResponseConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FailureHandlingConfig) DeepCopyInto(out *FailureHandlingConfig) {
	*out = *in
	if in.CircuitBreaker != nil {
		in, out := &in.CircuitBreaker, &out.CircuitBreaker
		*out = new(CircuitBreakerConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FailureHandlingConfig.
func (in *FailureHandlingConfig) DeepCopy() *FailureHandlingConfig {
	if in == nil {
		return nil
	}
	out := new(FailureHandlingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IncomingAuthConfig) DeepCopyInto(out *IncomingAuthConfig) {
	*out = *in
	if in.OIDC != nil {
		in, out := &in.OIDC, &out.OIDC
		*out = new(OIDCConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Authz != nil {
		in, out := &in.Authz, &out.Authz
		*out = new(AuthzConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IncomingAuthConfig.
func (in *IncomingAuthConfig) DeepCopy() *IncomingAuthConfig {
	if in == nil {
		return nil
	}
	out := new(IncomingAuthConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OIDCConfig) DeepCopyInto(out *OIDCConfig) {
	*out = *in
	if in.Scopes != nil {
		in, out := &in.Scopes, &out.Scopes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OIDCConfig.
func (in *OIDCConfig) DeepCopy() *OIDCConfig {
	if in == nil {
		return nil
	}
	out := new(OIDCConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperationalConfig) DeepCopyInto(out *OperationalConfig) {
	*out = *in
	if in.Timeouts != nil {
		in, out := &in.Timeouts, &out.Timeouts
		*out = new(TimeoutConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.FailureHandling != nil {
		in, out := &in.FailureHandling, &out.FailureHandling
		*out = new(FailureHandlingConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperationalConfig.
func (in *OperationalConfig) DeepCopy() *OperationalConfig {
	if in == nil {
		return nil
	}
	out := new(OperationalConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OptimizerConfig) DeepCopyInto(out *OptimizerConfig) {
	*out = *in
	if in.EmbeddingHeaders != nil {
		in, out := &in.EmbeddingHeaders, &out.EmbeddingHeaders
		*out = make(map[string]EmbeddingHeaderValue, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OptimizerConfig.
func (in *OptimizerConfig) DeepCopy() *OptimizerConfig {
	if in == nil {
		return nil
	}
	out := new(OptimizerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OutgoingAuthConfig) DeepCopyInto(out *OutgoingAuthConfig) {
	*out = *in
	if in.Default != nil {
		in, out := &in.Default, &out.Default
		*out = new(authtypes.BackendAuthStrategy)
		(*in).DeepCopyInto(*out)
	}
	if in.Backends != nil {
		in, out := &in.Backends, &out.Backends
		*out = make(map[string]*authtypes.BackendAuthStrategy, len(*in))
		for key, val := range *in {
			var outVal *authtypes.BackendAuthStrategy
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(authtypes.BackendAuthStrategy)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OutgoingAuthConfig.
func (in *OutgoingAuthConfig) DeepCopy() *OutgoingAuthConfig {
	if in == nil {
		return nil
	}
	out := new(OutgoingAuthConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OutputConfig) DeepCopyInto(out *OutputConfig) {
	*out = *in
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make(map[string]OutputProperty, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Required != nil {
		in, out := &in.Required, &out.Required
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OutputConfig.
func (in *OutputConfig) DeepCopy() *OutputConfig {
	if in == nil {
		return nil
	}
	out := new(OutputConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OutputProperty) DeepCopyInto(out *OutputProperty) {
	*out = *in
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make(map[string]OutputProperty, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	in.Default.DeepCopyInto(&out.Default)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OutputProperty.
func (in *OutputProperty) DeepCopy() *OutputProperty {
	if in == nil {
		return nil
	}
	out := new(OutputProperty)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SessionStorageConfig) DeepCopyInto(out *SessionStorageConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SessionStorageConfig.
func (in *SessionStorageConfig) DeepCopy() *SessionStorageConfig {
	if in == nil {
		return nil
	}
	out := new(SessionStorageConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StaticBackendConfig) DeepCopyInto(out *StaticBackendConfig) {
	*out = *in
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StaticBackendConfig.
func (in *StaticBackendConfig) DeepCopy() *StaticBackendConfig {
	if in == nil {
		return nil
	}
	out := new(StaticBackendConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StepErrorHandling) DeepCopyInto(out *StepErrorHandling) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StepErrorHandling.
func (in *StepErrorHandling) DeepCopy() *StepErrorHandling {
	if in == nil {
		return nil
	}
	out := new(StepErrorHandling)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeoutConfig) DeepCopyInto(out *TimeoutConfig) {
	*out = *in
	if in.PerWorkload != nil {
		in, out := &in.PerWorkload, &out.PerWorkload
		*out = make(map[string]Duration, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeoutConfig.
func (in *TimeoutConfig) DeepCopy() *TimeoutConfig {
	if in == nil {
		return nil
	}
	out := new(TimeoutConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolAnnotationsOverride) DeepCopyInto(out *ToolAnnotationsOverride) {
	*out = *in
	if in.Title != nil {
		in, out := &in.Title, &out.Title
		*out = new(string)
		**out = **in
	}
	if in.ReadOnlyHint != nil {
		in, out := &in.ReadOnlyHint, &out.ReadOnlyHint
		*out = new(bool)
		**out = **in
	}
	if in.DestructiveHint != nil {
		in, out := &in.DestructiveHint, &out.DestructiveHint
		*out = new(bool)
		**out = **in
	}
	if in.IdempotentHint != nil {
		in, out := &in.IdempotentHint, &out.IdempotentHint
		*out = new(bool)
		**out = **in
	}
	if in.OpenWorldHint != nil {
		in, out := &in.OpenWorldHint, &out.OpenWorldHint
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolAnnotationsOverride.
func (in *ToolAnnotationsOverride) DeepCopy() *ToolAnnotationsOverride {
	if in == nil {
		return nil
	}
	out := new(ToolAnnotationsOverride)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolConfigRef) DeepCopyInto(out *ToolConfigRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolConfigRef.
func (in *ToolConfigRef) DeepCopy() *ToolConfigRef {
	if in == nil {
		return nil
	}
	out := new(ToolConfigRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolOverride) DeepCopyInto(out *ToolOverride) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = new(ToolAnnotationsOverride)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolOverride.
func (in *ToolOverride) DeepCopy() *ToolOverride {
	if in == nil {
		return nil
	}
	out := new(ToolOverride)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkflowStepConfig) DeepCopyInto(out *WorkflowStepConfig) {
	*out = *in
	in.Arguments.DeepCopyInto(&out.Arguments)
	if in.DependsOn != nil {
		in, out := &in.DependsOn, &out.DependsOn
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.OnError != nil {
		in, out := &in.OnError, &out.OnError
		*out = new(StepErrorHandling)
		**out = **in
	}
	in.Schema.DeepCopyInto(&out.Schema)
	if in.OnDecline != nil {
		in, out := &in.OnDecline, &out.OnDecline
		*out = new(ElicitationResponseConfig)
		**out = **in
	}
	if in.OnCancel != nil {
		in, out := &in.OnCancel, &out.OnCancel
		*out = new(ElicitationResponseConfig)
		**out = **in
	}
	in.DefaultResults.DeepCopyInto(&out.DefaultResults)
	if in.InnerStep != nil {
		in, out := &in.InnerStep, &out.InnerStep
		*out = new(WorkflowStepConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkflowStepConfig.
func (in *WorkflowStepConfig) DeepCopy() *WorkflowStepConfig {
	if in == nil {
		return nil
	}
	out := new(WorkflowStepConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadToolConfig) DeepCopyInto(out *WorkloadToolConfig) {
	*out = *in
	if in.ToolConfigRef != nil {
		in, out := &in.ToolConfigRef, &out.ToolConfigRef
		*out = new(ToolConfigRef)
		**out = **in
	}
	if in.Filter != nil {
		in, out := &in.Filter, &out.Filter
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Overrides != nil {
		in, out := &in.Overrides, &out.Overrides
		*out = make(map[string]*ToolOverride, len(*in))
		for key, val := range *in {
			var outVal *ToolOverride
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(ToolOverride)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadToolConfig.
func (in *WorkloadToolConfig) DeepCopy() *WorkloadToolConfig {
	if in == nil {
		return nil
	}
	out := new(WorkloadToolConfig)
	in.DeepCopyInto(out)
	return out
}
