# Copyright (c) ModelScope Contributors. All rights reserved.
"""
ms-agent × OpenClaw  —  MCP integration test

Validates that the ms-agent MCP server works correctly when spawned
the same way OpenClaw would launch it (stdio subprocess with PYTHONPATH).

The test connects as a generic MCP client — identical JSON-RPC calls
regardless of whether OpenClaw, Hermes, nanobot, or Cursor is the host.

Usage:
  python test_openclaw_mcp.py               # run all tests
  python test_openclaw_mcp.py --list        # list tools only
  python test_openclaw_mcp.py --test ws     # test web_search only
  python test_openclaw_mcp.py --test fs,ws  # combined tests
"""
import argparse
import asyncio
import json
import os
import sys
import tempfile

MS_AGENT_ROOT = os.path.abspath(
    os.path.join(os.path.dirname(__file__), '..', '..', '..'))

if MS_AGENT_ROOT not in sys.path:
    sys.path.insert(0, MS_AGENT_ROOT)

from dotenv import load_dotenv
load_dotenv(os.path.join(MS_AGENT_ROOT, '.env'), override=False)


async def connect(stack):
    """Start an MCP Server subprocess the same way OpenClaw would."""
    from mcp import ClientSession, StdioServerParameters
    from mcp.client.stdio import stdio_client

    params = StdioServerParameters(
        command=sys.executable,
        args=['-m', 'ms_agent.capabilities.mcp_server'],
        env={**os.environ, 'PYTHONPATH': MS_AGENT_ROOT},
    )

    read, write = await stack.enter_async_context(stdio_client(params))
    session = await stack.enter_async_context(ClientSession(read, write))
    await session.initialize()
    return session


async def list_tools(session):
    result = await session.list_tools()
    print(f'\n{"=" * 64}')
    print(f'  MCP Server registered tools ({len(result.tools)})')
    print(f'{"=" * 64}\n')
    for tool in result.tools:
        desc = (tool.description or '')[:60]
        print(f'  {tool.name:38s} {desc}')
    print()
    return result.tools


async def call_tool(session, name: str, args: dict, timeout: int = 120):
    from mcp import types

    brief = json.dumps(args, ensure_ascii=False)
    if len(brief) > 80:
        brief = brief[:77] + '...'
    print(f'\n  >>> {name}({brief})')

    result = await asyncio.wait_for(
        session.call_tool(name, arguments=args),
        timeout=timeout,
    )

    text = '\n'.join(
        block.text for block in result.content
        if isinstance(block, types.TextContent)
    )

    try:
        parsed = json.loads(text)
        preview = json.dumps(parsed, indent=2, ensure_ascii=False)
        if len(preview) > 600:
            preview = preview[:597] + '...'
        print(f'  <<< {preview}')
        if isinstance(parsed, dict) and parsed.get('error'):
            print(f'  !! ERROR: {parsed["error"][:200]}')
        return parsed
    except json.JSONDecodeError:
        print(f'  <<< {text[:400]}')
        return text


def section(title: str):
    print(f'\n{"─" * 64}')
    print(f'  {title}')
    print(f'{"─" * 64}')


def ok(msg: str):
    print(f'  [PASS] {msg}')


def skip(msg: str):
    print(f'  [SKIP] {msg}')


def fail(msg: str):
    print(f'  [FAIL] {msg}')


async def test_filesystem(session):
    section('Filesystem Tools')

    with tempfile.NamedTemporaryFile(mode='w', suffix='.py',
                                     delete=False) as f:
        f.write('def hello():\n    print("Hello, World!")\n\nhello()\n')
        test_file = f.name
    print(f'  Temp file: {test_file}')

    r = await call_tool(session, 'replace_file_contents', {
        'path': test_file,
        'source': 'def hello():\n    print("Hello, World!")',
        'target': 'def greet(name="World"):\n    print(f"Hello, {name}!")',
    })
    assert 'error' not in r, r
    ok('replace_file_contents replacement succeeded')

    r = await call_tool(session, 'replace_file_lines', {
        'path': test_file,
        'content': '# Generated by ms-agent\n',
        'start_line': 0,
    })
    assert 'error' not in r, r
    ok('replace_file_lines header insertion succeeded')

    r = await call_tool(session, 'replace_file_contents', {
        'path': '/nonexistent/path.txt',
        'source': 'x',
        'target': 'y',
    })
    assert 'error' in r
    ok('Non-existent file correctly returned error')

    os.unlink(test_file)


async def test_web_search(session):
    section('Web Search')

    r = await call_tool(session, 'web_search', {
        'query': 'large language model agent framework',
        'engine_type': 'arxiv',
        'num_results': 3,
    })
    if 'error' not in r:
        assert r['status'] == 'ok'
        ok(f'arxiv search returned {r["count"]} results')
    else:
        fail(f'arxiv: {r["error"]}')

    if os.environ.get('EXA_API_KEY'):
        r = await call_tool(session, 'web_search', {
            'query': 'ModelScope agent framework',
            'engine_type': 'exa',
            'num_results': 2,
        })
        if 'error' not in r:
            ok(f'exa search returned {r.get("count", 0)} results')
        else:
            fail(f'exa: {r["error"]}')
    else:
        skip('EXA_API_KEY not set, skipping exa test')


async def test_agent_delegate(session):
    section('Agent Delegate')

    for tool_name in ['check_agent_task', 'get_agent_result',
                      'cancel_agent_task']:
        r = await call_tool(session, tool_name, {'task_id': 'nonexistent'})
        assert 'error' in r
    ok('check/get/cancel with unknown task_id all correctly returned errors')

    r = await call_tool(session, 'delegate_task', {'query': ''})
    assert 'error' in r
    ok('Empty query correctly rejected')

    if not os.environ.get('OPENAI_API_KEY'):
        skip('OPENAI_API_KEY not set, skipping real LLM call')
        return

    r = await call_tool(session, 'submit_agent_task', {
        'query': 'What is 2+2? Reply with ONLY the number.',
        'max_rounds': 1,
    })
    assert 'task_id' in r
    task_id = r['task_id']
    ok(f'Async task submitted: {task_id}')

    for _ in range(10):
        await asyncio.sleep(3)
        progress = await call_tool(session, 'check_agent_task',
                                   {'task_id': task_id})
        if progress.get('status') != 'running':
            break
    ok(f'Task status: {progress.get("status")}')

    result = await call_tool(session, 'get_agent_result',
                             {'task_id': task_id})
    if result.get('status') == 'completed':
        ok(f'LLM response: {result.get("response", "")[:100]}')
    else:
        fail(f'Task not completed: {result}')


async def test_deep_research(session):
    section('Deep Research (Async)')

    r = await call_tool(session, 'submit_research_task', {
        'query': 'Integration test query',
    })
    if 'task_id' in r:
        task_id = r['task_id']
        ok(f'Task submitted: {task_id}')
        await asyncio.sleep(2)
        progress = await call_tool(session, 'check_research_progress',
                                   {'task_id': task_id})
        ok(f'Poll status: {progress.get("status")}')
    elif 'error' in r:
        ok(f'Expected error (no config): {r["error"][:80]}')
        r2 = await call_tool(session, 'check_research_progress',
                             {'task_id': 'fake'})
        assert 'error' in r2
        ok('Unknown task_id correctly returned error')


async def test_code_genesis(session):
    section('Code Genesis (Async)')

    r = await call_tool(session, 'check_code_genesis_progress',
                        {'task_id': 'fake'})
    assert 'error' in r
    r = await call_tool(session, 'get_code_genesis_result',
                        {'task_id': 'fake'})
    assert 'error' in r
    ok('check/get with unknown task_id both correctly returned errors')

    r = await call_tool(session, 'submit_code_genesis_task', {
        'query': 'Create a hello world Python CLI tool',
    })
    if 'task_id' in r:
        task_id = r['task_id']
        ok(f'Task submitted: {task_id}, output_dir: {r.get("output_dir", "?")}')

        for i in range(6):
            await asyncio.sleep(5)
            progress = await call_tool(session, 'check_code_genesis_progress',
                                       {'task_id': task_id})
            status = progress.get('status', '?')
            total_files = progress.get('total_files', 0)
            print(f'      [{(i+1)*5}s] status={status}, files={total_files}')
            if status == 'failed':
                fail(f'Task failed: {progress.get("error", "")[:200]}')
                return
            if total_files > 0 or status == 'completed':
                break
        if total_files > 0:
            ok(f'Code generation in progress, {total_files} files generated')
        elif status == 'running':
            ok(f'Task still running (status={status})')
        else:
            fail(f'Task abnormal: status={status}')
    else:
        fail(f'Submission failed: {r.get("error", "unknown")[:80]}')


async def test_fin_research(session):
    section('Financial Research (Async)')

    r = await call_tool(session, 'check_fin_research_progress',
                        {'task_id': 'fake'})
    assert 'error' in r
    r = await call_tool(session, 'get_fin_research_report',
                        {'task_id': 'fake'})
    assert 'error' in r
    ok('check/get with unknown task_id both correctly returned errors')

    r = await call_tool(session, 'submit_fin_research_task', {
        'query': 'Briefly describe the current market status of AAPL stock',
    })
    if 'task_id' in r:
        task_id = r['task_id']
        ok(f'Task submitted: {task_id}')

        for i in range(6):
            await asyncio.sleep(5)
            progress = await call_tool(
                session, 'check_fin_research_progress',
                {'task_id': task_id})
            status = progress.get('status', '?')
            has_plan = progress.get('has_plan', False)
            print(f'      [{(i+1)*5}s] status={status}, has_plan={has_plan}')
            if has_plan or status in ('completed', 'failed'):
                break
        if has_plan:
            ok('Orchestrator generated plan.json')
        elif status == 'failed':
            fail(f'Task failed: {progress.get("error", "")[:100]}')
        else:
            ok(f'Task still running (status={status}), exiting early')
    else:
        ok(f'Submission returned: {r.get("error", "ok")[:80]}')


async def test_video_generation(session):
    section('Video Generation / Singularity Cinema (Async)')

    r = await call_tool(session, 'check_video_generation_progress',
                        {'task_id': 'fake'})
    assert 'error' in r
    r = await call_tool(session, 'get_video_generation_result',
                        {'task_id': 'fake'})
    assert 'error' in r
    ok('check/get with unknown task_id both correctly returned errors')

    r = await call_tool(session, 'submit_video_generation_task', {
        'query': 'Create a 10-second video about artificial intelligence',
    })
    if 'task_id' in r:
        task_id = r['task_id']
        ok(f'Task submitted: {task_id}, output_dir: {r.get("output_dir", "?")}')

        for i in range(8):
            await asyncio.sleep(5)
            progress = await call_tool(
                session, 'check_video_generation_progress',
                {'task_id': task_id})
            status = progress.get('status', '?')
            steps = progress.get('completed_steps', [])
            print(f'      [{(i+1)*5}s] status={status}, '
                  f'steps={len(steps)}/9 {steps}')
            if status == 'failed':
                fail(f'Video generation failed: '
                     f'{progress.get("error", "")[:200]}')
                return
            if len(steps) > 0 or status == 'completed':
                break
        if steps:
            ok(f'Pipeline in progress, completed: {", ".join(steps)}')
        elif status == 'running':
            ok(f'Task still running (status={status})')
        else:
            fail(f'Task abnormal: status={status}')
    else:
        fail(f'Submission failed: {r.get("error", "unknown")[:80]}')


async def test_doc_research(session):
    section('Document Research (Async)')

    r = await call_tool(session, 'check_doc_research_progress',
                        {'task_id': 'fake'})
    assert 'error' in r
    r = await call_tool(session, 'get_doc_research_report',
                        {'task_id': 'fake'})
    assert 'error' in r
    ok('check/get with unknown task_id both correctly returned errors')

    r = await call_tool(session, 'submit_doc_research_task', {'query': ''})
    assert 'error' in r
    ok('Empty query correctly rejected')

    r = await call_tool(session, 'submit_doc_research_task', {
        'query': 'Summarize the key contributions of this paper',
        'urls': 'https://arxiv.org/abs/2504.17432',
    })
    if 'task_id' in r:
        task_id = r['task_id']
        ok(f'Task submitted: {task_id}')

        for i in range(12):
            await asyncio.sleep(10)
            progress = await call_tool(
                session, 'check_doc_research_progress',
                {'task_id': task_id})
            status = progress.get('status', '?')
            has_report = progress.get('report_available', False)
            print(f'      [{(i+1)*10}s] status={status}, '
                  f'report={has_report}')
            if status in ('completed', 'failed') or has_report:
                break
        if status == 'failed':
            fail(f'Document research failed: '
                 f'{progress.get("error", "")[:200]}')
        elif has_report:
            ok('Report generated!')
        else:
            ok(f'Workflow still running (status={status})')
    else:
        fail(f'Submission failed: {r.get("error", "unknown")[:80]}')


TESTS = {
    'fs':   (test_filesystem,       'Filesystem Tools'),
    'ws':   (test_web_search,       'Web Search'),
    'ad':   (test_agent_delegate,   'Agent Delegate'),
    'dr':   (test_deep_research,    'Deep Research'),
    'cg':   (test_code_genesis,     'Code Genesis'),
    'fr':   (test_fin_research,     'Financial Research'),
    'vg':   (test_video_generation, 'Video Generation'),
    'docr': (test_doc_research,     'Document Research'),
}


async def main():
    parser = argparse.ArgumentParser(
        description='ms-agent x OpenClaw MCP integration test',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog='Examples:\n'
               '  python test_openclaw_mcp.py --list        # list tools\n'
               '  python test_openclaw_mcp.py --test ws     # web search\n'
               '  python test_openclaw_mcp.py --test fs,ws  # combined\n'
               '  python test_openclaw_mcp.py               # all tests\n',
    )
    parser.add_argument('--list', action='store_true',
                        help='list available MCP tools only')
    parser.add_argument(
        '--test', default='all',
        help=f'tests to run (comma-separated): '
             f'{", ".join(TESTS)} or all (default: all)',
    )
    args = parser.parse_args()

    try:
        from mcp import ClientSession  # noqa: F401
    except ImportError:
        print('ERROR: mcp package not installed.  pip install mcp')
        sys.exit(1)

    from contextlib import AsyncExitStack

    async with AsyncExitStack() as stack:
        session = await connect(stack)
        tools = await list_tools(session)

        if args.list:
            return

        if args.test == 'all':
            selected = list(TESTS.keys())
        else:
            selected = [t.strip() for t in args.test.split(',')]
            unknown = [t for t in selected if t not in TESTS]
            if unknown:
                print(f'ERROR: unknown test(s): {unknown}')
                print(f'Available: {", ".join(TESTS)}')
                sys.exit(1)

        passed, failed_list = 0, []
        for key in selected:
            test_fn, name = TESTS[key]
            try:
                await test_fn(session)
                passed += 1
            except Exception as e:
                import traceback
                fail(f'{name} crashed: {e}')
                traceback.print_exc()
                failed_list.append(name)

        total = len(selected)
        print(f'\n{"=" * 64}')
        print(f'  Result: {passed}/{total} passed', end='')
        if failed_list:
            print(f', failed: {", ".join(failed_list)}')
        else:
            print(' -- ALL PASSED')
        print(f'{"=" * 64}\n')


if __name__ == '__main__':
    asyncio.run(main())
