"""Compatibility facade for the focused Nsight Graphics backend modules."""

from __future__ import annotations

from cli_anything.nsight_graphics.utils.backend.commands import (
    build_split_capture_command,
    build_replay_command,
    build_unified_command,
    ensure_at_most_one,
    ensure_exactly_one,
    format_env_values,
    format_program_args,
    prepare_output_dir,
    require_binary,
    require_launch_target,
)
from cli_anything.nsight_graphics.utils.backend.discovery import (
    ENV_VAR,
    INSTALL_INSTRUCTIONS,
    _BINARY_CANDIDATES,
    _candidate_dirs_from_env,
    _default_windows_install_dirs,
    _fixed_windows_drive_roots,
    _normalized_install_key,
    _override_value,
    _primary_executable,
    _read_registry_installations,
    _scan_directory,
    detect_tool_mode,
    discover_binaries,
    get_version,
    list_installations,
    probe_installation,
)
from cli_anything.nsight_graphics.utils.backend.execution import (
    _combined_output,
    activity_artifact_roots,
    default_output_dir,
    diff_snapshots,
    run_command,
    run_with_artifacts,
    snapshot_files,
)
from cli_anything.nsight_graphics.utils.backend.parsing import (
    _ACTIVITY_ALIASES,
    _extract_long_option,
    parse_option_help,
    parse_unified_help,
    resolve_activity_name,
)
from cli_anything.nsight_graphics.utils.backend.shared import (
    _command_string,
    _dedupe,
    _extract_version_from_path,
    _extract_version_from_text,
    _version_sort_key,
)

__all__ = [
    "ENV_VAR",
    "INSTALL_INSTRUCTIONS",
    "_ACTIVITY_ALIASES",
    "_BINARY_CANDIDATES",
    "_candidate_dirs_from_env",
    "_combined_output",
    "_command_string",
    "_dedupe",
    "_default_windows_install_dirs",
    "_extract_long_option",
    "_extract_version_from_path",
    "_extract_version_from_text",
    "_fixed_windows_drive_roots",
    "_normalized_install_key",
    "_override_value",
    "_primary_executable",
    "_read_registry_installations",
    "_scan_directory",
    "_version_sort_key",
    "activity_artifact_roots",
    "build_replay_command",
    "build_split_capture_command",
    "build_unified_command",
    "default_output_dir",
    "detect_tool_mode",
    "diff_snapshots",
    "discover_binaries",
    "ensure_at_most_one",
    "ensure_exactly_one",
    "format_env_values",
    "format_program_args",
    "get_version",
    "list_installations",
    "parse_option_help",
    "parse_unified_help",
    "prepare_output_dir",
    "probe_installation",
    "require_binary",
    "require_launch_target",
    "resolve_activity_name",
    "run_command",
    "run_with_artifacts",
    "snapshot_files",
]
